{
  "hash": "d36303665a1751c007702712c0a2132a",
  "result": {
    "engine": "knitr",
    "markdown": "---\n# The always-open companion to wk05-exercises.qmd.\n#\n# Same page, same content, solutions never gated -- for Carlisle and the TA.\n# The week file is the only source; this wrapper adds nothing but front matter.\n# To make one of these for a new week, copy this file and change the two\n# `wk05` strings below.\n#\n# `solution-unlock` in the past is what opens the solutions: the week file\n# does not set that key, so this one survives the include's metadata merge.\n# (`title` does not survive -- the week file's wins -- hence the subtitle.)\nsubtitle: \"Instructor and TA copy: complete solutions, always open\"\nsolution-unlock: \"2000-01-01 00:00\"\n\n# Keep it off the site's search box and out of Google.\nsearch: false\nformat:\n  html:\n    include-in-header:\n      text: '<meta name=\"robots\" content=\"noindex, nofollow\">'\n---\n\n---\ntitle: \"Week 5 Exercises\"\ndistributed: 2026-09-22\nshow-hints: true\n---\n\n\n\n\nNote: The important **prospectus** is due on Sep. 29.\n\n## Clark and Golder (2006) {ref=\"clark-golder-2006\"}\n\nUse {marginaleffects} to reproduce *the spirit of*[^2] Figure 1 on p. 701 of @clark2006 [[pdf](https://pos5747.github.io/notes/readings/Clark2006.pdf)], which shows the effect of the effective number of ethnic groups (ENEG) on the effective number of electoral parties (ENEP) as district magnitude varies.\n\n[^2]: By \"the spirit of,\" I mean that you should feel free to change the mostly arbitrary features of the plot, like (1) the comparison (the authors use the instantaneous marginal effect), (2) the scale of the *x*-axis (the authors use the natural log), (3) the values of the other covariates, (4) average case or observed values, etc.\n\n![](images/clipboard-1585045842.png){width=\"70%\" fig-align=\"center\"}\n\nThe R code below gets you started.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load data\ncg <- crdata::cg2006\n\n# fit model; \"Established Democracies 1946-2000\" model in Table 2 on p. 698\nf <- enep ~ eneg*log(average_magnitude) + eneg*upper_tier + en_pres*proximity\nfit <- lm(f, data = cg)\n```\n:::\n\n\n1. Use `predictions()` to plot the expected ENEP as district magnitude varies from 1 to 150, once with ENEG at its minimum and once with ENEG at its maximum. (Set `upper_tier = 0`.) Interpret.\n1. Use `comparisons()` to plot the effect of moving ENEG from its minimum to its maximum as district magnitude varies from 1 to 150. (Again, set `upper_tier = 0`.) How does this curve relate to the two curves in part 1?\n\n::: hint\nFor part 2, `variables = list(eneg = \"minmax\")` specifies the comparison and `newdata = datagrid(...)` builds the grid. See the [Grid](https://pos5747.github.io/notes/wk05/01-marginaleffects.html#grid) section of the notes.\n:::\n\n::: sol\n\n**Part 1**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# expected enep for a range of magnitudes, at the min and max of eneg\nev <- predictions(fit,\n                  newdata = datagrid(average_magnitude = 1:150,\n                                     eneg = range,\n                                     upper_tier = 0))\n\n# plot\nggplot(ev, aes(x = average_magnitude, y = estimate,\n               ymin = conf.low, ymax = conf.high,\n               group = eneg)) +\n  geom_ribbon(alpha = 0.3) +\n  geom_line()\n```\n\n::: {.cell-output-display}\n![](wk05-exercises-sol_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# expected values at magnitudes 1 and 150\nev |>\n  filter(average_magnitude %in% c(1, 150)) |>\n  select(average_magnitude, eneg, estimate, conf.low, conf.high)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Estimate 2.5 % 97.5 %\n     2.73  2.48   2.97\n     4.20  2.46   5.94\n     4.44  3.95   4.94\n    23.38 15.49  31.27\n```\n\n\n:::\n:::\n\n\n`datagrid()` accepts a function as well as values, so `eneg = range` gives us the minimum (about 1.0) and the maximum (about 14.2) of ENEG. Then `datagrid()` crosses those two values with the 150 magnitudes, so `ev` has 300 rows.\n\nNotice that the two curves start close together and fan out. With a single-member district (i.e., magnitude 1), the expected ENEP is about 2.7 at the minimum ENEG and about 4.2 at the maximum ENEG. At magnitude 150, the expected ENEP is about 4.4 at the minimum ENEG and about 23.4 at the maximum ENEG. Ethnic diversity has little relationship to the number of parties when district magnitude is small and a large relationship when district magnitude is large. This is Clark and Golder's argument.\n\n**Part 2**\n\nThe code below serves as a minimal example--I tried to keep it as simple as possible. There are many things you might choose to do differently or better.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load packages\nlibrary(marginaleffects)\n\n# compute first difference for a range of magnitudes\nfd <- comparisons(fit,\n                  variables = list(eneg = \"minmax\"),\n                  newdata = datagrid(average_magnitude = 1:150,\n                                     upper_tier = 0))\n\n# plot\nggplot(fd, aes(x = average_magnitude, y = estimate,\n               ymin = conf.low, ymax = conf.high)) +\n  geom_ribbon() +\n  geom_line()\n```\n\n::: {.cell-output-display}\n![](wk05-exercises-sol_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# first differences at magnitudes 1 and 150\nfd |>\n  filter(average_magnitude %in% c(1, 150)) |>\n  select(average_magnitude, estimate, conf.low, conf.high)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Estimate  2.5 % 97.5 %\n     1.48 -0.374   3.33\n    18.94 10.734  27.15\n```\n\n\n:::\n:::\n\n\nThe plot shows how the expected number of electoral parties (ENEP) changes when moving from the minimum to the maximum level of the effective number of ethnic groups (ENEG) as district magnitude varies from 1 to 150, fixing `upper_tier = 0` and holding other covariates at their means. For each value of district magnitude, the coefficient estimates are used to calculate this first difference and 95% confidence interval.\n\n*Details*\n\n   ```r\n   fd <- comparisons(fit,\n                     variables = list(eneg = \"minmax\"),\n                     newdata = datagrid(average_magnitude = 1:150,\n                                        upper_tier = 0))\n   ```\n\n   - `comparisons(fit, ...)` calculates contrasts (differences in predictions) for a fitted model.\n   - `variables = list(eneg = \"minmax\")` specifies a **discrete contrast**: predict the outcome when `eneg` is set to its observed minimum, then to its observed maximum, and take the difference.\n   - `newdata = datagrid(...)` defines the evaluation dataset:\n     - `average_magnitude = 1:150` generates 150 rows, one for each magnitude value between 1 and 150.\n     - `upper_tier = 0` fixes to \"no upper tier.\"\n     - All other covariates are set to their typical values (means in this case).\n   - For each row in this grid, the model is used to predict the outcome under `eneg = min` and `eneg = max`, and their difference.\n\n   ```r\n   ggplot(fd, aes(x = average_magnitude, y = estimate,\n                  ymin = conf.low, ymax = conf.high)) +\n     geom_ribbon() +\n     geom_line()\n   ```\n\n   The plot answers: *\"At each value of district magnitude between 1 and 150, in systems without an upper tier and other covariates at their mean, how much larger is the expected number of electoral parties in the most ethnically diverse setting compared to the least?\"* The solid line shows the estimated effect, and the ribbon shows the 95% confidence interval around that estimate.\n\nThis curve is the vertical distance between the two curves in part 1. At magnitude 1, the first difference is about 4.2 - 2.7 = 1.5. At magnitude 150, it's about 23.4 - 4.4 = 18.9. `comparisons()` computes the two expected values, takes their difference, and uses the delta method to get the SE of that difference.\n\n*Note: Because this is a linear model, the \"other covariates\" only matter if they are included in interactions with variables of interest.*\n\n:::\n\n## Radean and Beger (2025) {ref=\"beger-2025\"}\n\nRead the Introduction and Conclusion sections of @beger2025 [[pdf](https://pos5747.github.io/notes/readings/Radean2025.pdf)]. The authors make an important point. They argue that reporting only the average effect can be misleading; it can obscure the wide variation in effects across observed values. Instead, they advocate for a case-centered approach, where researchers compute and report effects for each observation.\n\nUse the data and model from @Russett2001 in the {crdata} package to illustrate the relative value of a single summary effect (e.g., the average difference across all observations) and the approach recommended by @beger2025.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load data\nro <- crdata::ro2001\n\n# glm version of their gee on pp. 314\nf <- dispute ~ allies + lcaprat2 + contiguity + dem.lo + logdstab + power\nfit <- glm(f, family = \"binomial\", data = ro)\n\n# example quantity of interest\navg_comparisons(fit,  variables = list(dem.lo = c(-10, 10)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Estimate Std. Error     z Pr(>|z|)     S   2.5 %  97.5 %\n  -0.0605    0.00272 -22.3   <0.001 362.3 -0.0658 -0.0552\n\nTerm: dem.lo\nType: response\nComparison: 10 - -10\n```\n\n\n:::\n:::\n\n\nIn Week 4, we used the invariance property and the delta method to compute the first difference as `dem.lo` moves from -10 to 10, fixing `lcaprat2` and `logdstab` at their medians and `allies`, `contiguity`, and `power` at their reference levels. The code below repeats that computation by hand.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load packages\nlibrary(numDeriv)\n\n# function to compute the first difference\nfd_fn <- function(beta, hi, lo) {\n  plogis(hi%*%beta) - plogis(lo%*%beta)\n}\n\n# make X_lo\nX_lo <- cbind(\n  \"constant\"   = 1, # intercept\n  \"allies\"     = 0,\n  \"lcaprat2\"   = median(ro$lcaprat2, na.rm = TRUE),\n  \"contiguity\" = 0,\n  \"dem.lo\"     = -10,\n  \"logdstab\"   = median(ro$logdstab, na.rm = TRUE),\n  \"power\"      = 0\n)\n\n# make X_hi by modifying the relevant value of X_lo\nX_hi <- X_lo\nX_hi[, \"dem.lo\"] <- 10\n\n# invariance property\nfd_hat <- fd_fn(coef(fit), X_hi, X_lo)\n\n# delta method\ngrad <- grad(\n  func = fd_fn,\n  x = coef(fit),\n  hi = X_hi,\n  lo = X_lo)\nse_fd_hat <- sqrt(grad %*% vcov(fit) %*% grad)\n\n# estimated fd and se\nc(fd_hat, se_fd_hat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.049019410  0.004235749\n```\n\n\n:::\n:::\n\n\n1. Compute the same first difference with `comparisons()` and `datagrid()`. Does your estimate match the by-hand estimate above? Does your SE match the by-hand SE?\n1. Use `comparisons()` to compute this first difference for every dyad-year in the data. Make one figure that shows the distribution of these first differences. In one paragraph, compare this distribution to the single summary from `avg_comparisons()`. What information does the single summary leave out?\n\n::: hint\nIn the by-hand code, a `0` for `allies`, `contiguity`, and `power` means the reference level (i.e., the first level, which `levels(ro$allies)` shows). `datagrid()` accepts a function as well as a value, so `lcaprat2 = median` sets `lcaprat2` to its median.\n:::\n\n::: hint\nFor part 2, leave out `newdata`. Without `newdata`, `comparisons()` returns one first difference for each row of the data.\n:::\n\n::: sol\n\n**Part 1**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncomparisons(fit,\n            variables = list(dem.lo = c(-10, 10)),\n            newdata = datagrid(lcaprat2 = median,\n                               logdstab = median,\n                               allies = \"Allies\",\n                               contiguity = \"Contiguous\",\n                               power = \"At Least One Great Power\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n lcaprat2 logdstab allies contiguity                    power Estimate\n     2.83     8.04 Allies Contiguous At Least One Great Power   -0.049\n Std. Error     z Pr(>|z|)     S   2.5 %  97.5 %\n    0.00424 -11.6   <0.001 100.5 -0.0573 -0.0407\n\nTerm: dem.lo\nType: response\nComparison: 10 - -10\n```\n\n\n:::\n:::\n\n\nThe estimates and the SEs match the by-hand computation: about $-0.049$ with an SE of about 0.004. {marginaleffects} uses the same invariance property and delta method that we used by hand in Week 4.\n\n**Part 2**\n\n*Answers will vary.* Here's one version.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# first difference for every dyad-year\nfd <- comparisons(fit, variables = list(dem.lo = c(-10, 10)))\n\n# average first difference\navg_fd <- avg_comparisons(fit, variables = list(dem.lo = c(-10, 10)))\navg_fd\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Estimate Std. Error     z Pr(>|z|)     S   2.5 %  97.5 %\n  -0.0605    0.00272 -22.3   <0.001 362.3 -0.0658 -0.0552\n\nTerm: dem.lo\nType: response\nComparison: 10 - -10\n```\n\n\n:::\n\n```{.r .cell-code}\n# summarize the distribution of first differences\nquantile(fd$estimate, c(0, 0.5, 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          0%          50%         100% \n-0.318673406 -0.040727341 -0.004673395 \n```\n\n\n:::\n\n```{.r .cell-code}\n# plot the distribution, w/ the average as a vertical line\nggplot(fd, aes(x = estimate)) +\n  facet_wrap(vars(contiguity), ncol = 1) +\n  geom_histogram(bins = 50) +\n  geom_vline(xintercept = avg_fd$estimate, linetype = \"dashed\")\n```\n\n::: {.cell-output-display}\n![](wk05-exercises-sol_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nThe average first difference is about $-0.06$. But the first differences for individual dyad-years range from about $-0.32$ to about $-0.005$. The single summary doesn't show that the effect of democracy depends heavily on the baseline risk of a dispute.\n\nI split the figure by contiguity because neighbors have a much higher baseline risk. For contiguous dyads, most of the first differences are larger than the average. For noncontiguous dyads, most are smaller.\n\n:::\n\n## Zero-inflated negative binomial {ref=\"zinb-by-hand\"}\n\nSuppose a zero-inflated negative binomial model gives an observation a probability of a structural zero $\\pi = 0.25$, a negative binomial mean $\\mu = 4$, and an overdispersion parameter $\\theta = 0.5$. For the negative binomial part, the probability of a zero is $f(0; \\mu, \\theta) = \\left(\\frac{\\theta}{\\theta + \\mu}\\right)^\\theta$.\n\n1. By hand, compute $\\Pr(y = 0)$ for this observation. How much of this probability comes from structural zeros? How much comes from the negative binomial part?\n1. By hand, compute $E(y)$ for this observation. Why isn't $E(y)$ equal to $\\mu$?\n1. Copy the code from the [zero-inflation chapter](https://pos5747.github.io/notes/wk05/03-zero-inflation.html) of the notes that fits `zinb2_fit` to Holland's Santiago data, and run it. `predict(zinb2_fit, type = \"zprob\")` returns $\\hat{\\pi}_i$ and `predict(zinb2_fit, type = \"conditional\")` returns $\\hat{\\mu}_i$. Confirm that `predictions(zinb2_fit)` returns $(1 - \\hat{\\pi}_i)\\hat{\\mu}_i$.\n\n::: hint\nThere are two ways to get a zero. The observation can be a structural zero (with probability $\\pi$). Or it can be a draw from the negative binomial (with probability $1 - \\pi$) that happens to equal zero. See the [pmf](https://pos5747.github.io/notes/wk05/03-zero-inflation.html#pmf) in the notes.\n:::\n\n::: sol\n\n**Part 1**\n\nFirst, compute the negative binomial part's probability of a zero.\n\n$$\nf(0; \\mu, \\theta) = \\left(\\frac{0.5}{0.5 + 4}\\right)^{0.5} = \\left(\\frac{1}{9}\\right)^{0.5} = \\frac{1}{3}.\n$$\n\nThen add the two ways to get a zero.\n\n$$\n\\Pr(y = 0) = \\pi + (1 - \\pi) f(0; \\mu, \\theta) = 0.25 + 0.75 \\times \\frac{1}{3} = 0.25 + 0.25 = 0.5.\n$$\n\nSo half of the probability (0.25) comes from structural zeros, and the other half (0.25) comes from the negative binomial part.\n\n**Part 2**\n\n$$\nE(y) = \\pi \\times 0 + (1 - \\pi) \\mu = 0.75 \\times 4 = 3.\n$$\n\n$E(y)$ doesn't equal $\\mu$ because $\\mu$ is the mean of the negative binomial part only. A quarter of the time, the observation is a structural zero, which lowers the mean from 4 to 3.\n\n**Part 3**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load packages\nlibrary(glmmTMB)\n\n# fit zinb2_fit from the notes\nsant <- crdata::holland2015 |>\n  filter(city == \"santiago\")\nf <- operations ~ lower + vendors + budget + population\nzi_f <-  ~ lower + vendors + budget + population\nzinb2_fit <- glmmTMB(\n  formula = f,\n  ziformula = zi_f,\n  family = nbinom2,\n  data = sant\n)\n\n# the two parts of the model\npi_hat <- predict(zinb2_fit, type = \"zprob\")\nmu_hat <- predict(zinb2_fit, type = \"conditional\")\n\n# compare (1 - pi) * mu to predictions()\nev <- predictions(zinb2_fit)\ntibble(by_hand = (1 - pi_hat)*mu_hat,\n       marginaleffects = ev$estimate) |>\n  head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n  by_hand marginaleffects\n    <dbl>           <dbl>\n1   0.379           0.379\n2   0.306           0.306\n3   0.222           0.222\n4   1.64            1.64 \n5   1.89            1.89 \n6   0.723           0.723\n```\n\n\n:::\n:::\n\n\nThe two columns are the same. {marginaleffects} works with $E(y_i) = (1 - \\hat{\\pi}_i)\\hat{\\mu}_i$, which combines both parts of the model.\n\n:::\n\n## Hultman, Kathman, and Shannon (2013) {ref=\"hultman-2013\"}\n\n@Hultman2013 [[pdf](https://pos5747.github.io/notes/readings/Hultman2013.pdf)] use a negative binomial regression model. Skim through their paper to understand the application and the variables. You can find out more about their data and useful details with `?crdata::hks2013`.\n\n1. Fit two zero-inflated negative binomial models: one with constant zero inflation and one with zero inflation that depends on covariates $Z$. The $Z$ variables can be the same as the $X$ or different. How many parameters (i.e., $k$) does each of the three models (the negative binomial model below and your two zero-inflated models) have? Check your counts against the `df` column of `BIC()`.\n1. Use the BIC to compare the three models and convert the BICs to posterior model probabilities. How would @raftery1995 describe the evidence? Does a zero-inflated negative binomial model better fit their data?\n1. Use `simulate()` to simulate five fake data sets from the negative binomial model and five from your preferred zero-inflated model. Compare the fake data sets to the observed data. What do you notice?\n1. Compute a substantively meaningful effect of UN troops on the number of civilians killed. How does the estimate for this quantity of interest from their negative binomial regression compare to the alternative models you consider?\n\nFor part 3, use `simulate()` rather than building the fake data sets by hand with `rnbinom()` (like we did for Holland's data in Week 4). `simulate()` works for both `MASS::glm.nb()` and `glmmTMB()` fits, and it draws each fake observation from that observation's own fitted distribution. To do this by hand for the zero-inflated model, you'd need a $\\hat{\\pi}_i$ and a $\\hat{\\mu}_i$ for every observation.\n\n::: callout-warning\nThe `MASS::glm.nb()` model has a hard time converging for this data. See the `control` options that I use below for the negative binomial model.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load data\nhks <- crdata::hks2013\n\n# estimate models\nf <- osvAll ~ troopLag + policeLag + militaryobserversLag +\n  brv_AllLag + osvAllLagDum + incomp + epduration +\n  lntpop\n\n# replicates model 1 in table 1 on p. 884 of HKS\nfit <- MASS::glm.nb(f, data = hks,\n                    init.theta = 5,\n                    control = glm.control(epsilon = 1e-12,\n                                          maxit = 2500,\n                                          trace = FALSE))\n```\n:::\n\n\n::: hint\nIn `glmmTMB()`, `ziformula = ~ 1` gives constant zero inflation and `ziformula = ~ troopLag + ...` lets it depend on covariates. The [Information criteria](https://pos5747.github.io/notes/wk05/02-ic.html#information-criteria) section of the notes converts BICs to posterior probabilities. For part 4, compute the same quantity of interest from each fit with `avg_comparisons()`. `troopLag` is measured in thousands of troops, and most observations have none.\n:::\n\n::: hint\n`simulate(fit, nsim = 5)` returns a data frame with one column per fake data set. These counts are so skewed that a histogram isn't very useful. Instead, compare a few summaries (e.g., the share of zeros, the 90th percentile, and the maximum) of the observed data and each fake data set.\n:::\n\n::: sol\n\n**Part 1**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load packages\nlibrary(glmmTMB)\n\n# zinb w/o covariates\nfit_zi0 <- glmmTMB(f, ziformula = ~ 1, data = hks, family = nbinom2)\n\n# zinb w/ same covariates as nb portion\nfit_zi1 <- glmmTMB(f, ziformula = update(f, NULL ~ .), data = hks, family = nbinom2)\n```\n:::\n\n\nThe formula has eight covariates, so the negative binomial part has nine coefficients (i.e., eight slopes and an intercept).\n\n- The negative binomial model has the nine coefficients plus $\\theta$, so $k = 10$.\n- The model with constant zero inflation adds one intercept for the zero inflation, so $k = 11$.\n- The model with covariates in the zero inflation adds nine coefficients for the zero inflation, so $k = 9 + 9 + 1 = 19$.\n\nThe `df` column below confirms these counts.\n\n**Part 2**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# compare\nBIC(fit, fit_zi0, fit_zi1) |>\n  mutate(diff_min = BIC - min(BIC),\n         post_prob = exp(-0.5*diff_min)/sum(exp(-0.5*diff_min)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        df      BIC diff_min     post_prob\nfit     10 12602.59 1021.020 1.941904e-222\nfit_zi0 11 12610.82 1029.249 3.172807e-224\nfit_zi1 19 11581.57    0.000  1.000000e+00\n```\n\n\n:::\n:::\n\n\nThe BIC *strongly* prefers the zero-inflated model with covariates modeling the zero inflation. The difference is about 1,000, far above the threshold of 10 that @raftery1995 describes as \"very strong\" evidence. The posterior probability of the zero-inflated model with covariates is essentially 1.\n\nNotice that the model with constant zero inflation is *worse* than the negative binomial model by about 8. The estimated probability of a structural zero is essentially zero, so the model collapses to the negative binomial (just like the [Santiago example](https://pos5747.github.io/notes/wk05/03-zero-inflation.html#constant-pi) in the notes). It fits the data exactly as well as the negative binomial, but it has one more parameter. The BIC adds $\\log(N) = \\log(3{,}746) \\approx 8.2$ for each parameter, so the constant zero inflation makes the BIC about 8 points worse.\n\n**Part 3**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# simulate five fake data sets from each model\nset.seed(1234)\nnb_sims <- simulate(fit, nsim = 5)\nzinb_sims <- simulate(fit_zi1, nsim = 5)\n\n# a function to summarize a data set\nsummarize_counts <- function(y) {\n  c(pct_zero = round(100*mean(y == 0)),\n    median = median(y),\n    p90 = unname(quantile(y, 0.9)),\n    max = max(y))\n}\n\n# observed data\nsummarize_counts(hks$osvAll)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\npct_zero   median      p90      max \n      76        0       28   145844 \n```\n\n\n:::\n\n```{.r .cell-code}\n# fake data from the nb model\nt(sapply(nb_sims, summarize_counts))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      pct_zero median p90        max\nsim_1       76      0  16    7339049\nsim_2       76      0  15 5200027745\nsim_3       75      0  14   15037959\nsim_4       76      0  14    3489999\nsim_5       75      0  16    6536423\n```\n\n\n:::\n\n```{.r .cell-code}\n# fake data from the zinb model w/ covariates\nt(sapply(zinb_sims, summarize_counts))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      pct_zero median  p90     max\nsim_1       78      0 28.0   46791\nsim_2       78      0 29.5   65833\nsim_3       78      0 31.5   88596\nsim_4       77      0 38.0  696547\nsim_5       78      0 41.0 8500262\n```\n\n\n:::\n:::\n\n\nIn the observed data, about three-quarters of the observations are zeros, the 90th percentile is 28, and the maximum is about 146,000.\n\nBoth models get the share of zeros and the median about right. But the negative binomial model produces a 90th percentile that's too small (about 15) *and* maximums that are absurdly large (in the millions, and one above five billion!). The zero-inflated model does better. Its 90th percentiles are closer to the observed 28, and most of its maximums are in the tens of thousands. But it's not perfect. It occasionally simulates an enormous count as well.\n\n**Part 4**\n\nWe can use `avg_comparisons()` to compute the average change in expected civilian casualties as the number of UN troops (in 1000s) moves from 0 to its mean ($\\approx 0.7$).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbind_rows(\n  \"NB\" = avg_comparisons(fit, variables = list(troopLag = c(0, .7))),\n  \"constant ZINB\" = avg_comparisons(fit_zi0, variables = list(troopLag = c(0, .7))),\n  \"modeled ZINB\" = avg_comparisons(fit_zi1, variables = list(troopLag = c(0, .7))),\n  .id = \"model\") |>\n  select(model, estimate, std.error) |>\n  tinytable::tt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_5xwtqy8304ibvcyavnle = TinyTable.createTableFunctions(\"tinytable_5xwtqy8304ibvcyavnle\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '3', j: 1 }, { i: '3', j: 2 }, { i: '3', j: 3 } ], css_id: 'tinytable_css_s59kgew4fa2vq2uesi23',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 } ], css_id: 'tinytable_css_deupeiqdv0nxt54v33ta',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_5xwtqy8304ibvcyavnle.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_5xwtqy8304ibvcyavnle td.tinytable_css_s59kgew4fa2vq2uesi23, #tinytable_5xwtqy8304ibvcyavnle th.tinytable_css_s59kgew4fa2vq2uesi23 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_5xwtqy8304ibvcyavnle td.tinytable_css_deupeiqdv0nxt54v33ta, #tinytable_5xwtqy8304ibvcyavnle th.tinytable_css_deupeiqdv0nxt54v33ta {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_5xwtqy8304ibvcyavnle\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">model</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">estimate</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">std.error</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">NB</td>\n                  <td data-row=\"1\" data-col=\"2\">-2159660.706</td>\n                  <td data-row=\"1\" data-col=\"3\">3028339.87</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">constant ZINB</td>\n                  <td data-row=\"2\" data-col=\"2\">-2159686.294</td>\n                  <td data-row=\"2\" data-col=\"3\">3172687.72</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">modeled ZINB</td>\n                  <td data-row=\"3\" data-col=\"2\">-1064.872</td>\n                  <td data-row=\"3\" data-col=\"3\">1302.41</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\nFor the negative binomial and zero-inflated negative binomial models with constant zero-inflation, we obtain absurdly large estimates and SEs. For the zero-inflated model with covariates, we get a reasonable estimate that increasing the troops from zero to their average level in the data decreases civilian casualties by about 1,000, give or take 1,300 or so.\n\nThese estimates make it clear that *something weird* is happening with these estimates. It turns out that there are some *extremely* large counts in these data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(hks$osvAll)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. \n     0.00      0.00      0.00     69.54      0.00 145844.00 \n```\n\n\n:::\n:::\n\n\nThese extremely large counts push the overdispersion parameter *very close to zero*. When the overdispersion parameter is very close to zero, the negative binomial model can fit a few observations with *enormous* means. The largest fitted mean is about 2.2 billion, even though the largest observed count is about 146,000. These few observations account for most of the average first difference and its SE.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fitted(fit))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. \n0.000e+00 2.000e+00 5.000e+00 5.908e+05 2.100e+01 2.199e+09 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nMASS::glm.nb(formula = f, data = hks, control = glm.control(epsilon = 1e-12, \n    maxit = 2500, trace = FALSE), init.theta = 0.05919426018, \n    link = log)\n\nCoefficients:\n                       Estimate Std. Error z value Pr(>|z|)    \n(Intercept)          -9.2367536  0.8750837 -10.555   <2e-16 ***\ntroopLag             -0.5304466  0.0623706  -8.505   <2e-16 ***\npoliceLag            -9.9025813  1.0421355  -9.502   <2e-16 ***\nmilitaryobserversLag 21.7618688  1.3017670  16.717   <2e-16 ***\nbrv_AllLag            0.0007062  0.0005804   1.217    0.224    \nosvAllLagDum          2.1773614  0.1762377  12.355   <2e-16 ***\nincomp                2.3793901  0.1871308  12.715   <2e-16 ***\nepduration           -0.0005591  0.0013581  -0.412    0.681    \nlntpop                0.7031066  0.0726654   9.676   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for Negative Binomial(0.0592) family taken to be 1)\n\n    Null deviance: 2862.1  on 3745  degrees of freedom\nResidual deviance: 1834.7  on 3737  degrees of freedom\nAIC: 12540\n\nNumber of Fisher Scoring iterations: 1\n\n              Theta:  0.05919 \n          Std. Err.:  0.00228 \n\n 2 x log-likelihood:  -12520.30800 \n```\n\n\n:::\n:::\n\n\nModeling the zero-inflation allows the model to adequately capture the overdispersion while keeping $\\theta$ to a reasonable value (i.e., about 0.19 rather than 0.06).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fit_zi1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: nbinom2  ( log )\nFormula:          \nosvAll ~ troopLag + policeLag + militaryobserversLag + brv_AllLag +  \n    osvAllLagDum + incomp + epduration + lntpop\nZero inflation:          \n~troopLag + policeLag + militaryobserversLag + brv_AllLag + osvAllLagDum + \n    incomp + epduration + lntpop\nData: hks\n\n      AIC       BIC    logLik -2*log(L)  df.resid \n  11463.2   11581.6   -5712.6   11425.2      3727 \n\n\nDispersion parameter for nbinom2 family (): 0.192 \n\nConditional model:\n                       Estimate Std. Error z value Pr(>|z|)    \n(Intercept)          -4.2935574  0.9193441  -4.670 3.01e-06 ***\ntroopLag             -0.2973410  0.0953140  -3.120  0.00181 ** \npoliceLag            -7.5250182  1.2462203  -6.038 1.56e-09 ***\nmilitaryobserversLag 13.0225828  1.1210523  11.616  < 2e-16 ***\nbrv_AllLag            0.0003716  0.0002883   1.289  0.19749    \nosvAllLagDum          0.0637672  0.1839842   0.347  0.72890    \nincomp                1.9312583  0.2052217   9.411  < 2e-16 ***\nepduration           -0.0096235  0.0012134  -7.931 2.17e-15 ***\nlntpop                0.5675410  0.0754177   7.525 5.26e-14 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nZero-inflation model:\n                       Estimate Std. Error z value Pr(>|z|)    \n(Intercept)           1.092e+01  1.233e+00   8.855  < 2e-16 ***\ntroopLag              1.460e-01  8.017e-02   1.821   0.0685 .  \npoliceLag             3.739e+00  2.065e+00   1.811   0.0702 .  \nmilitaryobserversLag -4.416e+00  1.910e+00  -2.312   0.0208 *  \nbrv_AllLag           -2.320e-02  1.290e-02  -1.798   0.0722 .  \nosvAllLagDum         -2.136e+01  1.382e+03  -0.015   0.9877    \nincomp               -1.648e+00  2.520e-01  -6.541 6.12e-11 ***\nepduration           -8.083e-03  1.533e-03  -5.275 1.33e-07 ***\nlntpop               -5.962e-01  9.650e-02  -6.178 6.50e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n:::\n\n## de Kadt and Grzymala-Busse (2025) {ref=\"dekadt-2025\"}\n\nRead pp. 16-18 (in Section 3.1) of @dekadt2025 [[pdf](https://pos5747.github.io/notes/readings/deKadt2025.pdf)]. There (p. 17), they write:\n\n> If the researcher firmly believes they are not engaged in counterfactual reasoning---they purely want to 'describe the data'---then the use of multivariate regression is itself a peculiar choice.\n\nWhat do you make of their argument about multiple regression and control variables? Are control variables *always* about causal inference? Are control variables ever useful for description? Explain with one example (perhaps from your prospectus). Write two or three paragraphs (about 300 words).\n\n::: sol\n*No solution intended. Answers will vary.*\n:::\n\n## {marginaleffects} {ref=\"marginaleffects-cheatsheet\"}\n\nWrite your own one-page cheatsheet for the {marginaleffects} package. Organize it around the [three choices](https://pos5747.github.io/notes/wk05/01-marginaleffects.html#framework) in the notes (i.e., quantity, grid, and aggregation). *At a minimum*, your cheatsheet should describe `predictions()`, `comparisons()`, their `avg_*()` variants, and `datagrid()`, along with the arguments `type`, `variables`, `comparison`, `newdata`, and `by`.\n\nUse @me [[pdf](https://pos5747.github.io/notes/readings/Arel-Bundock2024.pdf)] as a reference.[^1] You don't need to read it cover to cover. Look up what you need for your cheatsheet.\n\n[^1]: There is also a book at [marginaleffects.com/chapters/who.html](https://marginaleffects.com/chapters/who.html) with lots of examples and case studies.\n\n*For inspiration: What are the important functions? What are the important arguments? What are good default practices---and how do these deviate from {marginaleffects} defaults? You can stick closely to the perspective in the [notes](https://pos5747.github.io/notes/wk05/01-marginaleffects.html) or deviate far from that perspective.*\n\n::: sol\n*No solution intended. Answers will vary.*\n:::\n\n",
    "supporting": [
      "wk05-exercises-sol_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}