{
  "hash": "a085794980af8179358d24a59c488ee4",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Hierarchical Models\"\nformat:\n  revealjs:\n    css: styles.css\n    transition: fade\n    slide-number: true\n    width: 1600\n    height: 900\n    mathjax: true  \nexecute:\n  echo: true\nfig-align: center\nfig-width: 8\nfig-asp: 0.5\n---\n\n\n\n\n# Opening Comments\n\n- Exam\n- Workshop\n- Paper\n\n\n\n::: {.cell}\n\n:::\n\n\n\n---\n\nHere are the packages we're using:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# generally useful packages\nlibrary(tidyverse)\nlibrary(marginaleffects)\nlibrary(modelsummary)\n\n# for fitting hierarchical models\nlibrary(lme4)\nlibrary(brms)  # see also rstanarm::stan_lmer()\n\n# for post-processing simulations\nlibrary(tidybayes)\n```\n:::\n\n\n\n\n---\n\nThis week, I introduce the idea of a hierarchical model. \n\n::: {.fragment .custom .blur}\nThese fall squarely within our probability modeling framework---but with an exciting new twist.\n:::\n\n::: {.fragment .custom .blur}\nBefore: $x_i \\sim f(x_i; \\theta)$\n:::\n\n\n::: {.fragment .custom .blur}\nNow: $x_i \\sim f(x_i; \\theta_{j[i]})$, where $\\theta_j \\sim f(\\theta_j; \\phi)$\n:::\n\n# Contact in Finland\n\nIn my dissertation, I was interested in how survey self-reports of **being contacted** by a political party varies across electoral districts. \n\n\nYou can see [here](http://www.carlislerainey.com/papers/stratmob.pdf) for the details. \n\n---\n\nFor now, let's just estimate the proportion of people in each district that are contacted by a party.\n\n::: {.fragment .custom .blur}\nLet's start with Finland.\n:::\n\n::: {.fragment .custom .blur}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load data\nfinland <- crdata::finland |>\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,086\nColumns: 2\n$ district_id <chr> \"District 313\", \"District 313\", \"District 310\", \"District 304\", \"Dis…\n$ contacted   <fct> Not Contacted, Contacted, Not Contacted, Contacted, Not Contacted, N…\n```\n\n\n:::\n:::\n\n\n:::\n\n::: {.fragment .custom .blur}\nIt will be convenient in later steps to have `contacted` be an indicator and `district_id` be a nice factor, so let's do that now.\n\n1. Remove \"District\" from the strings.\n1. `reorder()` the levels by the average of `contacted`. (Important sneaky trick).\n:::\n\n---\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load data\nfinland <- crdata::finland |>\n  # make contacted an indicator\n  mutate(contacted = as.numeric(contacted == \"Contacted\")) |>\n  # mutate district_id to factor ordered by contact rate\n  mutate(district_id = str_remove(district_id, \"District \"),\n         district_id = reorder(district_id, contacted)) |>\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,086\nColumns: 2\n$ district_id <fct> 313, 313, 310, 304, 304, 304, 304, 304, 304, 304, 304, 304, 304, 304…\n$ contacted   <dbl> 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,…\n```\n\n\n:::\n:::\n\n\n\n---\n\nA scatterplot is a safe and potentially informative way to start.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngg1 <- ggplot(finland, aes(x = district_id, y = contacted)) + \n  geom_jitter(shape = 21, alpha = 0.5, size = 1)\nprint(gg1)\n```\n\n::: {.cell-output-display}\n![](wk09-slides_files/figure-revealjs/unnamed-chunk-5-1.png){width=768}\n:::\n:::\n\n\n\n---\n\nNow let's estimate the probability of being contacted by a political party in each district.\n\n::: {.fragment .custom .blur}\nStart by writing down a probability model for being contacted. This is a binary outcome, so if we're going to assume (conditional) independence, it must be Bernoulli.\n:::\n\n::: {.fragment .custom .blur}\n$$\n\\text{Contacted}_i \\sim \\text{Bernoulli}(\\pi_j),\n$$\n\nwhere $i$ indexes the respondent and $j$ indexes the electoral district.\n:::\n\n::: {.fragment .custom .blur}\nRemember that the ML estimate of $\\pi$ is just the sample mean (or sample proportion). \n:::\n\n---\n\nWe can do this easily for each district with `group_by()` and `summarize()`. \n\n::: {.fragment .custom .blur}\nLet's also add an estimate of the standard error using $\\widehat{\\text{SE}}(\\hat{\\pi}_j) = \\frac{\\sqrt{\\hat{\\pi}_j(1 - \\hat{\\pi}_j)}}{\\sqrt{n}}$.\n:::\n\n::: {.fragment .custom .blur}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestimates <- finland %>%\n  group_by(district_id) %>%\n  summarize(pi_hat = mean(contacted),\n            n = n(),\n            se_hat = sqrt(pi_hat*(1 - pi_hat))/sqrt(n)) %>%\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 14\nColumns: 4\n$ district_id <fct> 312, 315, 316, 305, 310, 306, 311, 304, 317, 307, 314, 313, 308, 309\n$ pi_hat      <dbl> 0.0862, 0.0909, 0.1250, 0.1500, 0.1620, 0.1707, 0.1818, 0.2288, 0.22…\n$ n           <int> 58, 44, 40, 40, 179, 41, 88, 153, 61, 105, 103, 65, 86, 23\n$ se_hat      <dbl> 0.0369, 0.0433, 0.0523, 0.0565, 0.0275, 0.0588, 0.0411, 0.0340, 0.05…\n```\n\n\n:::\n:::\n\n\n:::\n\n---\n\nNow let's add these estimates to the scatterplot.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngg2 <- gg1 + \n  geom_errorbar(data = estimates, aes(ymin = pi_hat - 1.64*se_hat,\n                                      ymax = pi_hat + 1.64*se_hat, \n                                      y = NULL),\n                width = .2, color = \"#1b9e77\") + \n  geom_point(data = estimates, aes(y = pi_hat), \n             color = \"#1b9e77\", size = 2)\nprint(gg2)\n```\n\n::: {.cell-output-display}\n![](wk09-slides_files/figure-revealjs/unnamed-chunk-7-1.png){width=768}\n:::\n:::\n\n\n\n\n---\n\nYou can see that the confidence intervals (and sample size) varies by district, so let's add that information to the plot.\n\n::: {.fragment .custom .blur}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngg3 <- gg2 + \n  geom_label(data = estimates, aes(y = pi_hat + 1.64*se_hat,\n                                   label = n),\n                color = \"#1b9e77\",\n             vjust = -0.2)\nprint(gg3)\n```\n\n::: {.cell-output-display}\n![](wk09-slides_files/figure-revealjs/unnamed-chunk-8-1.png){width=768}\n:::\n:::\n\n\n:::\n\n\n---\n\nGreat! Now we're done. We've got ML estimates of the contact rate for all districts. \n\n::: {.fragment .custom .blur}\nBut wait... can we do better?\n:::\n\n---\n\nLet's look at district 309 on the far right. We our estimate of the contact rate in this district is the highest.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](wk09-slides_files/figure-revealjs/unnamed-chunk-9-1.png){width=768}\n:::\n:::\n\n\n\n::: {.fragment .custom .blur}\nOur estimator $\\hat\\pi$ is unbiased, but **if you had to say**, would you say that the turnout rate in district 309 was higher or lower than $\\hat{\\pi}_{309} = 0.40$?\n:::\n\n::: {.fragment .custom .blur}\nIf your intuition matches mine, you will say *lower*. Why? This \"why?\" is an important question.\n:::\n\n---\n\nIf you think that $\\hat{\\pi}$ is a good estimator, but you suddenly want to adjust this particular estimate, you must have additional information coming from somewhere. Where?\n\n::: {.fragment .custom .blur}\nThe answer: the *other districts*. We admit that the contact rate will be different across districts, but it also seems reasonable to assume they will be similar (that's \"different, but similar\"). Given that 309 has a small sample and looks relatively unlike the other estimates, we want to pull it down *slightly* toward the other estimates.\n:::\n\n::: {.fragment .custom .blur}\nThis is exactly the intuition of hierarchical models. Let's write down this \"different, but similar\" intuition. \n:::\n\n::: {.fragment .custom .blur}\nTo do this, it will be convenient to have our $\\pi_j$s on the logit scale.\n:::\n\n---\n\nStart with the likelihood.\n\n$$\n\\text{Contacted}_i \\sim \\text{Bernoulli}(\\pi_j)\n$$\n\n::: {.fragment .custom .blur}\nNow translate the $\\pi$s to the logit scale.\n\n$$\n\\pi_j = \\text{logit}^{-1}(\\alpha_j)\n$$\n:::\n\n::: {.fragment .custom .blur}\nEach of these $\\alpha_j$s is like a constant term in a logit model with no covariates. (We could add covariates, but that makes the example less clear.)\n:::\n\n---\n\nNow for the hierarchical part: we want to capture the notion that these $\\alpha_j$s are different *but similar*. \n\n::: {.fragment .custom .blur}\nWe can do that by modeling them as draws from normal distribution.\n\n$$\n\\alpha_j \\sim N(\\mu, \\sigma^2)\n$$\n:::\n\n::: {.fragment .custom .blur}\n- We can estimate $\\mu$ (the \"typical\" $\\alpha$) and $\\sigma$ (the degree of similarity) from the data. This is \"hierarchical piece.\"\n:::\n\n::: {.fragment .custom .blur}\n- We sometimes refer to batches of parameters modeled as draws from a distribution as \"random effects.\"\n:::\n\n---\n\nTo estimate the hierarchical model: \n\n- use ML via the `lme4::lmer()`/`lme4::glmer()` function. Fast, fragile, approximate.\n- use MCMC via the `brm()` function. Slow(er), robust, exact.^[Also `rstanarm::stan_lmer()`.]\n\n::: {.fragment .custom .blur}\nWe're going to start with `lmer()` because I don't want to juggle posterior simulation and hierarchical models simultaneously, but you should always use `brm()` always unless you simply need a quick fit.\n:::\n\n---\n\nWe can fit the model with `glmer()`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|2\"}\nlibrary(lme4)\nf <- contacted ~ (1 | district_id)\nfit <- glmer(f, data = finland, family = binomial)\n```\n:::\n\n\n\n::: {.fragment .custom .blur}\n\nAnd we can summarize the results.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\narm::display(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nglmer(formula = contacted ~ (1 | district_id), data = finland, \n    family = binomial)\ncoef.est  coef.se \n   -1.37     0.12 \n\nError terms:\n Groups      Name        Std.Dev.\n district_id (Intercept) 0.31    \n Residual                1.00    \n---\nnumber of obs: 1086, groups: district_id, 14\nAIC = 1108.5, DIC = 1070\ndeviance = 1087.0 \n```\n\n\n:::\n:::\n\n\n\nFrom the output above, we estimate $\\mu$ as -1.37 and $\\sigma$ as 0.31. That is, the $\\alpha_j$s are about -1.37 give-or-take 0.31 or so.\n:::\n\n---\n\nBut here's the useful part: we can take this $\\hat{\\mu}$ and $\\hat{\\sigma}$ and use them as a Bayesian prior for the individual $\\alpha_j$s. \n\n::: {.fragment .custom .blur}\nEach $\\alpha_j$ has a likelihood (using the data from that district) and a prior (using $\\hat{\\mu}$ and $\\hat{\\sigma}$).\n:::\n\n::: {.fragment .custom .blur}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nre <- ranef(fit)$district_id[, \"(Intercept)\"] # this is centered at zero (i.e., alpha - mu); random part\nfe <- fixef(fit)[\"(Intercept)\"]  # mu; fixed part\n\nalpha_hat <- fe + re  # district-level linear predictors\npi_hat <- plogis(fe + re)  # district-level probabilities\n```\n:::\n\n\n:::\n\n---\n\nIn this case, it's easy to use `predict()` to get this same estimates. (The `predict()` approach is a little safer because it's easier to keep the `pi_hat` and the `district_id` label together.)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhier_estimates <- tibble(district_id = unique(finland$district_id)) %>%\n  mutate(pi_hat = predict(fit, newdata = ., type = \"response\")) %>%\n  arrange(district_id) %>%\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 14\nColumns: 2\n$ district_id <fct> 312, 315, 316, 305, 310, 306, 311, 304, 317, 307, 314, 313, 308, 309\n$ pi_hat      <dbl> 0.151, 0.160, 0.174, 0.183, 0.173, 0.190, 0.191, 0.221, 0.216, 0.225…\n```\n\n\n:::\n:::\n\n\n\n---\n\nWe can also do this with \\{marginaleffects\\}.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredictions(fit,\n            newdata = datagrid(district_id = unique)) |>\n  select(district_id, estimate) |>\n  arrange(district_id) |>  # comparisons() arranges predictions differently\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 14\nColumns: 2\n$ district_id <fct> 312, 315, 316, 305, 310, 306, 311, 304, 317, 307, 314, 313, 308, 309\n$ estimate    <dbl> 0.151, 0.160, 0.174, 0.183, 0.173, 0.190, 0.191, 0.221, 0.216, 0.225…\n```\n\n\n:::\n:::\n\n\n\n---\n\nWe can add this to our plot to see how the estimates changed. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngg4 <- gg3 + \n  geom_point(data = hier_estimates,\n             aes(y = pi_hat), \n             color = \"#d95f02\",\n             shape = 10, size = 3)\nprint(gg4)\n```\n\n::: {.cell-output-display}\n![](wk09-slides_files/figure-revealjs/unnamed-chunk-15-1.png){width=768}\n:::\n:::\n\n\n\n::: {.aside}\n- Notice that our new estimate for 309 is now at the very bottom of our initial confidence interval.\n- Notice the differences between the original ML estimates and CIs and the new estimates from the hierarchical model.\n:::\n\n---\n\nWe can compare the initial ML estimates to the hierarchical model estimates.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncomb <- bind_rows(list(\"initial ML\" = estimates,\n                       \"hierarchical\" = hier_estimates), \n                  .id = \"type\") %>%\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 28\nColumns: 5\n$ type        <chr> \"initial ML\", \"initial ML\", \"initial ML\", \"initial ML\", \"initial ML\"…\n$ district_id <fct> 312, 315, 316, 305, 310, 306, 311, 304, 317, 307, 314, 313, 308, 309…\n$ pi_hat      <dbl> 0.0862, 0.0909, 0.1250, 0.1500, 0.1620, 0.1707, 0.1818, 0.2288, 0.22…\n$ n           <int> 58, 44, 40, 40, 179, 41, 88, 153, 61, 105, 103, 65, 86, 23, NA, NA, …\n$ se_hat      <dbl> 0.0369, 0.0433, 0.0523, 0.0565, 0.0275, 0.0588, 0.0411, 0.0340, 0.05…\n```\n\n\n:::\n:::\n\n\n\n---\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngg_comb <- ggplot(comb, aes(x = pi_hat, y = type)) + \n  geom_point(alpha = 0.5) + \n  geom_line(aes(group = district_id), alpha = 0.5)\nprint(gg_comb)\n```\n\n::: {.cell-output-display}\n![](wk09-slides_files/figure-revealjs/unnamed-chunk-17-1.png){width=768}\n:::\n:::\n\n\n\n---\n\nIt's helpful to think of these approaches in terms of the amount of information they borrow across groups.\n\n::: {.fragment .fade-up}\n1. **No Pooling.** Assume the groups are different, and that nothing can be learned from the other groups. Estimate each group separately. \n:::\n::: {.fragment .fade-up}\n2. **Complete Pooling**. Assume the groups are identical. Collapse all the groups together to estimate the single, common estimate.\n:::\n::: {.fragment .fade-up}\n3. **Partial Pooling**. A compromise between the two extremes above. Assume the groups are different, *but similar*. Estimate the amount of similarity using the data, and pool the estimates toward a common estimate accordingly.\n:::\n\n---\n\nWe did not implement complete pooling above, but we can do it here to compare the three approaches. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# use the overall rate for each district\ncommon_estimate <- tibble(district_id = unique(finland$district_id)) %>%\n  mutate(pi_hat = mean(finland$contacted)) %>%\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 14\nColumns: 2\n$ district_id <fct> 313, 310, 304, 309, 312, 311, 307, 317, 314, 308, 305, 316, 306, 315\n$ pi_hat      <dbl> 0.207, 0.207, 0.207, 0.207, 0.207, 0.207, 0.207, 0.207, 0.207, 0.207…\n```\n\n\n:::\n:::\n\n\n\n---\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# combine the three types\ncomb <- bind_rows(list(\"No Pooling\" = estimates,\n                       \"Partial Pooling\" = hier_estimates,\n                       \"Complete Pooling\" = common_estimate), \n                  .id = \"type\") %>%\n  mutate(type = reorder(type, pi_hat, var)) %>%\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 42\nColumns: 5\n$ type        <fct> No Pooling, No Pooling, No Pooling, No Pooling, No Pooling, No Pooli…\n$ district_id <fct> 312, 315, 316, 305, 310, 306, 311, 304, 317, 307, 314, 313, 308, 309…\n$ pi_hat      <dbl> 0.0862, 0.0909, 0.1250, 0.1500, 0.1620, 0.1707, 0.1818, 0.2288, 0.22…\n$ n           <int> 58, 44, 40, 40, 179, 41, 88, 153, 61, 105, 103, 65, 86, 23, NA, NA, …\n$ se_hat      <dbl> 0.0369, 0.0433, 0.0523, 0.0565, 0.0275, 0.0588, 0.0411, 0.0340, 0.05…\n```\n\n\n:::\n:::\n\n\n\n---\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngg_comb2 <- ggplot(comb, aes(x = pi_hat, y = type)) + \n  geom_point(alpha = 0.5) + \n  geom_line(aes(group = district_id), alpha = 0.5)\nprint(gg_comb2)  \n```\n\n::: {.cell-output-display}\n![](wk09-slides_files/figure-revealjs/unnamed-chunk-20-1.png){width=768}\n:::\n:::\n\n\n\n## Key things\n\n::: {.fragment .custom .blur}\nFirst, the 309 problem.\n:::\n\n::: {.fragment .custom .blur}\nSecond, $\\mu_i = \\alpha_{j[i]} + \\beta x_i$, where $\\alpha_j \\sim N(0, \\sigma^2_\\alpha)$.\n:::\n\n::: {.fragment .custom .blur}\nThird, the figure below.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](wk09-slides_files/figure-revealjs/unnamed-chunk-21-1.png){width=768}\n:::\n:::\n\n\n:::\n\n\n# Contact in the UK\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nuk <- crdata::uk |>\n  # make contacted an indicator\n  mutate(contacted = as.numeric(contacted == \"Contacted\")) |>\n  # mutate district_id to factor ordered by contact rate\n  mutate(district_id = str_remove(district_id, \"District \"), \n         district_id = reorder(district_id, contacted)) |>\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 756\nColumns: 3\n$ district_id              <fct> 492, 492, 492, 492, 492, 374, 350, 350, 350, 463, 463, …\n$ contacted                <dbl> 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1…\n$ district_competitiveness <dbl> 0.484, 0.484, 0.484, 0.484, 0.484, 0.510, 0.540, 0.540,…\n```\n\n\n:::\n:::\n\n\n\n---\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngg1_uk <- ggplot(uk, aes(x = district_id, y = contacted)) + \n  geom_jitter(shape = 21, alpha = 0.5, size = 1)\nprint(gg1_uk)\n```\n\n::: {.cell-output-display}\n![](wk09-slides_files/figure-revealjs/unnamed-chunk-23-1.png){width=768}\n:::\n:::\n\n\n\n---\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestimates <- uk %>%\n  group_by(district_id) %>%\n  summarize(pi_hat = mean(contacted),\n            n = n(),\n            se_hat = sqrt(pi_hat*(1 - pi_hat))/sqrt(n)) %>%\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 253\nColumns: 4\n$ district_id <fct> 319, 320, 323, 326, 328, 329, 330, 331, 337, 338, 339, 344, 347, 348…\n$ pi_hat      <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ n           <int> 1, 2, 4, 2, 3, 2, 2, 1, 4, 1, 1, 2, 2, 1, 1, 1, 2, 2, 6, 4, 1, 3, 1,…\n$ se_hat      <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n```\n\n\n:::\n:::\n\n\n\n---\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngg2_uk <- gg1_uk + \n  geom_errorbar(data = estimates, aes(ymin = pi_hat - 1.64*se_hat,\n                                      ymax = pi_hat + 1.64*se_hat, \n                                      y = NULL),\n                width = .2, color = \"#1b9e77\") + \n  geom_point(data = estimates, aes(y = pi_hat), \n             color = \"#1b9e77\", size = 2)\nprint(gg2_uk)\n```\n\n::: {.cell-output-display}\n![](wk09-slides_files/figure-revealjs/unnamed-chunk-25-1.png){width=768}\n:::\n:::\n\n\n\n---\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nno_pooling <-  uk %>%\n  group_by(district_id) %>%\n  summarize(pi_hat = mean(contacted))  %>%\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 253\nColumns: 2\n$ district_id <fct> 319, 320, 323, 326, 328, 329, 330, 331, 337, 338, 339, 344, 347, 348…\n$ pi_hat      <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n```\n\n\n:::\n:::\n\n\n\n---\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncomplete_pooling <- tibble(district_id = unique(uk$district_id)) %>%\n  mutate(pi_hat = mean(uk$contacted)) %>%\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 253\nColumns: 2\n$ district_id <fct> 492, 374, 350, 463, 393, 366, 432, 375, 385, 377, 378, 461, 387, 367…\n$ pi_hat      <dbl> 0.32, 0.32, 0.32, 0.32, 0.32, 0.32, 0.32, 0.32, 0.32, 0.32, 0.32, 0.…\n```\n\n\n:::\n:::\n\n\n\n---\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|1\"}\nf <- contacted ~ (1 | district_id)\nfit <- glmer(f, data = uk, family = binomial)\n\narm::display(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nglmer(formula = contacted ~ (1 | district_id), data = uk, family = binomial)\ncoef.est  coef.se \n   -0.85     0.10 \n\nError terms:\n Groups      Name        Std.Dev.\n district_id (Intercept) 0.71    \n Residual                1.00    \n---\nnumber of obs: 756, groups: district_id, 253\nAIC = 941.8, DIC = 694\ndeviance = 815.8 \n```\n\n\n:::\n:::\n\n\n\n---\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npartial_pooling <- tibble(district_id = unique(uk$district_id)) %>%\n  mutate(pi_hat = predict(fit, newdata = ., type = \"response\")) %>%\n  arrange(district_id) %>%\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 253\nColumns: 2\n$ district_id <fct> 319, 320, 323, 326, 328, 329, 330, 331, 337, 338, 339, 344, 347, 348…\n$ pi_hat      <dbl> 0.271, 0.249, 0.216, 0.249, 0.231, 0.249, 0.249, 0.271, 0.216, 0.271…\n```\n\n\n:::\n:::\n\n\n\n---\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncomb <- bind_rows(list(\"No Pooling\" = no_pooling,\n                       \"Partial Pooling\" = partial_pooling,\n                       \"Complete Pooling\" = complete_pooling), \n                  .id = \"type\") %>%\n  mutate(type = reorder(type, pi_hat, var)) %>%\n  arrange(district_id) %>%\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 759\nColumns: 3\n$ type        <fct> No Pooling, Partial Pooling, Complete Pooling, No Pooling, Partial P…\n$ district_id <fct> 319, 319, 319, 320, 320, 320, 323, 323, 323, 326, 326, 326, 328, 328…\n$ pi_hat      <dbl> 0.000, 0.271, 0.320, 0.000, 0.249, 0.320, 0.000, 0.216, 0.320, 0.000…\n```\n\n\n:::\n:::\n\n\n\n---\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(comb, aes(x = pi_hat, y = type)) + \n  geom_point(alpha = 0.5) + \n  geom_line(aes(group = district_id), alpha = 0.5)\n```\n\n::: {.cell-output-display}\n![](wk09-slides_files/figure-revealjs/unnamed-chunk-31-1.png){width=768}\n:::\n:::\n\n\n\n# Contact in the UK (w/ predictors!)\n\nWe can also add predictors of the random parameters, such as the competitiveness of the district.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(uk)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 756\nColumns: 3\n$ district_id              <fct> 492, 492, 492, 492, 492, 374, 350, 350, 350, 463, 463, …\n$ contacted                <dbl> 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1…\n$ district_competitiveness <dbl> 0.484, 0.484, 0.484, 0.484, 0.484, 0.510, 0.540, 0.540,…\n```\n\n\n:::\n:::\n\n\n\n---\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nuk_districts <- uk %>% \n  select(district_id, district_competitiveness) %>%\n  distinct() %>%\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 253\nColumns: 2\n$ district_id              <fct> 492, 374, 350, 463, 393, 366, 432, 375, 385, 377, 378, …\n$ district_competitiveness <dbl> 0.484, 0.510, 0.540, 0.454, 0.429, 0.676, 0.603, 0.588,…\n```\n\n\n:::\n\n```{.r .cell-code}\nw_comp <- partial_pooling |>\n  left_join(uk_districts) |>\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 253\nColumns: 3\n$ district_id              <fct> 319, 320, 323, 326, 328, 329, 330, 331, 337, 338, 339, …\n$ pi_hat                   <dbl> 0.271, 0.249, 0.216, 0.249, 0.231, 0.249, 0.249, 0.271,…\n$ district_competitiveness <dbl> 0.584, 0.658, 0.657, 0.453, 0.676, 0.686, 0.659, 0.679,…\n```\n\n\n:::\n:::\n\n\n\n---\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(w_comp, aes(x = district_competitiveness, y = pi_hat)) + \n  geom_point() \n```\n\n::: {.cell-output-display}\n![](wk09-slides_files/figure-revealjs/unnamed-chunk-34-1.png){width=768}\n:::\n:::\n\n\n\n---\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(w_comp, aes(x = district_competitiveness, y = pi_hat)) + \n  geom_point() + \n  geom_smooth(method = lm, se = FALSE, color = \"#1b9e77\")\n```\n\n::: {.cell-output-display}\n![](wk09-slides_files/figure-revealjs/unnamed-chunk-35-1.png){width=768}\n:::\n:::\n\n\n\n---\n\nHey! We should build this directly into our model.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|1\"}\ncontacted ~ district_competitiveness + (1 | district_id)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncontacted ~ district_competitiveness + (1 | district_id)\n```\n\n\n:::\n\n```{.r .cell-code  code-line-numbers=\"|1\"}\nfit <- glmer(f, data = uk, family = binomial)\n\narm::display(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nglmer(formula = contacted ~ (1 | district_id), data = uk, family = binomial)\ncoef.est  coef.se \n   -0.85     0.10 \n\nError terms:\n Groups      Name        Std.Dev.\n district_id (Intercept) 0.71    \n Residual                1.00    \n---\nnumber of obs: 756, groups: district_id, 253\nAIC = 941.8, DIC = 694\ndeviance = 815.8 \n```\n\n\n:::\n:::\n\n---\n::: {.cell}\n\n```{.r .cell-code}\npartial_pooling <- uk %>%\n  select(district_id, district_competitiveness) %>%\n  distinct() %>%\n  mutate(pi_hat = predict(fit, newdata = ., type = \"response\")) %>%\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 253\nColumns: 3\n$ district_id              <fct> 492, 374, 350, 463, 393, 366, 432, 375, 385, 377, 378, …\n$ district_competitiveness <dbl> 0.484, 0.510, 0.540, 0.454, 0.429, 0.676, 0.603, 0.588,…\n$ pi_hat                   <dbl> 0.203, 0.271, 0.307, 0.307, 0.249, 0.293, 0.216, 0.293,…\n```\n\n\n:::\n:::\n\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(partial_pooling, aes(x = district_competitiveness, y = pi_hat)) + \n  geom_point()\n```\n\n::: {.cell-output-display}\n![](wk09-slides_files/figure-revealjs/unnamed-chunk-38-1.png){width=768}\n:::\n:::\n\n\n\n---\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncomb <- bind_rows(list(\"No Pooling\" = no_pooling,\n                       \"Partial Pooling\" = partial_pooling,\n                       \"Complete Pooling\" = complete_pooling), \n                  .id = \"type\") %>%\n  mutate(type = reorder(type, pi_hat, var)) %>%\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 759\nColumns: 4\n$ type                     <fct> No Pooling, No Pooling, No Pooling, No Pooling, No Pool…\n$ district_id              <fct> 319, 320, 323, 326, 328, 329, 330, 331, 337, 338, 339, …\n$ pi_hat                   <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n$ district_competitiveness <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n```\n\n\n:::\n:::\n\n\n  \n---  \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(comb, aes(x = pi_hat, y = type)) + \n  geom_point(alpha = 0.5) + \n  geom_line(aes(group = district_id), alpha = 0.5)\n```\n\n::: {.cell-output-display}\n![](wk09-slides_files/figure-revealjs/unnamed-chunk-40-1.png){width=768}\n:::\n:::\n\n\n\n# A simulation exercise in R\n\n# Contact in Several Countries\n\n$$\n\\text{Pr}(\\text{Contacted}_{i} = 1) = \\text{logit}^{-1}(\\alpha_{jk} + {\\bf X}_i\\beta)\n$$\n$$\n\\alpha_{jk} \\sim N(\\gamma_{0k} + \\gamma_{1k}\\text{Competitiveness}_j, \\sigma^2_{\\alpha}) \\text{ for } j = 1, 2,..., J\n$$\n\n$$\n\\begin{pmatrix} \\gamma_{0k} \\\\ \\gamma_{1k} \\end{pmatrix} \n\\sim \n{\\large} N\\begin{pmatrix}  \\begin{pmatrix} \\mu_{\\gamma_{0}} \\\\ \\mu_{\\gamma_{1}} \\end{pmatrix}, \n\\begin{pmatrix}         \\sigma^2_{\\gamma_{0}}                                           &                 \\rho\\sigma_{\\gamma_{0}}\\sigma_{\\gamma_{1}} \\\\\n\\rho\\sigma_{\\gamma_{0}}\\sigma_{\\gamma_{1}}         &                \\sigma^2_{\\gamma_{1}}\n\\end{pmatrix}\\end{pmatrix} \\text{ , for }k = 1, 2, ..., K\n$$\n\n$$\n\\mu_{\\gamma_{0}} = \\delta_{00} + \\delta_{01}\\text{Proportional Rules}_k\n$$\n\n$$\n\\mu_{\\gamma_{1}} = \\delta_{10} + \\delta_{11}\\text{Proportional Rules}_k\n$$\n\n---\n  \n\n\n::: {.cell}\n\n```{.r .cell-code}\nrainey <- crdata::rainey2015 |>\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 5,126\nColumns: 5\n$ election_id              <chr> \"Canada\", \"Canada\", \"Canada\", \"Canada\", \"Canada\", \"Cana…\n$ district_id              <chr> \"Canada; District 7\", \"Canada; District 4\", \"Canada; Di…\n$ contacted                <fct> Contacted, Not Contacted, Not Contacted, Not Contacted,…\n$ district_competitiveness <dbl> 0.740, 0.420, 0.692, 0.692, 0.610, 0.742, 0.742, 0.742,…\n$ electoral_rules          <fct> SMD, SMD, SMD, SMD, SMD, SMD, SMD, SMD, SMD, SMD, SMD, …\n```\n\n\n:::\n:::\n\n\n\n---\n\nWe can fit this model with `lmer()`, but this *relatively small* model is too big or complex. \n\n::: {.fragment .custom .blur}\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|2,3,4\"}\n# model is fragile\nf <- contacted ~ district_competitiveness*electoral_rules +\n               (1 | district_id) +\n               (1 + district_competitiveness | election_id)\nfit <- glmer(f, data = rainey, family = binomial)\n```\n:::\n\n\n:::\n\n::: {.fragment .custom .blur}\nStan would have no problems with this one...\n:::\n\n---\n\nAnd show the estimates.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\narm::display(fit, detail = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nglmer(formula = contacted ~ district_competitiveness * electoral_rules + \n    (1 | district_id) + (1 + district_competitiveness | election_id), \n    data = rainey, family = binomial)\n                                            coef.est coef.se z value Pr(>|z|)\n(Intercept)                                 -2.35     0.59   -4.01    0.00   \ndistrict_competitiveness                     1.21     0.81    1.49    0.14   \nelectoral_rulesSMD                          -0.74     0.72   -1.03    0.30   \ndistrict_competitiveness:electoral_rulesSMD  3.07     1.03    2.99    0.00   \n\nError terms:\n Groups      Name                     Std.Dev. Corr \n district_id (Intercept)              0.47          \n election_id (Intercept)              0.18          \n             district_competitiveness 0.27     1.00 \n Residual                             1.00          \n---\nnumber of obs: 5126, groups: district_id, 567; election_id, 5\nAIC = 5580.3, DIC = 5131\ndeviance = 5347.5 \n```\n\n\n:::\n:::\n\n\n\n---\n\nUsing the `lmer()`-like formula, we can fit the hiearchical model with Stan.\n  \n\n\n::: {.cell}\n\n```{.r .cell-code}\nstart_time <- Sys.time()\nstan_fit <- brm(contacted ~ district_competitiveness*electoral_rules +\n                  (1 | district_id) + \n                  (1 + district_competitiveness | election_id),\n                data = rainey, \n                family = bernoulli, \n                chains = 10,\n                cores = 10,\n                iter = 4000, \n                backend = \"cmdstanr\")\nend_time <- Sys.time()\n```\n:::\n\n\n\n::: {.fragment .custom .blur}\n\nAnd it fits in less than 10 minutes. This took hours or days in 2012 with JAGS.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nend_time - start_time\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTime difference of 6.86 mins\n```\n\n\n:::\n:::\n\n\n\n:::\n\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(stan_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: bernoulli \n  Links: mu = logit \nFormula: contacted ~ district_competitiveness * electoral_rules + (1 | district_id) + (1 + district_competitiveness | election_id) \n   Data: rainey (Number of observations: 5126) \n  Draws: 10 chains, each with iter = 4000; warmup = 2000; thin = 1;\n         total post-warmup draws = 20000\n\nMultilevel Hyperparameters:\n~district_id (Number of levels: 567) \n              Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsd(Intercept)     0.52      0.08     0.38     0.69 1.00     4310     4360\n\n~election_id (Number of levels: 5) \n                                        Estimate Est.Error l-95% CI u-95% CI Rhat\nsd(Intercept)                               0.66      0.56     0.03     2.17 1.00\nsd(district_competitiveness)                0.85      0.65     0.04     2.53 1.00\ncor(Intercept,district_competitiveness)    -0.05      0.58    -0.94     0.95 1.00\n                                        Bulk_ESS Tail_ESS\nsd(Intercept)                               2585      739\nsd(district_competitiveness)                5532     8377\ncor(Intercept,district_competitiveness)     4953     3089\n\nRegression Coefficients:\n                                            Estimate Est.Error l-95% CI u-95% CI Rhat\nIntercept                                      -2.35      0.78    -3.90    -0.83 1.00\ndistrict_competitiveness                        1.30      1.04    -0.73     3.43 1.00\nelectoral_rulesSMD                             -0.77      1.04    -2.98     1.22 1.00\ndistrict_competitiveness:electoral_rulesSMD     3.05      1.41     0.15     5.75 1.00\n                                            Bulk_ESS Tail_ESS\nIntercept                                       3314     1526\ndistrict_competitiveness                        4545     4831\nelectoral_rulesSMD                              2815     1553\ndistrict_competitiveness:electoral_rulesSMD     5207     7799\n\nDraws were sampled using sample(hmc). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n:::\n\n\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(stan_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: bernoulli \n  Links: mu = logit \nFormula: contacted ~ district_competitiveness * electoral_rules + (1 | district_id) + (1 + district_competitiveness | election_id) \n   Data: rainey (Number of observations: 5126) \n  Draws: 10 chains, each with iter = 4000; warmup = 2000; thin = 1;\n         total post-warmup draws = 20000\n\nMultilevel Hyperparameters:\n~district_id (Number of levels: 567) \n              Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsd(Intercept)     0.52      0.08     0.38     0.69 1.00     4310     4360\n\n~election_id (Number of levels: 5) \n                                        Estimate Est.Error l-95% CI u-95% CI Rhat\nsd(Intercept)                               0.66      0.56     0.03     2.17 1.00\nsd(district_competitiveness)                0.85      0.65     0.04     2.53 1.00\ncor(Intercept,district_competitiveness)    -0.05      0.58    -0.94     0.95 1.00\n                                        Bulk_ESS Tail_ESS\nsd(Intercept)                               2585      739\nsd(district_competitiveness)                5532     8377\ncor(Intercept,district_competitiveness)     4953     3089\n\nRegression Coefficients:\n                                            Estimate Est.Error l-95% CI u-95% CI Rhat\nIntercept                                      -2.35      0.78    -3.90    -0.83 1.00\ndistrict_competitiveness                        1.30      1.04    -0.73     3.43 1.00\nelectoral_rulesSMD                             -0.77      1.04    -2.98     1.22 1.00\ndistrict_competitiveness:electoral_rulesSMD     3.05      1.41     0.15     5.75 1.00\n                                            Bulk_ESS Tail_ESS\nIntercept                                       3314     1526\ndistrict_competitiveness                        4545     4831\nelectoral_rulesSMD                              2815     1553\ndistrict_competitiveness:electoral_rulesSMD     5207     7799\n\nDraws were sampled using sample(hmc). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n:::\n\n\n\n---\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create grid\ngrid <- rainey |>\n  select(district_id, \n         election_id, \n         district_competitiveness, \n         electoral_rules) |>\n  distinct() |>\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 567\nColumns: 4\n$ district_id              <chr> \"Canada; District 7\", \"Canada; District 4\", \"Canada; Di…\n$ election_id              <chr> \"Canada\", \"Canada\", \"Canada\", \"Canada\", \"Canada\", \"Cana…\n$ district_competitiveness <dbl> 0.740, 0.420, 0.692, 0.610, 0.742, 0.822, 0.518, 0.670,…\n$ electoral_rules          <fct> SMD, SMD, SMD, SMD, SMD, SMD, SMD, SMD, SMD, SMD, SMD, …\n```\n\n\n:::\n:::\n\n\n::: {.fragment .custom .blur}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# compute posterior average for each district\npred_district <- grid |>  \n  add_epred_draws(stan_fit) %>%\n  summarize(post_avg = mean(.epred)) %>%\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 567\nColumns: 6\nGroups: district_id, election_id, district_competitiveness, electoral_rules [567]\n$ district_id              <chr> \"Canada; District 1\", \"Canada; District 10\", \"Canada; D…\n$ election_id              <chr> \"Canada\", \"Canada\", \"Canada\", \"Canada\", \"Canada\", \"Cana…\n$ district_competitiveness <dbl> 0.610, 0.607, 0.765, 0.624, 0.440, 0.572, 0.750, 0.433,…\n$ electoral_rules          <fct> SMD, SMD, SMD, SMD, SMD, SMD, SMD, SMD, SMD, SMD, SMD, …\n$ .row                     <int> 4, 11, 41, 46, 59, 62, 43, 52, 168, 176, 131, 10, 103, …\n$ post_avg                 <dbl> 0.568, 0.480, 0.593, 0.553, 0.292, 0.446, 0.600, 0.304,…\n```\n\n\n:::\n:::\n\n\n:::\n\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# compute posterior average for each country (in a 'typical' district)\npred_country <- rainey %>%\n  select(district_id, \n         election_id, \n         district_competitiveness, \n         electoral_rules) %>%\n  distinct() %>%\n  add_epred_draws(stan_fit, \n                  re_formula = ~ (1 + district_competitiveness | election_id)) %>%\n  summarize(post_avg = mean(.epred)) %>%\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 567\nColumns: 6\nGroups: district_id, election_id, district_competitiveness, electoral_rules [567]\n$ district_id              <chr> \"Canada; District 1\", \"Canada; District 10\", \"Canada; D…\n$ election_id              <chr> \"Canada\", \"Canada\", \"Canada\", \"Canada\", \"Canada\", \"Cana…\n$ district_competitiveness <dbl> 0.610, 0.607, 0.765, 0.624, 0.440, 0.572, 0.750, 0.433,…\n$ electoral_rules          <fct> SMD, SMD, SMD, SMD, SMD, SMD, SMD, SMD, SMD, SMD, SMD, …\n$ .row                     <int> 4, 11, 41, 46, 59, 62, 43, 52, 168, 176, 131, 10, 103, …\n$ post_avg                 <dbl> 0.511, 0.507, 0.685, 0.527, 0.318, 0.466, 0.669, 0.311,…\n```\n\n\n:::\n:::\n\n\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(pred_district, aes(x = district_competitiveness, y = post_avg)) +\n  facet_wrap(vars(election_id)) +\n  geom_point() +\n  geom_line(data = pred_country, color = \"red\", size = 1.5)\n```\n\n::: {.cell-output-display}\n![](wk09-slides_files/figure-revealjs/unnamed-chunk-51-1.png){width=768}\n:::\n:::\n\n\n\n---\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrid <- rainey %>%\n  select(district_id, \n         election_id, \n         district_competitiveness, \n         electoral_rules)\n\np <- predictions(stan_fit,\n                 newdata = grid) |>\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 5,126\nColumns: 9\n$ rowid                    <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, …\n$ estimate                 <dbl> 0.694, 0.320, 0.562, 0.562, 0.570, 0.632, 0.632, 0.632,…\n$ conf.low                 <dbl> 0.457, 0.143, 0.322, 0.322, 0.338, 0.399, 0.399, 0.399,…\n$ conf.high                <dbl> 0.865, 0.571, 0.769, 0.769, 0.788, 0.817, 0.817, 0.817,…\n$ district_id              <chr> \"Canada; District 7\", \"Canada; District 4\", \"Canada; Di…\n$ election_id              <chr> \"Canada\", \"Canada\", \"Canada\", \"Canada\", \"Canada\", \"Cana…\n$ district_competitiveness <dbl> 0.740, 0.420, 0.692, 0.692, 0.610, 0.742, 0.742, 0.742,…\n$ electoral_rules          <fct> SMD, SMD, SMD, SMD, SMD, SMD, SMD, SMD, SMD, SMD, SMD, …\n$ df                       <dbl> Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf, …\n```\n\n\n:::\n:::\n\n\n\n---\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_typical <- predictions(\n  stan_fit,\n  newdata = grid, \n  re_formula = ~ (1 + district_competitiveness | election_id)\n  ) |>\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 5,126\nColumns: 9\n$ rowid                    <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, …\n$ estimate                 <dbl> 0.659, 0.297, 0.606, 0.606, 0.511, 0.661, 0.661, 0.661,…\n$ conf.low                 <dbl> 0.606, 0.230, 0.559, 0.559, 0.466, 0.608, 0.608, 0.608,…\n$ conf.high                <dbl> 0.711, 0.374, 0.652, 0.652, 0.555, 0.713, 0.713, 0.713,…\n$ district_id              <chr> \"Canada; District 7\", \"Canada; District 4\", \"Canada; Di…\n$ election_id              <chr> \"Canada\", \"Canada\", \"Canada\", \"Canada\", \"Canada\", \"Cana…\n$ district_competitiveness <dbl> 0.740, 0.420, 0.692, 0.692, 0.610, 0.742, 0.742, 0.742,…\n$ electoral_rules          <fct> SMD, SMD, SMD, SMD, SMD, SMD, SMD, SMD, SMD, SMD, SMD, …\n$ df                       <dbl> Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf, …\n```\n\n\n:::\n:::\n\n\n\n---\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(p, aes(x = district_competitiveness, y = estimate)) +\n  facet_wrap(vars(election_id)) +\n  geom_point() +\n  geom_line(data = p_typical, color = \"red\", size = 1.5)\n```\n\n::: {.cell-output-display}\n![](wk09-slides_files/figure-revealjs/unnamed-chunk-54-1.png){width=768}\n:::\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}