project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!slides/"  

execute:
  freeze: auto

website:
  title: "Modern Statistical Modeling"
  site-url: https://pos5747.github.io/
  google-analytics: "G-ZV1MJ9E632"
  navbar:
    left:
      - href: index.qmd
        text: Schedule
      - href: https://pos5747.github.io/notes/
        text: Notes
      - href: research-project.qmd
        text: Research Project
      - href: workshop.qmd
        text: Workshop
      - href: syllabus.pdf
        text: Syllabus

format:
  html:
    theme:
      - sandstone
    css: styles.css
    toc: true
    
resources:
  - syllabus.pdf
  - exr/
  - files/
  - slides/
  - data/



