---
title: "Schedule"
editor:
  markdown:
    wrap: 72
---

- Office hours: Mondays, 1:00–2:00 PM, Bellamy 540.
- Our TA, Bryson Lyons, will hold office hours (time TBD) and an optional study/review session (time TBD).

------------------------------------------------------------------------

aug 25 · **review** · \[[slides](slides/wk01-slides.pdf)\]
\[[notes](https://pos5747.github.io/notes/wk01/frac-exp-log.html)\]
\[[exercises](exr/wk01-exr.pdf)\] \[[solutions](exr/wk01-exr-sol.pdf)\]
[fractions, logarithms, and exponents; calculus; matrices; probability
theory]{.topics}

------------------------------------------------------------------------

sep 01 · **ml** · \[[slides](slides/wk02-slides.pdf)\]
\[[notes](https://pos5747.github.io/notes/wk02/01-maximum-likelihood.html)\]
\[[exercises](exercises/wk02-exercises.html)\] [*maximum likelihood;
invariance principle; predictive distribution*]{.topics}

------------------------------------------------------------------------

sep 08 · **se** · \[[slides](slides/wk03-slides.pdf)\]
\[[notes](https://pos5747.github.io/notes/wk03/01-sampling-distribution.html)\]
\[[exercises](exercises/wk03-exercises.html)\] [sampling
distribution; parametric bootstrap; variance and standard error; delta
method]{.topics}

------------------------------------------------------------------------

sep 15 · **X** · \[[slides](slides/wk04-slides.pdf)\]
\[[materials](files/wk04-r.qmd)\]
\[[notes](https://pos5747.github.io/notes/wk04/01-design-matrix.html)\]
\[[exercises](exercises/wk04-exercises.html)\] [adding covariates;
logit models; expected value and first difference]{.topics}

------------------------------------------------------------------------

sep 22 · **{marginaleffects}** · \[[slides](slides/wk05-slides.pdf)\]
\[[materials](files/wk05-r.qmd)\]
\[[notes](https://pos5747.github.io/notes/wk05/01-marginaleffects.html)\]
\[[exercises](exercises/wk05-exercises.html)\]
[{marginaleffects}; information criteria; zero inflation]{.topics}

------------------------------------------------------------------------

sep 29 · **bayes** · \[[slides](slides/wk06-slides.pdf)\]
\[[ordered logit slides](slides/wk06-ordered/ordered.html)\]
\[[materials](files/wk06-r.qmd)\]
\[[notes](https://pos5747.github.io/notes/wk06/01-bayes.html)\]
\[[exercises](exercises/wk06-exercises.html)\]
[Bayesian
inference; rejection sampling; a Bayesian invariance property; ordered logit]{.topics} [Due Sep. 29: prospectus for research paper.]{.remarks}

------------------------------------------------------------------------

oct 06 · **mcmc** · \[[slides](slides/wk07-lecture/lecture.html)\]
\[[multinomial logit slides](slides/wk07-unordered/unordered.html)\]
\[[materials](files/wk07-r.qmd)\]
\[[notes](https://pos5747.github.io/notes/wk07/01-metrop.html)\]
\[[exercises](exercises/wk07-exercises.html)\]
[Metropolis
algorithm; HMC + Stan and its R ecosystem; multinomial logit]{.topics}

------------------------------------------------------------------------

oct 13 · [**midterm exam**]{.text-warning}

------------------------------------------------------------------------

oct 20 · **ai**
[Due: (1) first draft of research paper due and (2) initial outline of
take-home workshop handout.]{.remarks}

------------------------------------------------------------------------

oct 27 · **hierarchical models, 1** [Due: (1) peer-review memo and (2) first drafts of all workshop materials.]{.remarks}

------------------------------------------------------------------------

nov 03 · **hierarchical models, 2** [Due: workshop
rehearsal]{.remarks}

------------------------------------------------------------------------

nov 10 · **irt**

------------------------------------------------------------------------

nov 17 · **a final perspective**

------------------------------------------------------------------------

nov 24 · **wrap** [Due: **second
draft** of research paper.]{.remarks}

------------------------------------------------------------------------

dec 01 · **posters** [No class meeting; instead, poster presentations on
the 5th floor of Bellamy from 9:45 to 11:30 AM.]{.remarks}

------------------------------------------------------------------------

dec 08 · [**final exam**]{.text-warning} [9:00–11:30 AM in Bellamy 113,
our usual meeting time. Due: final draft of research paper.]{.remarks}
