---
title: "Research Project"
bibliography: references.bib
#citation-location: margin
reference-location: margin
---

Your task this semester: *write a paper of modest ambition and exceptional quality that makes a descriptive argument about politics.*

::: callout-note
I am significantly revising this project from previous semesters. While the important pieces of the project (i.e., overall expectations and deadlines) will not change without advance warning, I hope to continuously clarify this document in light of conversation with students about their projects.
:::

## Overview

We'll borrow Gerring's [-@gerring2012, p. 722] definition of a *descriptive argument*:

> A descriptive argument describes some aspect of the world. In doing so, it aims to answer what questions (e.g., when, whom, out of what, in what manner) about a phenomenon or a set of phenomena. Descriptive arguments are about what is/was. For example: 'Over the course of the past two centuries there have been three major waves of democratization.'

You might feel confused. After all, Gerring writes that description "has come to be employed as a euphemism for a failed, or not yet proven, causal inference." At best, we might think that description only serves to support the primary task of causal inference. Indeed, @kkv [p. 34] write that "description, in turn, *loses most of its interest* unless linked to some causal relationships."

However, description is an essential component of social science. @dekadt2025 argue that description is "a fundamental component of the social scientific enterprise" (2) that "engages theory by invoking existing theories, motivating new theoretical models and their refinement, and in some cases even evaluating theory" (24). Gerring writes that "description can be written out of the discipline only at great cost to our understandings of the world" (744). And @holmes2024 write that "answering questions of 'who,' 'what,' 'when,' 'where,' and 'how'---in concert with but also independent from causal inquiry---is vital to the continued relevance and coherence of our discipline in both scholarly and public-facing work" (54).

As a whole, I suggest that social science asks: *how can we intervene to make the world a better place?* This implies three parts.

1.  First, what does the world look like now?
2.  Second, what worlds would be better?
3.  And third, what are the effects of potential interventions?

I view answers the the first question---a description of the world as it exists---as a difficult and worthwhile challenge. It seems difficult to even entertain the second and third questions without a thorough understanding of the world as it exists.

And you may think that description is easy, and establishing causality is hard. I think you'll find that description is easier *statistically,* but a more difficult struggle overall.[^1]

[^1]: My thinking is something like this. When you randomly assign $T$ and you measure $Y$ afterward, you've established that $T$ causes $X$. But suppose that you just measure $Y$. It isn't clear what you've just measured or whether it's meaningful. Of course, these same questions lay hiding in the shadows in the randomized experiment. But the randomization guarantees a "causal inference" that is sufficient to strike our fancy. The descriptive argument brings the subtler questions of measures and their meanings into the broad daylight. Fuzzy concepts and measurements can't hide behind a "compelling identification strategy" when you are making a descriptive argument.

Examples of the struggle to describe are easy to find. Consider two ideas that are central to political science: "democracy" or "political ideology." If a reporter from the New York Times asked whether democracy was in decline around the world, the answer isn't easy or obvious. Political scientists are not in agreement. If that reporter asked you whether there are many or few moderate voters in the US, the answer isn't obvious or easy. Again, political scientists are not in agreement.

# Examples

## A Recent Debate About Moderates

A recent exchange in the *American Political Science Review* centers on how best to characterize ideological moderation in the American public. In the original article, @fowler2023moderates develop a statistical model to distinguish among types of moderates, finding that while a single ideological dimension captures most Americans’ policy views, moderates—especially those not neatly aligned—remain central to electoral accountability. In response, @broockman2025moderates critique this approach, arguing that it overestimates the number of genuinely one-dimensional voters and fails to account for individuals with cross-pressured or multidimensional views. Finally, @fowler2024assessing reply by showing that Broockman and Lauderdale’s visual and simulation-based critiques do not invalidate their main conclusions, reaffirming that most Americans’ policy preferences are well summarized by a single ideological dimension and that most such individuals are ideologically moderate.

## A Recent Debate About Backsliding

-   @little2024a argue that objective indicators (e.g., electoral outcomes) show little evidence of global democratic decline over the past decade, challenging findings based on subjective expert assessments.

Numerous authors offered responses published in the same issue of *PS*. For example:

1.  @knutsen2024 critique Little and Meng's reliance on objective measures, highlighting issues in conceptualization, indicator selection, and aggregation that may overlook nuanced democratic erosion.
2.  @gorokhovskaia2024 emphasizes the importance of disaggregating data, noting that while electoral indicators may remain stable, other areas like media freedom show signs of backsliding.
3.  @miller2024 contends that objective indicators fail to detect democratic erosion within established democracies, missing subtle but significant declines.

In a reply, @little2024b acknowledge the critiques and emphasize the need for improved measurement tools to better understand democratic backsliding.

# Scaffolding

I use scaffolding to help you manage a complex project. This paper is an *important* component of our work this semester; intermediate assignments make progress *urgent* before the end of the semester.

The several assignments do not increase the amount of work. Instead, they help you *distribute the work* more evenly across the semester. These assignments give you time to reflect, revise, and improve each part of your project. They make the final result is stronger and less stressful to produce. It also gives me time to give you feedback early and often.

## Optional Early Assignments

-   **Descriptive Research in Your Field** *(Optional; due by Sep. 3)* Reflect on what descriptive research looks like in your field and identify examples of high-quality description. Consider the following prompts as starting points:
    a.  Engage with @gerring2012, @dekadt2025, and @holmes2024.[^2] What parts of their arguments do you find most compelling?
    b.  What is the value of description in your research area? Take one or two papers that you admire---the kinds of papers that you'd like to write---and ask yourself "what would this project have looked like if the authors had instead focused on carefully *describing* their critical concepts (rather than looking for their effects and/or causes)?"
-   **Data Sets** *(Optional; due by Sep. 10)* Identify publicly available data sets relevant to your general area of interest. For each data set, briefly describe the variables, cases, and time periods included. Flag any variables that seem especially important. Realize there is lots of data available---search deep and wide! And talk to other students and faculty.
-   **Concepts** *(Optional; due by Sep. 17)* Explore and explain the major theoretical or empirical concepts scholars focus on in your area.
-   **Narrowing Your Topics** *(Optional; due by Sep. 24)* Narrow your focus by choosing a few concepts you find interesting. Identify FSU faculty working in these areas. Sketch 3–5 potential research questions.

## Required Assignments

-   **Prospectus** *([Required]{.text-warning}; due by Oct. 1)* A memo describing your project in as much detail as possible. This should resemble the structure of a paper, though it will still be an early, developing version. At a minimum, the prospectus should: (1) clearly state the descriptive claim or question; (2) explain why the claim is important, independent of any causal links between the focal variables; (3) demonstrate the feasibility of the data collection (e.g., collected 20% or ideally all of the data); and include an initial data analysis (scatterplots and averages might be sufficient). *Instructor comments, ASAP.*
-   **First Draft** *([Required]{.text-warning}; due by Oct. 22)* Submit the first full draft of your paper. This should include a working version of all major sections, figures, and tables. *Feedback from a peer, ASAP*.
-   **Second Draft** *([Required]{.text-warning}; due by Nov. 25 ([Tuesday!]{.text-danger}))* Submit a substantially revised draft of your paper that incorporates peer feedback. *Instructor comments ASAP*.
-   **Poster Presentation** *([Required]{.text-warning}; done week of Dec. 3)* Present your research in a short, conference-style poster session. This is a low-stakes chance to get feedback and practice communicating your work.
-   **Final Project** *([Required]{.text-warning}; due by Dec. 10)* Submit the final version of your research paper. You must submit a PDF of the final version of the paper and the data and computer code to reproduce your work. This version should reflect feedback from both the poster session and instructor comments. This version should be *polished*.

[^2]: See also Part II of Gerring's *Social Science Methodology* for a supplement to Gerrying (2012).

# Format

Your paper should be formatted as if preparing to submit to a political science journal or post a preprint online.[^3]

[^3]: You can find requirements for various journals on their websites (e.g., [*APSR*](https://www.cambridge.org/core/journals/american-political-science-review/information/author-instructions/preparing-your-materials), [*AJPS*](https://ajps.org/guidelines-for-manuscripts/manuscript-preparation/), [*PSRM*](https://www.cambridge.org/core/journals/political-science-research-and-methods/information/author-instructions/preparing-your-materials)). Some journals have idiosyncratic requirements, like endnotes or double-spaced footnotes, but most working papers have a standard format and look like [this one](https://osf.io/preprints/osf/5am9q_v) of mine.

-   No page or word count limit.[^4]
-   Title, author, abstract, and date on first page.
-   Page numbers on every page.
-   Appendices allowed, but only include materials needed to make your argument. Do not use the appendix as a dumping ground for results or ideas only loosely related to your point.
-   References in [APSA style](https://connect.apsanet.org/stylemanual/) (e.g., like the references in [this working paper](https://osf.io/preprints/osf/5am9q_v2))

[^4]: You should initially think of this project as a "research note" (i.e., "moderate ambition"). Even if you have a clear vision for a larger project, focus on a small, manageable piece. A "typical" research note might have a limit of about 4,000 words. As the paper progresses, it's fine for it to grow into a longer paper. However, please present your arguments compactly and efficiently (i.e., "exceptional quality").

I recommend LaTeX,[^5] but any software is fine.

[^5]: Some folks Overleaf's implementation.

# Style

Focus narrowly on a single descriptive claim. Establish the normative and/or theoretical importance of the claim. Clearly describe your precise claim and the evidence. Avoid fluff. Make your paper easy to read.

Weingast's [-@caltech_rules] advice applies.

> Papers must focus on one main point. Do not attempt to enrich your paper with many asides. Avoid comments that suggest implications not essential for the development of the central point. It is far better to have a narrow, focused, and useful paper than a rich one that readers find confusing and therefore ignore.

That's worth saying again: write a "narrow, focused, and useful paper."

Related, there are two temptations worth avoiding:

-   It can be tempting to overcome a deficiency in the quality of an argument through quantity. Do not fall for this temptation. Make one point clearly.
-   It can be tempting to show off data analytic skills. A few averages over time or a simple scatterplot might be sufficient to make the point clearly.

Zach Elkins has a wonderful [collection](https://sites.google.com/site/zachelkinstexas/me-write-pretty-some-day) of resources about writing. I particularly like the following:

-   Collier's "Notes on Writing and Editing" \[[pdf](https://github.com/carlislerainey/elkins-writing-resources/blob/main/original-documents/collier%20Notes%20on%20Writing.pdf)\]
-   Loehle's “A Guide to Increased Creativity in Research---Inspiration or Perspiration?" \[[pdf](https://github.com/carlislerainey/elkins-writing-resources/blob/main/original-documents/loehle90.pdf)\]
-   Luskin's "Robert's Rules: Suggestions for Writing" \[[pdf](https://github.com/carlislerainey/elkins-writing-resources/blob/main/original-documents/Robert's%20Rules%20January%2008.pdf)\]
-   Stimson's "Professional Writing in Political Science: A Highly Opinionated Essay" \[[pdf](https://github.com/carlislerainey/elkins-writing-resources/blob/main/original-documents/stimson%20writing.pdf)\]
-   Weingast's "Structuring Your Papers (CalTech Rules)" \[[pdf](https://github.com/carlislerainey/elkins-writing-resources/blob/main/original-documents/caltech_rules.pdf)\]

Writing *as a process* can be challenging. I strongly recommend Silva's *How to Write a Lot.* I wrote a [summary](https://www.carlislerainey.com/blog/2023-08-15-daily-writing/) of what I learned from that book.
