{
  "hash": "e80ef2479ad64582f11408b351b323e6",
  "result": {
    "engine": "knitr",
    "markdown": "---\n# The always-open companion to wk02-exercises.qmd.\n#\n# Same page, same content, solutions never gated -- for Carlisle and the TA.\n# The week file is the only source; this wrapper adds nothing but front matter.\n# To make one of these for a new week, copy this file and change the two\n# `wk02` strings below.\n#\n# `solution-unlock` in the past is what opens the solutions: the week file\n# does not set that key, so this one survives the include's metadata merge.\n# (`title` does not survive -- the week file's wins -- hence the subtitle.)\nsubtitle: \"Instructor and TA copy: complete solutions, always open\"\nsolution-unlock: \"2000-01-01 00:00\"\n\n# Keep it off the site's search box and out of Google.\nsearch: false\nformat:\n  html:\n    include-in-header:\n      text: '<meta name=\"robots\" content=\"noindex, nofollow\">'\n---\n\n---\ntitle: \"Week 2 Exercises\"\ndistributed: 2026-09-01\nshow-hints: true\n---\n\n\nDo all the exercises below.\n\n\n\n\n\n# Maximum Likelihood\n\n## A Function of What? {ref=\"function-of-what\"}\n\nFor the Bernoulli model, we wrote the likelihood as $L(\\pi) = \\pi^{k}(1 - \\pi)^{(N - k)}$, where $k$ is the number of successes in $N$ trials. In the likelihood, which symbol is the variable? Which symbol(s) are fixed? In one sentence, describe the question that $L(\\pi)$ answers.\n\n::: hint\n\nIn the pmf $f(x; \\pi)$, we treat $x$ as the variable and $\\pi$ as fixed. What changes when we relabeled $f(x; \\pi)$ as $L(\\pi)$? \n\n:::\n\n::: hint\n\nBefore the notes ever introduce $L(\\pi)$, the Bernoulli section evaluates the likelihood (for the toothpaste cap data) at several candidate values of $\\pi$ (0.1, 0.45, 0.55, and 0.9). Reread that paragraph.\n\n:::\n\n::: sol\n\nThe likelihood reverses the roles of $x$ and $\\pi$ compared to $f(x; \\pi)$. \n\nWe think of $f(x; \\pi)$ as \"the probability of $x$, given $\\pi$.\"\n\nBut for the likelihood, the data are fixed (we observed them!), and we want to vary the parameter (to optimize across it). Thus, for $L(\\pi)$, the variable is $\\pi$ and the data (or summaries $k$ and $N$, in this case) are fixed numbers. \n\n$L(\\pi)$ answers the question: *if the parameter were $\\pi$, how likely would these data be?* ML then finds the $\\pi$ that makes the observed data most likely.\n\n**Something that's wrong**: the likelihood is *not* a probability distribution over $\\pi$. It doesn't integrate to one. It does not allow a probability claim about the parameter.\n\n:::\n\n## Why the Log? Predict, Then Check {ref=\"why-the-log\"}\n\nSuppose you observe 2,000 Bernoulli trials with $\\pi = 0.5$, so that each observation equals one with probability 0.5 and zero with probability 0.5. The likelihood is the product of these 2,000 probabilities.\n\n*Before you run it*, predict what the first line of R code below returns. Write down your reasoning.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\ny <- rbinom(2000, 1, 0.5)\n\nprod(dbinom(y, 1, 0.5))             # the likelihood, computed directly\nsum(dbinom(y, 1, 0.5, log = TRUE))  # the log-likelihood\n```\n:::\n\n\nNow run both lines. Explain what happened, why it's expected, and why it matters for ML. The log fixes this computational problem. How?\n\n::: hint\n\nThe product is $0.5^{2000}$. Figure out roughly how big that is as a power of ten. Compare that to the smallest positive number R can store (i.e., run `.Machine$double.xmin`).\n\nUse this rule of thumb: $2^{10} = 1024 \\approx 10^3$. In turn, $\\left(\\frac{1}{2}\\right)^{10} \\approx 10^{-3}$, so that ten halvings is about the same as three orders of magnitude. \n\n:::\n\n::: hint\n\nThe notes give two separate reasons for taking the log (i.e., where they define $L(\\pi)$ in the Bernoulli example). One reason is what you just watched happen in R. \n\n:::\n\n::: sol\n\nStart with the prediction. The product is $0.5^{2000} \\approx 10^{-600}$. Computers can't keep track of numbers that small (the smallest positive number R can store is about $10^{-308}$; run `.Machine$double.xmin`), so `prod()` returns exactly 0.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\ny <- rbinom(2000, 1, 0.5)\n\nprod(dbinom(y, 1, 0.5))             # the likelihood, computed directly\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(dbinom(y, 1, 0.5, log = TRUE))  # the log-likelihood\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -1386.294\n```\n\n\n:::\n:::\n\n\nThe *log*-likelihood works just fine, though. It's $2000 \\log(0.5) \\approx -1386.29$. This is a very ordinary number that computers can handle.\n\n(Importantly, a hill-climbing algorithm can't climb a function that returns 0 everywhere!)\n\n:::\n\n## What a Grid Can Miss {ref=\"grid-miss\"}\n\nSuppose a colleague uses a Bernoulli model and estimates $\\pi$ by computing the log-likelihood at the eleven values $0, 0.1, 0.2, \\ldots, 1$ and reporting the best of the eleven as \"the ML estimate.\" In one or two sentences, in what sense is that answer wrong, and how would you tighten it?\n\n::: sol\n\nA grid will almost never *contain* the maximum. Instead the maximum will lie *between* the elements on the grid. For example, the true ML estimate is $k/N$. Unless we're lucky, this will not be a multiple of 0.1. \n\nTo tighten the answer, we could make the grid finer near the peak (or just use calculus or `optim()`).\n\n:::\n\n## From Derivative to Estimator {ref=\"deriv-to-est\"}\n\nLast week, we computed $\\frac{d\\ell}{d\\pi}$ for $\\ell(\\pi) = S \\log(\\pi) + (N - S)\\log(1 - \\pi)$. Set the derivative equal to zero, set $\\pi = \\hat{\\pi}$, solve for $\\hat{\\pi}$.\n\n::: sol\n\nWe already found that $\\frac{d\\ell}{d\\pi} = \\frac{S}{\\pi} - \\frac{N - S}{1 - \\pi}$. Setting $\\frac{d\\ell}{d\\pi} = 0$, setting $\\pi = \\hat{\\pi}$, and solving for $\\hat{\\pi}$, we obtain\n\n$$\n\\begin{aligned}\n\\frac{S}{\\hat{\\pi}} &= \\frac{N - S}{1 - \\hat{\\pi}} \\\\\nS(1 - \\hat{\\pi}) &= (N - S)\\hat{\\pi} \\\\\nS - S\\hat{\\pi} &= N\\hat{\\pi} - S\\hat{\\pi} \\\\\nS &= N\\hat{\\pi} \\\\\n\\hat{\\pi} &= \\frac{S}{N}.\n\\end{aligned}\n$$\n\nThe ML estimate is the fraction of successes (i.e., the sample average of the 0s and 1s).\n\n:::\n\n## Reading a Contour Plot {ref=\"contour\"}\n\nThe plot below shows the log-likelihood for the beta model from the notes. We have 100 observations (in this case, fake data simulated from a beta distribution). I computed the log-likelihood $\\log L(\\alpha, \\beta)$ over a grid of parameter pairs.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](wk02-exercises-sol_files/figure-html/ex05-contour-1.png){width=768}\n:::\n:::\n\n\na. Roughly where is the ML estimate?\nb. What does a labeled curve on this plot mean (i.e., what do the points on that curve have in common)?\nc. For the Bernoulli model, we found $\\hat{\\pi}$ quickly with pencil and paper. Why can't we do that here?\n\n::: sol\n\n**Part (a)** Around $\\alpha = 12$, $\\beta = 12$. (`optim()` found the maximum at $\\hat{\\alpha} \\approx 12.0$ and $\\hat{\\beta} \\approx 11.9$.)\n\n**Part (b)** A curve is a *level set*, such that every pair $(\\alpha, \\beta)$ on that curve produces the same value of the log-likelihood. If we imagine the contour plot as a mountain coming off the screen toward us, then each point along a curve is at the same \"height\" on that mountain (i.e., if you followed that path, you would go around the mountain and never up or down.)\n\n**Part (c)** The beta log-likelihood contains the expression $\\log B(\\alpha, \\beta)$. We can *evaluate* that term for any $\\alpha$ and $\\beta$ we like (e.g., use `lbeta()` in R). But we cannot differentiate it and solve to find a closed-form solution (e.g., like we did for Bernoulli). Intractability is the usual situation; our first few tractable models are the exceptions.\n\n:::\n\n## Diagnose the Error {ref=\"diagnose-fnscale\"}\n\nA classmate estimates a Poisson rate $\\lambda$. Their code runs without an error or a warning:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny <- c(12, 7, 9, 12, 10)\n\nll_pois <- function(par, y) {\n  sum(dpois(y, lambda = par, log = TRUE))\n}\n\nest <- optim(par = 1,\n             fn = ll_pois,\n             y = y,\n             method = \"Brent\",\n             lower = 0.001, upper = 100)\nest$par\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 100\n```\n\n\n:::\n:::\n\n\nBut the estimate is absurd. The average of `y` is 10, but $\\hat{\\lambda} = 100$. What went wrong? How can they fix the code? What is the *category* of the mistake: a typo, an algebra error, or something else?\n\n::: hint\n\nWhen you hand `optim()` a function, what does it do by default: maximize or minimize? See the Details section of `?optim`.\n\n:::\n\n::: sol\n\n`optim()` is a *minimizer* by default. By default, it looks for the \"minimum likelihood.\" We know that the Poisson log-likelihood always gets smaller as $\\lambda$ moves away from the average of `y`. The search \"climbed\" to the edge of the parameter space (i.e., [0.001 to 100]) and stopped.\n\nDon't read much into *which* bound `optim()` found. Our hill-climbing algorithms assume the function has a single interior minimum. In this case, the log-likelihood at `lower = 0.001` is actually even smaller than the log-likelihood at `upper = 100`, so `optim()` didn't even land on the smaller of the two endpoints. It just \"climbed\" downhill (in the wrong direction!) until it ran out of space.\n\nTo maximize, we need `control = list(fnscale = -1)`. This flips the function over by multiplying it by $-1$. This turns a minimizer into a maximizer.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nest <- optim(par = 1,\n             fn = ll_pois,\n             y = y,\n             control = list(fnscale = -1),\n             method = \"Brent\",\n             lower = 0.001, upper = 100)\nest$par\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10\n```\n\n\n:::\n:::\n\n\nNow $\\hat{\\lambda} = 10$, which matches the closed form.\n\nIt's not a typo and it's not algebra. The code computed exactly what it was told to compute. It is a misunderstanding of how the tool works. This is a dangerous category of error.\n\n:::\n\n## Trust It or Not? {ref=\"trust-optim\"}\n\nYour `optim()` call returns `$convergence = 1`, and `$par` equals the upper bound you supplied. Do you trust the estimate?\n\n::: hint\n\n`?optim`'s Value section documents every `$convergence` code.\n\n:::\n\n::: sol\n\nNo. `$convergence = 1` means the algorithm hit its iteration limit without converging (see `?optim`). Also, a parameter estimate sitting exactly on a boundary is a red flag.\n\n:::\n\n## An Unfamiliar Density {ref=\"unfamiliar-density\"}\n\nSuppose a random variable has pdf $f(x; \\theta) = \\theta x^{\\theta - 1}$ for $0 < x < 1$ and $\\theta > 0$, and suppose we collect $N$ iid observations $x = \\{x_1, x_2, \\ldots, x_N\\}$.^[This is Exercise 9 on p. 425 of DeGroot and Schervish's *Probability and Statistics*.] Find the ML estimator of $\\theta$.\n\n::: hint\n\nWhat steps did we use for the Bernoulli and the Poisson? Start the same way here. Write $L(\\theta)$ as a product over the observations.\n\n:::\n\n::: hint\n\nTake the log and then use the rules for logs to simplify. \n\nYou should end up with two terms: one involving $\\log \\theta$ and one involving $\\sum \\log x_i$.\n\n:::\n\n::: {.hint label=\"Self-check\"}\n\nYour formula and `optim()` must agree. For `x <- c(0.2, 0.5, 0.9)`, evaluate your $\\hat{\\theta}$ formula, then run the code below and compare.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(0.2, 0.5, 0.9)\n\nll_fn <- function(theta, x) {\n  sum(log(theta) + (theta - 1)*log(x))\n}\n\nest <- optim(par = 1,\n             fn = ll_fn,\n             x = x,\n             control = list(fnscale = -1),\n             method = \"Brent\",\n             lower = 0, upper = 100)\nest$par\n```\n:::\n\n\n:::\n\n::: sol\n\nFirst, write down the likelihood and simplify the product:\n\n$$\nL(\\theta) = \\prod_{i = 1}^N \\theta x_i^{\\theta - 1} = \\theta^N \\prod_{i = 1}^N x_i^{\\theta - 1}.\n$$\n\nSecond, take the log. The product becomes a sum. Use $\\log(a^b) = b \\log(a)$ to bring the exponent out front:\n\n$$\n\\log L(\\theta) = N \\log \\theta + (\\theta - 1) \\sum_{i = 1}^N \\log x_i.\n$$\n\nThird, differentiate with respect to $\\theta$:\n\n$$\n\\frac{d \\log L}{d\\theta} = \\frac{N}{\\theta} + \\sum_{i = 1}^N \\log x_i.\n$$\n\nFourth, set the derivative to zero, set $\\theta = \\hat{\\theta}$, and solve:\n\n$$\n\\hat{\\theta} = \\frac{N}{-\\sum_{i = 1}^N \\log x_i}.\n$$\n\nFor the self-check data, $\\hat{\\theta} = 3 / [-(\\log 0.2 + \\log 0.5 + \\log 0.9)] \\approx 1.246$, and `optim()` returns 1.246.\n\n:::\n\n# The Invariance Property\n\n## One Line of Invariance {ref=\"invariance-one-line\"}\n\nLet $\\hat{\\theta}$ be the ML estimate of $\\theta$. Suppose we are interested in $\\psi = \\theta^2$. What is the ML estimate of $\\psi$?\n\n::: hint\n\nThe notes have a chapter that describes how to turn an ML estimate of a parameter into an ML estimate of a function of that parameter without writing down a new likelihood.\n\n:::\n\n::: sol\n\nBy the invariance property, the ML estimate of a function of a parameter is the function of the ML estimate:\n\n$$\n\\hat{\\psi} = \\hat{\\theta}^2.\n$$\n\nThat's the whole answer, and the brevity is the point. We don't need to derive a new likelihood for $\\psi$.\n\nThis is a very powerful, useful property.\n\n:::\n\n## The Exponential Model {ref=\"exponential-model\"}\n\nThe exponential distribution has pdf $f(t; \\lambda) = \\lambda e^{-\\lambda t}$ for $t \\geq 0$ and $\\lambda > 0$. We might use the exponential distribution to model *durations*. A duration is the *time until an event*, such as the end of a coalition government.\n\na. Suppose we collect $N$ iid durations $t = \\{t_1, t_2, \\ldots, t_N\\}$. Find the ML estimator of $\\lambda$.\nb. The parameter $\\lambda$ is called the *rate*. The *mean* of the exponential distribution is $\\frac{1}{\\lambda}$.^[Showing this takes integration by parts; here we'll take it as known.] Find the ML estimator of the mean. \n\n::: {.hint label=\"For part (a)\"}\n\nThis is very similar to the derivation of the ML estimate of $\\lambda$ for the Poisson distribution, with one important difference. Be careful with your algebra!\n\n:::\n\n::: sol\n\n**Part (a)** \n\nFirst, write down the likelihood and simplify:\n\n$$\nL(\\lambda) = \\prod_{i = 1}^N \\lambda e^{-\\lambda t_i} = \\lambda^N e^{-\\lambda \\sum_{i = 1}^N t_i}.\n$$\n\nSecond, take the log. The product becomes a sum. Remember that $\\log e^u = u$:\n\n$$\n\\log L(\\lambda) = N \\log \\lambda - \\lambda \\sum_{i = 1}^N t_i.\n$$\n\nThird, differentiate:\n\n$$\n\\frac{d \\log L}{d\\lambda} = \\frac{N}{\\lambda} - \\sum_{i = 1}^N t_i.\n$$\n\nFourth, set the derivative to zero at $\\lambda = \\hat{\\lambda}$ and solve:\n\n$$\n\\hat{\\lambda} = \\frac{N}{\\sum_{i = 1}^N t_i} = \\frac{1}{\\text{avg}(t)}.\n$$\n\nThus, the ML estimator of the rate is the *reciprocal of* the average duration.\n\n**Part (b)** By the invariance property, the ML estimator of the mean $\\frac{1}{\\lambda}$ is\n\n$$\n\\widehat{\\text{mean}} = \\hat{\\mu} = \\frac{1}{\\hat{\\lambda}} = \\text{avg}(t).\n$$\n\nThe ML estimate of the mean duration is the average duration, which seems sensible!\n\n:::\n\n## Four Models, One Number {ref=\"four-models\"}\n\nSuppose you observe the binary outcome `y <- c(0, 1, 0, 1, 1, 1, 0)` and you want to estimate the *mean* of the distribution that generated it. Naturally, you'd model these data as Bernoulli and estimate $\\pi$. But suppose that instead you model these 0s and 1s with a *normal* distribution. What is your ML estimate of the mean? What if you use the Poisson? The exponential?\n\nComplete the table below. For each model, find the ML estimates of the parameters, then the estimate of the mean via the invariance property if needed. What do you notice? Explain.\n\n| Distribution | Parameter(s) | ML estimates | Estimate of the mean |\n|---|---|---|---|\n| Bernoulli | $\\pi$ | ?? | ?? |\n| Normal | $\\mu$, $\\sigma^2$ | ?? | ?? |\n| Poisson | $\\lambda$ | ?? | ?? |\n| Exponential | $\\lambda$ | ?? | ?? |\n\n::: sol\n\nHere's the completed table, for `y` with $\\text{avg}(y) = \\frac{4}{7} \\approx 0.571$.\n\n| Distribution | Parameter(s) | ML estimates | Estimate of the mean |\n|---|---|---|---|\n| Bernoulli | $\\pi$ | $\\hat{\\pi} = \\text{avg}(y) \\approx 0.571$ | $\\hat{\\pi} \\approx 0.571$ (no transformation needed: $E(Y) = \\pi$) |\n| Normal | $\\mu$, $\\sigma^2$ | $\\hat{\\mu} = \\text{avg}(y) \\approx 0.571$ and $\\hat{\\sigma}^2 = \\frac{\\sum (y_i - \\bar{y})^2}{N} \\approx 0.245$ | $\\hat{\\mu} \\approx 0.571$ |\n| Poisson | $\\lambda$ | $\\hat{\\lambda} = \\text{avg}(y) \\approx 0.571$ | $\\hat{\\lambda} \\approx 0.571$ ($E(Y) = \\lambda$) |\n| Exponential | $\\lambda$ | $\\hat{\\lambda} = \\frac{1}{\\text{avg}(y)} = 1.75$ | $\\frac{1}{\\hat{\\lambda}} = \\text{avg}(y) \\approx 0.571$ |\n\nNo matter which model we use, we obtain an *identical* estimate of the mean. Not the same in expectation. Not the same asymptotically. It's the exact same number, regardless of the model.\n\nAnd importantly, whatever properties one of these estimators has, the others share, because the estimates are identical. If one is consistent, all are consistent. If one is unbiased, all are unbiased.\n\nThe lesson is worth stating carefully: *the quality or usefulness of an estimator doesn't always depend on every part of the model being right.* The usefulness of a model often depends on *what quantity you're targeting*. These four models agree exactly about the mean of these data. \n\n(But, as [implied-sd]{.ex-ref} and the model-checking exercises below show, these models can disagree wildly about other important things.)\n\n:::\n\n## N or N − 1? {ref=\"n-or-nm1\"}\n\nR's `var(y)` is *not* the ML estimate of $\\sigma^2$ for a normal model. What's the difference between the two? Which one is bigger? And does the difference matter at $N = 10{,}000$? Check your answers numerically using some vector of data.\n\n::: hint\n\nThe notes derive the ML estimator for $\\sigma^2$ by solving $\\frac{d \\log L}{d \\sigma^2} = 0$. Find that derivation in the notes. What is the denominator? Compare it to the denominator for `var()`, which is explained deep in the Details of `?var`. \n\n:::\n\n::: {.hint label=\"Self-check\"}\n\nFor the numeric check, compute the sum of squared deviations from the mean. Then use the two alternative denominators. Compare each result to `var()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# pick any vector, e.g.:\ny <- rnorm(1000)\n\nvar(y)\n\n# your ML formula for sigma^2, using y directly (not from var(y))\n```\n:::\n\n\n:::\n\n::: sol\n\n`var()` divides the sum of squared deviations by $N - 1$ (the classic, unbiased estimator). The ML estimator divides by $N$ (see the notes), so `var()` is larger by a factor of $\\frac{N}{N-1}$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\ny <- rnorm(10000, mean = 5, sd = 2)\n\nvar(y)                             # divides by N - 1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.099462\n```\n\n\n:::\n\n```{.r .cell-code}\nsum((y - mean(y))^2) / length(y)   # ml estimate: divides by N\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.099052\n```\n\n\n:::\n:::\n\n\nAt $N = 10{,}000$ the two differ in the fourth decimal, which is practically nothing. But the conceptual distinction is important. They are different estimators, derived from different principles. And at small $N$, the difference is sometimes visible.\n\n:::\n\n## The SD the Model Implies {ref=\"implied-sd\"}\n\nHolland (2015) measures the number of enforcement operations (i.e., a \"count\") against street vendors across districts in three Latin American cities. The data are in `crdata::holland2015`.^[`crdata` isn't on CRAN. Install it once with `remotes::install_github(\"carlislerainey/crdata\")`.] The notes use the Poisson model and estimate the mean $\\lambda$ separately for each city. Now let's estimate the standard deviation of the number of operations (rather than the mean).\n\na. What does the Poisson model *assume* about the SD of the data, in terms of $\\lambda$?\nb. Use the invariance property to estimate the SD of the operations counts in each city from $\\hat{\\lambda}$.\nc. Compute the observed sample SD in each city and compare (i.e., use `sd()`). What do you find? Why is this interesting or important?\n\n::: {.hint label=\"For parts (a) and (b)\"}\n\nFor a Poisson distribution, how is the variance related to the mean? Write the SD as a function of $\\lambda$, then estimate it by plugging in $\\hat{\\lambda}$.\n\nThe [distributions appendix](https://pos5747.github.io/notes/appendicies/999-distributions.html#poisson-distribution) has the answer.\n\n:::\n\n::: {.hint label=\"For part (c)\"}\n\nYou already grouped the operations counts by city to compute $\\hat{\\lambda}$ in part (b). Apply that same grouping here, and compute each city's sample SD with `sd()`.\n\n:::\n\n::: sol\n\n**Part (a)** Recall that the Poisson has $\\text{Var}(Y) = E(Y) = \\lambda$, so the model assumes the SD is $\\sqrt{\\lambda}$. In this case, the spread is *determined by* the mean. The variance and the mean have no freedom to differ.\n\n**Parts (b) and (c)** By the invariance property, we estimate the SD with $\\widehat{\\text{SD}} = \\sqrt{\\hat{\\lambda}}$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load holland's data\nholland2015 <- crdata::holland2015\n\nholland2015 |>\n  group_by(city) |>\n  summarize(lambda_hat = mean(operations),\n            sd_implied = sqrt(lambda_hat),\n            sd_sample  = sd(operations))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  city     lambda_hat sd_implied sd_sample\n  <chr>         <dbl>      <dbl>     <dbl>\n1 bogota         8.89       2.98      6.94\n2 lima          23.2        4.82     18.8 \n3 santiago       2.71       1.64      4.94\n```\n\n\n:::\n:::\n\n\nFor every city, the sample SDs are roughly two to four times the model SDs (Santiago 4.9 vs. 1.6; Bogotá 6.9 vs. 3.0; Lima 18.8 vs. 4.8). These counts are far more dispersed than a Poisson allows. This is called *overdispersion*, and it's almost always present in count data.\n\nNotice what kind of failure this is. Nothing is wrong with $\\sqrt{\\hat{\\lambda}}$ as an estimate of *the model's* SD. Invariance did its job. The problem lies with the model. The Poisson assumes a particular relationship between the SD and the mean. These data are inconsistent with that assumed relationship. The predictive-distribution chapter shows this mismatch in detail for Lima.\n\n:::\n\n# When the Recipe Fails\n\n## The Discrete Uniform {ref=\"discrete-uniform\"}\n\nSuppose a discrete uniform distribution on $\\{0, 1, \\ldots, K\\}$, with pmf $f(x; K) = \\frac{1}{K + 1}$ for $x \\in \\{0, 1, \\ldots, K\\}$. Suppose we observe a sample of size 3: 276, 159, and 912.\n\na. Find the ML estimate of $K$. *Hint: The likelihood is discontinuous in $K$, so differentiate-and-solve will mislead you. But the maximum is immediately apparent once you write out the likelihood. Use a verbal, logical argument here, rather than the usual recipe.*\nb. Find the method of moments estimate of $K$. *Hint: The mean of this distribution is $\\tfrac{K}{2}$. Set the sample mean equal to the model mean and solve.*\nc. For these data, the method of moments estimate falls below the largest observation. This is unsatisfying because the data themselves rule out that estimate of $K$ as impossible. This raises the question: how bad can this get? Construct a three-observation dataset that makes the ratio $\\hat{K}_{MM} / \\max(x)$ as small as you can. What is the smallest value the ratio can take with three observations?\nd. In a sentence or two, describe what these two failures teach us about choosing an estimator.\n\n::: {.hint label=\"For part (c)\"}\n\nYou are minimizing the ratio $2 \\cdot \\text{avg}(x) / \\max(x)$ (i.e., part (b)'s formula divided by the largest observation). $\\max(x)$ is fixed, so which direction should you push the other two observations to shrink the average?\n\n:::\n\n::: sol\n\n**Part (a)** The likelihood is\n\n$$\nL(K) = \\prod_{i=1}^N \\frac{1}{K+1} = \\left(\\frac{1}{K+1}\\right)^N\n$$\n\nif every observation lies in $\\{0, 1, \\ldots, K\\}$, and $0$ if *any* observation exceeds $K$. This function is not differentiable, so the recipe isn't useful. Notice that making $K$ smaller makes each data point more likely, until we've made $K$ too small. So to make $L(K)$ as large as possible, we make $K$ as small as the data allow. That's $\\hat{K}_{ML} = \\max(x) = 912$.\n\n**Part (b)** Set the sample mean equal to the model mean, $\\text{avg}(x) = \\frac{\\hat{K}_{MM}}{2}$. Then, solving for $\\hat{K}_{MM}$ gives $\\hat{K}_{MM} = 2 \\cdot \\text{avg}(x) = 2 \\cdot 449 = 898$.\n\n**Part (c)** We want $2 \\cdot \\text{avg}(x)$ small while $\\max(x)$ stays large, so push the other two observations as low as they can go, which is $x = (0, 0, 912)$. Then $\\text{avg}(x) = 304$, $\\hat{K}_{MM} = 608$, and the ratio is $608/912 = \\tfrac{2}{3}$. This means that $\\tfrac{2}{3}$ is the smallest possible ratio. With three observations, $\\text{avg}(x) \\geq \\frac{\\max(x)}{3}$.\n\n$$\n\\hat{K}_{MM} = 2 \\cdot \\text{avg}(x) \\;\\geq\\; \\frac{2}{3}\\max(x).\n$$\n\n**Part (d)** Both estimators \"work\" in the sense that the procedure produces a number. But each misbehaves differently. The ML estimate is the smallest *logically possible* value of $K$, which intuition says is probably too low. And the method of moments can produce values of $K$ the data have already contradicted.\n\nThese diverging misbehaviors make this problem useful for thinking about how we evaluate models (a little later in the course), so remember this problem.\n\n:::\n\n# Checking the Model\n\n## The Remaining Wait {ref=\"memorylessness\"}\n\nThe exponential distribution from [exponential-model]{.ex-ref} is our first model for durations. However, this model makes a simple assumption about wait times that turns out to be really interesting and important!\n\na. Show that the cdf of the exponential distribution is $F(t; \\lambda) = \\Pr(T \\leq t) = 1 - e^{-\\lambda t}$. Then define the *survival function* $S(t; \\lambda) = \\Pr(T > t) = 1 - F(t; \\lambda)$ and interpret it (i.e., for an input $t$, what does $S$ return)?\nb. Suppose you've already waited $s$ units of time without the event occurring. Using the definition of conditional probability and the survival function, find $\\Pr(T > t + s \\mid T > s)$. Compare your answer to $\\Pr(T > t)$. What do you notice? Write it down in one sentence *before* you start part (c).\nc. Now check your sentence against a simulation. The code below draws 10,000 durations and computes, *for the draws that lasted past time 2*, how much *longer* they lasted.\n\n    ```r\n    set.seed(123)\n    durations <- rexp(10000, rate = 1)\n    remaining <- durations[durations > 2] - 2\n    ```\n\n    Compare the distribution of `remaining` to the distribution of the original `durations` (plotting both ECDFs in one panel works well). Do the plots confirm or refute your sentence from (b)?\nd. Name one political process that your finding might describe well, and one that it might not. Explain.\n\n::: {.hint label=\"For part (a)\"}\n\nThe cdf accumulates the density: $F(t; \\lambda) = \\int_0^t \\lambda e^{-\\lambda u}\\, du$. Use integration rules from Week 1.\n\n:::\n\n::: {.hint label=\"For part (b)\"}\n\nWhat is the event \"$T > t + s$ *and* $T > s$\"? Notice that one of the two conditions implies the other.\n\n:::\n\n::: {.hint label=\"For part (b), a second nudge\"}\n\nWrite the conditional probability as a ratio of survival functions and substitute $S(t; \\lambda) = e^{-\\lambda t}$.\n\n:::\n\n::: sol\n\n**Part (a)** Integrate the pdf from $0$ to $t$:\n\n$$\nF(t; \\lambda) = \\int_0^t \\lambda e^{-\\lambda u}\\, du = \\lambda \\left[ \\frac{-1}{\\lambda} e^{-\\lambda u} \\right]_0^t = -e^{-\\lambda t} + e^{0} = 1 - e^{-\\lambda t}.\n$$\n\nSubtracting from one, we obtain the survival function:\n\n$$\nS(t; \\lambda) = \\Pr(T > t) = e^{-\\lambda t}.\n$$\n\n$S$ returns the probability that the event *has not yet occurred* by time $t$. (The cdf returns the probability that it *has*.) If $t = 3$ years and $S(3; \\lambda) = 0.20$, there's a 20% chance the event happens after year three.\n\n**Part (b)** The key step: when $T > t + s$, then $T > s$ automatically, so the joint event is just $T > t + s$. By the definition of conditional probability,\n\n$$\n\\Pr(T > t + s \\mid T > s) = \\frac{\\Pr(T > t + s)}{\\Pr(T > s)} = \\frac{e^{-\\lambda (t + s)}}{e^{-\\lambda s}} = e^{-\\lambda t} = \\Pr(T > t).\n$$\n\nNotice that the $s$ cancels! Thus, the two are exactly the same. **This is important**: *the probability of waiting at least $t$ more units of time doesn't depend on how long you've already waited.* This is the **memoryless property**. The exponential is the *only* continuous distribution that has this property.\n\n**Part (c)** Here $s = 2$. The vector `remaining` holds the remaining durations of the draws that made it past time 2. This makes `remaining` a sample from the distribution of $T - s$ given $T > s$. Plotting its ECDF over the ECDF of the original `durations` allows us to check part (b)'s claim.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\ndurations <- rexp(10000, rate = 1)\nremaining <- durations[durations > 2] - 2\n\n# stack the two sets of durations into one tidy data frame\ndf <- bind_rows(\n  data.frame(duration = durations, type = \"original\"),\n  data.frame(duration = remaining, type = \"remaining\")\n)\n\n# compare the two ecdfs in a single panel\nggplot(df, aes(x = duration, color = type)) +\n  stat_ecdf()\n```\n\n::: {.cell-output-display}\n![](wk02-exercises-sol_files/figure-html/ex15-solution-1.png){width=672}\n:::\n:::\n\n\nThe two ECDFs sit right on top of each other! Of the 10,000 draws, only 1353 survived past time 2, so the `remaining` curve uses less data and wiggles around a little more.\n\n**Part (d)** The property is perhaps plausible for wait times \"with no internal clock,\" such as the time between militarized disputes in a region or between filibusters in a session. (Below, [hockey]{.ex-ref} looks at the time between hits in a hockey game.) Memorylessness fails for cabinet duration, the example mentioned back in [exponential-model]{.ex-ref}. If I ask how much longer a coalition will last, you'd definitely want to know how long it has lasted already. Human lifespans are similar. If I asked how much longer a person will live, you'd definitely want to know how old that person is now.\n\n:::\n\n## Herron's Hockey Data {ref=\"hockey\"}\n\nHerron's hockey data set records the time between hits[^hit] in the regulation periods of all 82 regular-season games for the Chicago Blackhawks.\n\n[^hit]: From [Wikipedia](https://en.wikipedia.org/wiki/Ice_hockey_statistics), a hit is: *\"Intentionally initiated contact with the player possessing the puck that causes that player to lose possession of the puck.\"*\n\nBefore looking at the data, do you expect an exponential model to fit the times between hits? Do you expect memorylessness to work well here? Write down your prediction and your reasoning. It could be that hits cluster together (i.e., a hit sparks retaliation). Or maybe a long lull makes the next hit increasingly likely.\n\nModel `seconds_btw_hits` as exponential, estimate the rate and the mean, and use the predictive distribution to evaluate the fit. Were you right?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load data directly from the web\nhockey <- read_csv(\"https://gist.githubusercontent.com/carlislerainey/0bc3018cd2377022fd045e1c932110a2/raw/fd6dcc28a7c0df456d779e9f0d7a82f15b9b5844/herron-hockey.csv\")\n\n# quick look\nglimpse(hockey)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,175\nColumns: 5\n$ game_id                  <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, …\n$ period_id                <dbl> 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 2, …\n$ time_of_hit              <chr> \"25S\", \"2M 8S\", \"2M 58S\", \"3M 8S\", \"4M 13S\", …\n$ seconds_played_in_season <dbl> 25, 128, 178, 188, 253, 560, 643, 1407, 1825,…\n$ seconds_btw_hits         <dbl> NA, 103, 50, 10, 65, 307, 83, 764, 418, 535, …\n```\n\n\n:::\n:::\n\n\n::: hint\n\nThe general recipe for the predictive distribution is in the notes and it works for any fitted distribution. You've already derived a formula for $\\hat{\\lambda}$ in [exponential-model]{.ex-ref}. Get that estimate from the data. Then simulate fake data as we do in the notes.\n\n:::\n\n\n::: sol\n\nFirst obtain the estimates using $\\hat{\\lambda} = 1/\\text{avg}(t)$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# drop the one missing value (the season's first hit has no predecessor)\ny <- na.omit(hockey$seconds_btw_hits)\n\n# ml estimates of the rate and the mean\nlambda_hat <- 1/mean(y)\nlambda_hat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.003980079\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(y)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 251.2513\n```\n\n\n:::\n:::\n\n\nThe mean time between hits is about 251 seconds (a hit every four minutes or so), which makes the rate $\\hat{\\lambda} \\approx 0.004$ hits per second.\n\nNow do the predictive check:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create observed data set\nobserved_data <- tibble(seconds_btw_hits = y, type = \"observed\")\n\n# simulate five fake data sets\nset.seed(1917)\nn <- length(y)\nsim_list <- list()\nfor (i in 1:5) {\n  y_pred <- rexp(n, rate = lambda_hat)\n  sim_list[[i]] <- tibble(seconds_btw_hits = y_pred,\n                          type = paste0(\"simulated #\", i))\n}\n\n# combine the fake and observed data sets\ngg_data <- bind_rows(sim_list) |>\n  bind_rows(observed_data)\n\n# plot the observed and fake data sets\nggplot(gg_data, aes(x = seconds_btw_hits)) +\n  geom_histogram(bins = 30) +\n  facet_wrap(vars(type))\n```\n\n::: {.cell-output-display}\n![](wk02-exercises-sol_files/figure-html/ex16-check-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# a sharper comparison: all the ecdfs in one panel\ngg_data2 <- gg_data |>\n  separate(type, into = c(\"type\", \"version\"))\n\nggplot(gg_data2, aes(x = seconds_btw_hits, color = type, group = version)) +\n  stat_ecdf()\n```\n\n::: {.cell-output-display}\n![](wk02-exercises-sol_files/figure-html/ex16-ecdf-1.png){width=672}\n:::\n:::\n\n\nThese distributions look *very* similar. The observed ECDF hides among the ECDFs for the simulated data. \n\nThe exponential fits! This is perhaps substantively surprising. In sports, we talk constantly about momentum, big swings, retaliation, tension building. If any of that mattered for hits, the time since the last hit would predict the time to the next one, but the distribution of hits seems memoryless.\n\n:::\n\n## Heavy Tails: GDP Growth and the Location-Scale *t* {ref=\"t-model\"}\n\nThe location-scale *t* distribution is a flexible model for data with heavier-than-normal tails (i.e., more extreme observations than a normal model expects). Its pdf is\n\n$$\nf(y; \\mu, \\sigma, \\nu) = \\frac{\\Gamma\\left(\\frac{\\nu+1}{2}\\right)}{\\Gamma\\left(\\frac{\\nu}{2}\\right) \\sqrt{\\nu \\pi} \\, \\sigma} \\left[1 + \\frac{1}{\\nu} \\left( \\frac{y - \\mu}{\\sigma} \\right)^2 \\right]^{-\\frac{\\nu+1}{2}},\n$$\n\nwhere $\\mu$ is the location parameter (it shifts the distribution, like the normal's mean), $\\sigma$ is the scale parameter (it spreads the distribution, like the normal's SD), and $\\nu$ controls the heaviness of the tails. The $\\mu$ and $\\sigma$ work similarly to a normal model. Small $\\nu$ means heavy tails, and as $\\nu \\to \\infty$ the distribution converges to the normal. (For $\\nu > 10$ or so, the $t$ and the normal distributions are hard to tell apart, and $\\nu = 1$ is the Cauchy.)\n\nWe can use `metRology::dt.scaled()` to compute this density in R.^[`metRology` is on CRAN: `install.packages(\"metRology\")`.] Be careful with the argument names in `metRology::dt.scaled()`. `mean` is the location $\\mu$ (though $\\mu$ isn't always a mean), `sd` is the scale $\\sigma$ (though $\\sigma$ isn't the SD), and `df` is $\\nu$.\n\nWe'll model cross-national GDP growth, which mixes a tight cluster of ordinary economies with a few extreme performers. The code below downloads percentage GDP growth for 2022 from the World Bank.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load package\nlibrary(WDI)\n\n# get annual % gdp growth for 2022\n# - \"NY.GDP.MKTP.KD.ZG\" is percentage gdp growth\n#   see https://data.worldbank.org/indicator/NY.GDP.MKTP.KD.ZG\ndf <- WDI(indicator = \"NY.GDP.MKTP.KD.ZG\",\n          start = 2022,\n          end = 2022,\n          extra = TRUE) %>%\n  # drop aggregates (e.g., European Union)\n  filter(region != \"Aggregates\") %>%\n  mutate(pct_gdp_growth = NY.GDP.MKTP.KD.ZG) %>%\n  select(country, year, region, pct_gdp_growth) %>%\n  na.omit()\n\n# plot histogram\nggplot(df, aes(x = pct_gdp_growth)) +\n  geom_histogram(bins = 40)\n```\n\n::: {.cell-output-display}\n![](wk02-exercises-sol_files/figure-html/ex17-data-1.png){width=672}\n:::\n:::\n\n\na. As a baseline, model `pct_gdp_growth` with a normal distribution. Estimate $\\mu$ and $\\sigma$ by ML (both have closed forms), then use the predictive distribution to assess the fit. What does the normal model miss?\nb. Now fit the location-scale *t*, estimating $\\mu$, $\\sigma$, and $\\nu$ with `optim()`. Complete the skeleton below by filling in the two blanked lines.\n\n    ```r\n    ll_t <- function(par, y) {\n      # unpack the parameter vector\n      mu    <- par[1]   # location\n      sigma <- par[2]   # scale\n      nu    <- par[3]   # degrees of freedom (tail heaviness)\n\n      # 1. guard: impossible parameter values should return -Inf\n      #    ... your code here ...\n\n      # 2. compute the log-likelihood with metRology::dt.scaled()\n      #    ll <- ... your code here ...\n\n      return(ll)\n    }\n    ```\n\n    Reasonable starting values are `c(median(y), sd(y), 10)`.\nc. Use the predictive distribution to compare the *t* model to the normal model. How does the predictive distribution from the *t* compare to the normal? What is the ML estimate of $\\nu$, and why might that matter?\n\n::: {.hint label=\"For part (b)\"}\n\nThe density is undefined when the scale or the tail parameter is zero or negative. If `sigma` or `nu` is not positive, return `-Inf`; otherwise return `sum(dt.scaled(y, mean = mu, sd = sigma, df = nu, log = TRUE))`.\n\n\n:::\n\n\n::: sol\n\n**Part (a)** The normal ML estimates have closed forms, so no optimizer is needed:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# save the variable as y to simplify the code\ny <- df$pct_gdp_growth\nn <- length(y)\n\n# ml estimates for the normal model\nmu_hat <- mean(y)\nsigma_hat <- sqrt(sum((y - mu_hat)^2)/n)\nc(mu_hat = mu_hat, sigma_hat = sigma_hat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   mu_hat sigma_hat \n 4.418957  6.766710 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# predictive check for the normal model\nobserved_data <- tibble(pct_gdp_growth = y, type = \"observed\")\n\nset.seed(2026)\nsim_list <- list()\nfor (i in 1:5) {\n  y_pred <- rnorm(n, mean = mu_hat, sd = sigma_hat)\n  sim_list[[i]] <- tibble(pct_gdp_growth = y_pred,\n                          type = paste0(\"simulated #\", i))\n}\n\ngg_data <- bind_rows(sim_list) |>\n  bind_rows(observed_data)\n\nggplot(gg_data, aes(x = pct_gdp_growth)) +\n  geom_histogram(bins = 40) +\n  facet_wrap(vars(type))\n```\n\n::: {.cell-output-display}\n![](wk02-exercises-sol_files/figure-html/ex17-normal-check-1.png){width=672}\n:::\n:::\n\n\nThe normal model misses in two directions at once. To accommodate the handful of extreme observations, it needs a large SD (about 6.8 here). But that large SD forces the simulated data sets to spread out, so they show too little of the tight clustering around the average that the observed data have, and still none of the truly extreme values. The observed panel has a sharper peak *and* wilder outliers than any simulated panel.\n\n**Part (b)** The completed skeleton:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load package\nlibrary(metRology)  # for dt.scaled()\n\n# log-likelihood for the location-scale t\nll_t <- function(par, y) {\n  # unpack the parameter vector\n  mu    <- par[1]   # location\n  sigma <- par[2]   # scale\n  nu    <- par[3]   # degrees of freedom (tail heaviness)\n\n  # 1. guard: impossible parameters get -Inf, so optim() walks away\n  if (sigma <= 0 | nu <= 0) return(-Inf)\n\n  # 2. compute the log-likelihood\n  ll <- sum(dt.scaled(y, mean = mu, sd = sigma, df = nu, log = TRUE))\n\n  return(ll)\n}\n\n# maximize\nest <- optim(par = c(median(y), sd(y), 10),\n             fn = ll_t,\n             y = y,\n             control = list(fnscale = -1),\n             method = \"Nelder-Mead\")\nest$convergence\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nest$par\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.379386 2.561957 1.884743\n```\n\n\n:::\n:::\n\n\n\n**Part (c)** The predictive check for the *t* model:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2027)\nsim_list <- list()\nfor (i in 1:5) {\n  y_pred <- rt.scaled(n, mean = est$par[1], sd = est$par[2], df = est$par[3])\n  sim_list[[i]] <- tibble(pct_gdp_growth = y_pred,\n                          type = paste0(\"simulated #\", i))\n}\n\ngg_data <- bind_rows(sim_list) |>\n  bind_rows(observed_data)\n\nggplot(gg_data, aes(x = pct_gdp_growth)) +\n  geom_histogram(bins = 40) +\n  facet_wrap(vars(type))\n```\n\n::: {.cell-output-display}\n![](wk02-exercises-sol_files/figure-html/ex17-t-check-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# the ecdf overlay for a sharper comparison\ngg_data2 <- gg_data |>\n  separate(type, into = c(\"type\", \"version\"))\n\nggplot(gg_data2, aes(x = pct_gdp_growth, color = type, group = version)) +\n  stat_ecdf()\n```\n\n::: {.cell-output-display}\n![](wk02-exercises-sol_files/figure-html/ex17-t-ecdf-1.png){width=672}\n:::\n:::\n\n\nThe fitted *t* distributions match the observed data far better than the normal model. The simulated panels now show the tight central cluster *and* occasional extreme values. In the ECDF overlay, the observed curve is hard to pick out.\n\nThe estimate of the degrees of freedom is $\\hat{\\nu} \\approx 1.9$. This means that these data have extremely heavy tails (almost a Cauchy). Of note: A $t$ has a finite variance only when $\\nu > 2$, so the variance does not exist for the fitted model. \n\n$\\nu$ gives us a third parameter that separates \"how spread out is the middle?\" ($\\sigma \\approx 2.6$, against the normal's inflated 6.8) from \"how common are extreme values?\". With the tails handled by $\\nu$, the scale can describe the typical countries.\n\n:::\n\n# Reflection\n\n## What Should a Model Match? {ref=\"reflection\"}\n\nThe exercises above repeatedly compare a fitted model against observed data, and the models often disagree with the data about everything *except* the mean. \n\nAnswer these three questions in a few sentences each:\n\na. Is it important that a model mimic features of the data beyond the mean?\nb. When might the SD, the tails, or the behavior of wait times matter *substantively*?\nc. When might those features matter *statistically* (even if the mean is all you care about)?\n\n::: {.hint label=\"For part (a)\"}\n\nSee [four-models]{.ex-ref} for an example.\n\n:::\n\n::: sol\n\nThere's no single right answer here. But here are a few thoughts:\n\n**(a)** It depends on the target. [four-models]{.ex-ref} showed four wildly different models agreeing exactly about the mean. So for estimating a mean, mimicry beyond the mean can be surprisingly optional. \n\n**(b)** Your question might ask about more than the center. If you care about the *chance of an extreme outcome* (a deep recession, an unusually long stretch without a coup), the tails matter substantively. If you care about *how long until an event, given the wait so far*, the memory structure is the substance. If you care about variability, then the scale or SD might matter most. A normal model of GDP growth answers tail questions badly even though its mean is fine.\n\n**(c)** Looking ahead, standard errors depend on more of the distribution than its center. A model whose spread or tails are wrong can deliver a fine point estimate with badly wrong uncertainty.\n\n:::\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}