<!DOCTYPE html>
<html lang="en"><head>
<script src="wk09-slides_files/libs/clipboard/clipboard.min.js"></script>
<script src="wk09-slides_files/libs/quarto-html/tabby.min.js"></script>
<script src="wk09-slides_files/libs/quarto-html/popper.min.js"></script>
<script src="wk09-slides_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="wk09-slides_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="wk09-slides_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="wk09-slides_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.6.42">

  <title>Hierarchical Models</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="wk09-slides_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="wk09-slides_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="wk09-slides_files/libs/revealjs/dist/theme/quarto-2f366650f320edcfcf53d73c80250a32.css">
  <link rel="stylesheet" href="styles.css">
  <link href="wk09-slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="wk09-slides_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="wk09-slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="wk09-slides_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Hierarchical Models</h1>

<div class="quarto-title-authors">
</div>

</section>
<section>
<section id="opening-comments" class="title-slide slide level1 center">
<h1>Opening Comments</h1>
<ul>
<li>Exam</li>
<li>Workshop</li>
<li>Paper</li>
</ul>
</section>
<section class="slide level2">

<p>Here are the packages we’re using:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href=""></a><span class="co"># generally useful packages</span></span>
<span id="cb1-2"><a href=""></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href=""></a><span class="fu">library</span>(marginaleffects)</span>
<span id="cb1-4"><a href=""></a><span class="fu">library</span>(modelsummary)</span>
<span id="cb1-5"><a href=""></a></span>
<span id="cb1-6"><a href=""></a><span class="co"># for fitting hierarchical models</span></span>
<span id="cb1-7"><a href=""></a><span class="fu">library</span>(lme4)</span>
<span id="cb1-8"><a href=""></a><span class="fu">library</span>(brms)  <span class="co"># see also rstanarm::stan_lmer()</span></span>
<span id="cb1-9"><a href=""></a></span>
<span id="cb1-10"><a href=""></a><span class="co"># for post-processing simulations</span></span>
<span id="cb1-11"><a href=""></a><span class="fu">library</span>(tidybayes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="where-were-headed" class="slide level2">
<h2>Where we’re headed</h2>
<p>This week, I introduce the idea of a hierarchical model.</p>
<p>These fall squarely within our probability modeling framework—but with an exciting new twist.</p>
<p>Before: <span class="math inline">\(x_i \sim f(x_i; \theta)\)</span></p>
<p>Now: <span class="math inline">\(x_i \sim f(x_i; \theta_{j[i]})\)</span>, where <span class="math inline">\(\theta_j \sim f(\theta_j; \phi)\)</span></p>
<p>We have models of parameters <span class="math inline">\(\theta_j \sim f(\theta_j; \phi)\)</span> analogous to a previous models of data.</p>
</section></section>
<section>
<section id="contact-in-finland" class="title-slide slide level1 center">
<h1>Contact in Finland</h1>
<p>In my dissertation, I was interested in how survey self-reports of <strong>being contacted</strong> by a political party varies across electoral districts.</p>
<p>You can see <a href="http://www.carlislerainey.com/papers/stratmob.pdf">here</a> for the details.</p>
</section>
<section id="the-finland-data" class="slide level2">
<h2>The <code>finland</code> data</h2>
<p>For now, let’s just estimate the proportion of people in each district that are contacted by a party.</p>
<p>Let’s start with Finland.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href=""></a><span class="co"># load data</span></span>
<span id="cb2-2"><a href=""></a>finland <span class="ot">&lt;-</span> crdata<span class="sc">::</span>finland <span class="sc">|&gt;</span></span>
<span id="cb2-3"><a href=""></a>  <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1,086
Columns: 2
$ district_id &lt;chr&gt; "District 313", "District 313", "District 310", "District 304", "Dis…
$ contacted   &lt;fct&gt; Not Contacted, Contacted, Not Contacted, Contacted, Not Contacted, N…</code></pre>
</div>
</div>
<p>It will be convenient in later steps to have <code>contacted</code> be an indicator and <code>district_id</code> be a nice factor, so let’s do that now.</p>
<ol type="1">
<li>Remove “District” from the strings.</li>
<li><code>reorder()</code> the levels by the average of <code>contacted</code>. (Important sneaky trick).</li>
</ol>
</section>
<section id="the-finland-data-tidied-up" class="slide level2">
<h2>The <code>finland</code> data, tidied up</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href=""></a><span class="co"># load data</span></span>
<span id="cb4-2"><a href=""></a>finland <span class="ot">&lt;-</span> crdata<span class="sc">::</span>finland <span class="sc">|&gt;</span></span>
<span id="cb4-3"><a href=""></a>  <span class="co"># make contacted an indicator</span></span>
<span id="cb4-4"><a href=""></a>  <span class="fu">mutate</span>(<span class="at">contacted =</span> <span class="fu">as.numeric</span>(contacted <span class="sc">==</span> <span class="st">"Contacted"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb4-5"><a href=""></a>  <span class="co"># mutate district_id to factor ordered by contact rate</span></span>
<span id="cb4-6"><a href=""></a>  <span class="fu">mutate</span>(<span class="at">district_id =</span> <span class="fu">str_remove</span>(district_id, <span class="st">"District "</span>),</span>
<span id="cb4-7"><a href=""></a>         <span class="at">district_id =</span> <span class="fu">reorder</span>(district_id, contacted)) <span class="sc">|&gt;</span></span>
<span id="cb4-8"><a href=""></a>  <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1,086
Columns: 2
$ district_id &lt;fct&gt; 313, 313, 310, 304, 304, 304, 304, 304, 304, 304, 304, 304, 304, 304…
$ contacted   &lt;dbl&gt; 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,…</code></pre>
</div>
</div>
</section>
<section id="always-scatterplot-your-data" class="slide level2">
<h2>Always scatterplot your data</h2>
<p>A scatterplot is a safe and potentially informative way to start.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href=""></a>gg1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(finland, <span class="fu">aes</span>(<span class="at">x =</span> district_id, <span class="at">y =</span> contacted)) <span class="sc">+</span> </span>
<span id="cb6-2"><a href=""></a>  <span class="fu">geom_jitter</span>(<span class="at">shape =</span> <span class="dv">21</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">1</span>)</span>
<span id="cb6-3"><a href=""></a><span class="fu">print</span>(gg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>

</div>
<img data-src="wk09-slides_files/figure-revealjs/unnamed-chunk-5-1.png" width="768" class="r-stretch"></section>
<section id="model-part-1" class="slide level2">
<h2>Model, part 1</h2>
<p>Now let’s estimate the probability of being contacted by a political party in each district.</p>
<p>Start by writing down a probability model for being contacted. This is a binary outcome, so if we’re going to assume (conditional) independence, it must be Bernoulli.</p>
<p><span class="math display">\[
\text{Contacted}_i \sim \text{Bernoulli}(\pi_j),
\]</span></p>
<p>where <span class="math inline">\(i\)</span> indexes the respondent and <span class="math inline">\(j\)</span> indexes the electoral district.</p>
<p>Remember that the ML estimate of <span class="math inline">\(\pi\)</span> is just the sample mean (or sample proportion).</p>
</section>
<section id="estimating-pi_j-a-crude-first-cut" class="slide level2">
<h2>Estimating <span class="math inline">\(\pi_j\)</span>: a crude first cut</h2>
<p>We can do this easily for each district with <code>group_by()</code> and <code>summarize()</code>.</p>
<p>Let’s also add an estimate of the standard error using <span class="math inline">\(\widehat{\text{SE}}(\hat{\pi}_j) = \frac{\sqrt{\hat{\pi}_j(1 - \hat{\pi}_j)}}{\sqrt{n}}\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href=""></a>estimates <span class="ot">&lt;-</span> finland <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href=""></a>  <span class="fu">group_by</span>(district_id) <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href=""></a>  <span class="fu">summarize</span>(<span class="at">pi_hat =</span> <span class="fu">mean</span>(contacted),</span>
<span id="cb7-4"><a href=""></a>            <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb7-5"><a href=""></a>            <span class="at">se_hat =</span> <span class="fu">sqrt</span>(pi_hat<span class="sc">*</span>(<span class="dv">1</span> <span class="sc">-</span> pi_hat))<span class="sc">/</span><span class="fu">sqrt</span>(n)) <span class="sc">%&gt;%</span></span>
<span id="cb7-6"><a href=""></a>  <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 14
Columns: 4
$ district_id &lt;fct&gt; 312, 315, 316, 305, 310, 306, 311, 304, 317, 307, 314, 313, 308, 309
$ pi_hat      &lt;dbl&gt; 0.0862, 0.0909, 0.1250, 0.1500, 0.1620, 0.1707, 0.1818, 0.2288, 0.22…
$ n           &lt;int&gt; 58, 44, 40, 40, 179, 41, 88, 153, 61, 105, 103, 65, 86, 23
$ se_hat      &lt;dbl&gt; 0.0369, 0.0433, 0.0523, 0.0565, 0.0275, 0.0588, 0.0411, 0.0340, 0.05…</code></pre>
</div>
</div>
</section>
<section id="adding-the-estimates-to-the-scatterplot" class="slide level2">
<h2>Adding the estimates to the scatterplot</h2>
<p>Now let’s add these estimates to the scatterplot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href=""></a>gg2 <span class="ot">&lt;-</span> gg1 <span class="sc">+</span> </span>
<span id="cb9-2"><a href=""></a>  <span class="fu">geom_errorbar</span>(<span class="at">data =</span> estimates, <span class="fu">aes</span>(<span class="at">ymin =</span> pi_hat <span class="sc">-</span> <span class="fl">1.64</span><span class="sc">*</span>se_hat,</span>
<span id="cb9-3"><a href=""></a>                                      <span class="at">ymax =</span> pi_hat <span class="sc">+</span> <span class="fl">1.64</span><span class="sc">*</span>se_hat, </span>
<span id="cb9-4"><a href=""></a>                                      <span class="at">y =</span> <span class="cn">NULL</span>),</span>
<span id="cb9-5"><a href=""></a>                <span class="at">width =</span> .<span class="dv">2</span>, <span class="at">color =</span> <span class="st">"#1b9e77"</span>) <span class="sc">+</span> </span>
<span id="cb9-6"><a href=""></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> estimates, <span class="fu">aes</span>(<span class="at">y =</span> pi_hat), </span>
<span id="cb9-7"><a href=""></a>             <span class="at">color =</span> <span class="st">"#1b9e77"</span>, <span class="at">size =</span> <span class="dv">2</span>)</span>
<span id="cb9-8"><a href=""></a><span class="fu">print</span>(gg2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>

</div>
<img data-src="wk09-slides_files/figure-revealjs/unnamed-chunk-7-1.png" width="768" class="r-stretch"></section>
<section id="adding-the-sample-size" class="slide level2">
<h2>Adding the sample size</h2>
<p>You can see that the confidence intervals (and sample size) varies by district, so let’s add that information to the plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href=""></a>gg3 <span class="ot">&lt;-</span> gg2 <span class="sc">+</span> </span>
<span id="cb10-2"><a href=""></a>  <span class="fu">geom_label</span>(<span class="at">data =</span> estimates, <span class="fu">aes</span>(<span class="at">y =</span> pi_hat <span class="sc">+</span> <span class="fl">1.64</span><span class="sc">*</span>se_hat, <span class="at">label =</span> n),</span>
<span id="cb10-3"><a href=""></a>             <span class="at">color =</span> <span class="st">"#1b9e77"</span>, <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.2</span>)</span>
<span id="cb10-4"><a href=""></a><span class="fu">print</span>(gg3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>

</div>
<img data-src="wk09-slides_files/figure-revealjs/unnamed-chunk-8-1.png" width="768" class="r-stretch"><p>Great! Now we’re done. We’ve got ML estimates of the contact rate for all districts.</p>
<p>But wait… can we do better?</p>
</section>
<section id="looking-carefully-at-309" class="slide level2">
<h2>Looking carefully at 309</h2>
<p>Let’s look at district 309 on the far right. We our estimate of the contact rate in this district is the highest.</p>

<img data-src="wk09-slides_files/figure-revealjs/unnamed-chunk-9-1.png" width="768" class="r-stretch"><p>Our estimator <span class="math inline">\(\hat\pi\)</span> is unbiased, but <strong>if you had to say</strong>, would you say that the turnout rate in district 309 was higher or lower than <span class="math inline">\(\hat{\pi}_{309} = 0.40\)</span>?</p>
<p>If your intuition matches mine, you will say <em>lower</em>. Why? This “why?” is an important question.</p>
</section>
<section id="why" class="slide level2">
<h2>Why?</h2>
<ul>
<li>If you think that <span class="math inline">\(\hat{\pi}\)</span> is a good estimator, but you suddenly want to adjust this particular estimate, you must have additional information coming from somewhere. Where?</li>
<li>The answer: the <em>other districts</em>. We admit that the contact rate will be different across districts, but it also seems reasonable to assume they will be similar (that’s “different, but similar”). Given that 309 has a small sample and looks relatively unlike the other estimates, we want to pull it down <em>slightly</em> toward the other estimates.</li>
</ul>
<p><strong>This is exactly the intuition of hierarchical models.</strong></p>
<p>Let’s write down this “different, but similar” intuition.</p>
<p>To do this, it will be convenient to have our <span class="math inline">\(\pi_j\)</span>s on the logit scale.</p>
</section>
<section id="model-part-2a" class="slide level2">
<h2>Model, part 2a</h2>
<p>Start with the likelihood.</p>
<p><span class="math display">\[
\text{Contacted}_i \sim \text{Bernoulli}(\pi_j)
\]</span></p>
<p>Now translate the <span class="math inline">\(\pi\)</span>s to the logit scale.</p>
<p><span class="math display">\[
\pi_j = \text{logit}^{-1}(\alpha_j)
\]</span></p>
<p>Each of these <span class="math inline">\(\alpha_j\)</span>s is like a constant term in a logit model with no covariates. (We could add covariates, but that makes the example less clear.)</p>
</section>
<section id="model-part-2b" class="slide level2">
<h2>Model, part 2b</h2>
<p>Now for the hierarchical part: we want to capture the notion that these <span class="math inline">\(\alpha_j\)</span>s are different <em>but similar</em>.</p>
<p>We can do that by modeling them as draws from normal distribution.</p>
<p><span class="math display">\[
\alpha_j \sim N(\mu, \sigma^2)
\]</span></p>
<ul>
<li><p>We can estimate <span class="math inline">\(\mu\)</span> (the “typical” <span class="math inline">\(\alpha\)</span>) and <span class="math inline">\(\sigma\)</span> (the degree of similarity) from the data. This is “hierarchical piece.”</p></li>
<li><p>We sometimes refer to batches of parameters modeled as draws from a distribution as “random effects.”</p></li>
</ul>
</section>
<section id="estimating-the-model" class="slide level2">
<h2>Estimating the model</h2>
<p>To estimate the hierarchical model:</p>
<ul>
<li>use ML via the <code>lme4::lmer()</code>/<code>lme4::glmer()</code> function. Fast, fragile, approximate.</li>
<li>use MCMC via the <code>brm()</code> function. Slow(er), robust, exact.<sup>1</sup></li>
<li>also Stan via {rstan`} or {cmdstanr}.</li>
</ul>
<p>We’re going to start with <code>lmer()</code> because I don’t want to juggle posterior simulation and hierarchical models simultaneously, but you should always use <code>brm()</code> (or Stan some other way) <em>always</em> unless you simply need a quick fit.</p>
<aside><ol class="aside-footnotes"><li id="fn1"><p>Also <code>rstanarm::stan_lmer()</code>.</p></li></ol></aside></section>
<section id="lmer" class="slide level2">
<h2><code>lmer()</code></h2>
<p>We can fit the model with <code>glmer()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11" data-code-line-numbers="|2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href=""></a><span class="fu">library</span>(lme4)</span>
<span id="cb11-2"><a href=""></a>f <span class="ot">&lt;-</span> contacted <span class="sc">~</span> (<span class="dv">1</span> <span class="sc">|</span> district_id)</span>
<span id="cb11-3"><a href=""></a>fit <span class="ot">&lt;-</span> <span class="fu">glmer</span>(f, <span class="at">data =</span> finland, <span class="at">family =</span> binomial)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And we can summarize the results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href=""></a>arm<span class="sc">::</span><span class="fu">display</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>glmer(formula = contacted ~ (1 | district_id), data = finland, 
    family = binomial)
coef.est  coef.se 
   -1.37     0.12 

Error terms:
 Groups      Name        Std.Dev.
 district_id (Intercept) 0.31    
 Residual                1.00    
---
number of obs: 1086, groups: district_id, 14
AIC = 1108.5, DIC = 1070
deviance = 1087.0 </code></pre>
</div>
</div>
<p>From the output above, we estimate <span class="math inline">\(\mu\)</span> as -1.37 and <span class="math inline">\(\sigma\)</span> as 0.31. That is, the <span class="math inline">\(\alpha_j\)</span>s are about -1.37 give-or-take 0.31 or so.</p>
</section>
<section id="extracting-the-group-level-effects" class="slide level2">
<h2>Extracting the group-level effects</h2>
<p><strong>group-level effects 👉 “random effects”</strong></p>
<p>But here’s the useful part: we can take this <span class="math inline">\(\hat{\mu}\)</span> and <span class="math inline">\(\hat{\sigma}\)</span> and use them as a Bayesian prior for the individual <span class="math inline">\(\alpha_j\)</span>s.</p>
<p>Each <span class="math inline">\(\alpha_j\)</span> has a likelihood (using the data from that district) and a prior (using <span class="math inline">\(\hat{\mu}\)</span> and <span class="math inline">\(\hat{\sigma}\)</span>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href=""></a><span class="fu">fixef</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
      -1.37 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href=""></a><span class="fu">ranef</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$district_id
    (Intercept)
312     -0.3586
315     -0.2901
316     -0.1875
305     -0.1260
310     -0.1917
306     -0.0768
311     -0.0743
304      0.1125
317      0.0809
307      0.1339
314      0.1497
313      0.1793
308      0.3718
309      0.3681

with conditional variances for "district_id" </code></pre>
</div>
</div>
</section>
<section id="working-with-the-group-level-effects" class="slide level2">
<h2>Working with the group-level effects</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href=""></a><span class="co"># mu</span></span>
<span id="cb18-2"><a href=""></a><span class="co"># - fixed part</span></span>
<span id="cb18-3"><a href=""></a><span class="co"># - "typical" intercept across districts</span></span>
<span id="cb18-4"><a href=""></a>fe <span class="ot">&lt;-</span> <span class="fu">fixef</span>(fit)[<span class="st">"(Intercept)"</span>]  </span>
<span id="cb18-5"><a href=""></a>fe</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
      -1.37 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href=""></a><span class="co"># (alpha - mu) </span></span>
<span id="cb20-2"><a href=""></a><span class="co"># - random part</span></span>
<span id="cb20-3"><a href=""></a><span class="co"># - deviation from the typical intercept for each district</span></span>
<span id="cb20-4"><a href=""></a>re <span class="ot">&lt;-</span> <span class="fu">ranef</span>(fit)<span class="sc">$</span>district_id[, <span class="st">"(Intercept)"</span>] <span class="co"># ️👈 "random effects"‼️</span></span>
<span id="cb20-5"><a href=""></a>re</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] -0.3586 -0.2901 -0.1875 -0.1260 -0.1917 -0.0768 -0.0743  0.1125  0.0809  0.1339
[11]  0.1497  0.1793  0.3718  0.3681</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href=""></a><span class="co"># alpha</span></span>
<span id="cb22-2"><a href=""></a>alpha_hat <span class="ot">&lt;-</span> fe <span class="sc">+</span> re  <span class="co"># district-level linear predictors</span></span>
<span id="cb22-3"><a href=""></a>alpha_hat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] -1.73 -1.66 -1.56 -1.50 -1.56 -1.45 -1.45 -1.26 -1.29 -1.24 -1.22 -1.19 -1.00 -1.00</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href=""></a><span class="co"># pi</span></span>
<span id="cb24-2"><a href=""></a>pi_hat <span class="ot">&lt;-</span> <span class="fu">plogis</span>(fe <span class="sc">+</span> re)  <span class="co"># district-level probabilities</span></span>
<span id="cb24-3"><a href=""></a>pi_hat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 0.151 0.160 0.174 0.183 0.173 0.190 0.191 0.221 0.216 0.225 0.228 0.233 0.269 0.268</code></pre>
</div>
</div>
</section>
<section id="using-predict" class="slide level2">
<h2>Using <code>predict()</code></h2>
<p>In this case, it’s easy to use <code>predict()</code> to get this same estimates. (The <code>predict()</code> approach is a little safer because it’s easier to keep the <code>pi_hat</code> and the <code>district_id</code> label together.)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href=""></a>hier_estimates <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">district_id =</span> <span class="fu">unique</span>(finland<span class="sc">$</span>district_id)) <span class="sc">%&gt;%</span></span>
<span id="cb26-2"><a href=""></a>  <span class="fu">mutate</span>(<span class="at">pi_hat =</span> <span class="fu">predict</span>(fit, <span class="at">newdata =</span> ., <span class="at">type =</span> <span class="st">"response"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href=""></a>  <span class="fu">arrange</span>(district_id) <span class="sc">%&gt;%</span></span>
<span id="cb26-4"><a href=""></a>  <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 14
Columns: 2
$ district_id &lt;fct&gt; 312, 315, 316, 305, 310, 306, 311, 304, 317, 307, 314, 313, 308, 309
$ pi_hat      &lt;dbl&gt; 0.151, 0.160, 0.174, 0.183, 0.173, 0.190, 0.191, 0.221, 0.216, 0.225…</code></pre>
</div>
</div>
</section>
<section id="using-marginaleffects" class="slide level2">
<h2>Using {marginaleffects}</h2>
<p>We can also do this with {marginaleffects}.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href=""></a><span class="fu">predictions</span>(fit,</span>
<span id="cb28-2"><a href=""></a>            <span class="at">newdata =</span> <span class="fu">datagrid</span>(<span class="at">district_id =</span> unique)) <span class="sc">|&gt;</span></span>
<span id="cb28-3"><a href=""></a>  <span class="fu">select</span>(district_id, estimate) <span class="sc">|&gt;</span></span>
<span id="cb28-4"><a href=""></a>  <span class="fu">arrange</span>(district_id) <span class="sc">|&gt;</span>  <span class="co"># comparisons() arranges predictions differently</span></span>
<span id="cb28-5"><a href=""></a>  <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 14
Columns: 2
$ district_id &lt;fct&gt; 312, 315, 316, 305, 310, 306, 311, 304, 317, 307, 314, 313, 308, 309
$ estimate    &lt;dbl&gt; 0.151, 0.160, 0.174, 0.183, 0.173, 0.190, 0.191, 0.221, 0.216, 0.225…</code></pre>
</div>
</div>
</section>
<section id="comparing-the-ml-and-hierarchical-estimates" class="slide level2">
<h2>Comparing the ML and hierarchical estimates</h2>
<p>We can add this to our plot to see how the estimates changed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href=""></a>gg4 <span class="ot">&lt;-</span> gg3 <span class="sc">+</span> </span>
<span id="cb30-2"><a href=""></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> hier_estimates,</span>
<span id="cb30-3"><a href=""></a>             <span class="fu">aes</span>(<span class="at">y =</span> pi_hat), </span>
<span id="cb30-4"><a href=""></a>             <span class="at">color =</span> <span class="st">"#d95f02"</span>,</span>
<span id="cb30-5"><a href=""></a>             <span class="at">shape =</span> <span class="dv">10</span>, <span class="at">size =</span> <span class="dv">3</span>)</span>
<span id="cb30-6"><a href=""></a><span class="fu">print</span>(gg4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="wk09-slides_files/figure-revealjs/unnamed-chunk-16-1.png" width="768"></p>
</figure>
</div>
</div>
</div>

<aside><div>
<ul>
<li>Notice that our new estimate for 309 is now at the very bottom of our initial confidence interval.</li>
<li>Notice the differences between the original ML estimates and CIs and the new estimates from the hierarchical model.</li>
</ul>
</div></aside></section>
<section id="a-plot-of-the-partial-pooling" class="slide level2">
<h2>A plot of the partial pooling</h2>
<p>We can compare the initial ML estimates to the hierarchical model estimates.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href=""></a>comb <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(<span class="fu">list</span>(<span class="st">"initial ML"</span> <span class="ot">=</span> estimates,</span>
<span id="cb31-2"><a href=""></a>                       <span class="st">"hierarchical"</span> <span class="ot">=</span> hier_estimates), </span>
<span id="cb31-3"><a href=""></a>                  <span class="at">.id =</span> <span class="st">"type"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb31-4"><a href=""></a>  <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 28
Columns: 5
$ type        &lt;chr&gt; "initial ML", "initial ML", "initial ML", "initial ML", "initial ML"…
$ district_id &lt;fct&gt; 312, 315, 316, 305, 310, 306, 311, 304, 317, 307, 314, 313, 308, 309…
$ pi_hat      &lt;dbl&gt; 0.0862, 0.0909, 0.1250, 0.1500, 0.1620, 0.1707, 0.1818, 0.2288, 0.22…
$ n           &lt;int&gt; 58, 44, 40, 40, 179, 41, 88, 153, 61, 105, 103, 65, 86, 23, NA, NA, …
$ se_hat      &lt;dbl&gt; 0.0369, 0.0433, 0.0523, 0.0565, 0.0275, 0.0588, 0.0411, 0.0340, 0.05…</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href=""></a>gg_comb <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(comb, <span class="fu">aes</span>(<span class="at">x =</span> pi_hat, <span class="at">y =</span> type)) <span class="sc">+</span> </span>
<span id="cb33-2"><a href=""></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb33-3"><a href=""></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">group =</span> district_id), <span class="at">alpha =</span> <span class="fl">0.5</span>)</span>
<span id="cb33-4"><a href=""></a><span class="fu">print</span>(gg_comb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>

</div>
<img data-src="wk09-slides_files/figure-revealjs/unnamed-chunk-17-1.png" width="768" class="r-stretch"></section>
<section id="two-approaches-plus-a-compromise" class="slide level2">
<h2>Two approaches, plus a compromise</h2>
<p>It’s helpful to think of these approaches in terms of the amount of information they borrow across groups.</p>
<div class="fragment fade-up">
<ol type="1">
<li><strong>No Pooling.</strong> Assume the groups are different, and that nothing can be learned from the other groups. Estimate each group separately.</li>
</ol>
</div>
<div class="fragment fade-up">
<ol start="2" type="1">
<li><strong>Complete Pooling</strong>. Assume the groups are identical. Collapse all the groups together to estimate the single, common estimate.</li>
</ol>
</div>
<div class="fragment fade-up">
<ol start="3" type="1">
<li><strong>Partial Pooling</strong>. A compromise between the two extremes above. Assume the groups are different, <em>but similar</em>. Estimate the amount of similarity using the data, and pool the estimates toward a common estimate accordingly.</li>
</ol>
</div>
</section>
<section class="slide level2">

<p>We did not implement complete pooling above, but we can do it here to compare the three approaches.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href=""></a><span class="co"># use the overall rate for each district</span></span>
<span id="cb34-2"><a href=""></a>common_estimate <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">district_id =</span> <span class="fu">unique</span>(finland<span class="sc">$</span>district_id)) <span class="sc">%&gt;%</span></span>
<span id="cb34-3"><a href=""></a>  <span class="fu">mutate</span>(<span class="at">pi_hat =</span> <span class="fu">mean</span>(finland<span class="sc">$</span>contacted))</span>
<span id="cb34-4"><a href=""></a></span>
<span id="cb34-5"><a href=""></a><span class="co"># combine the three types</span></span>
<span id="cb34-6"><a href=""></a>comb <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(<span class="fu">list</span>(<span class="st">"No Pooling"</span> <span class="ot">=</span> estimates,</span>
<span id="cb34-7"><a href=""></a>                       <span class="st">"Partial Pooling"</span> <span class="ot">=</span> hier_estimates,</span>
<span id="cb34-8"><a href=""></a>                       <span class="st">"Complete Pooling"</span> <span class="ot">=</span> common_estimate), </span>
<span id="cb34-9"><a href=""></a>                  <span class="at">.id =</span> <span class="st">"type"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb34-10"><a href=""></a>  <span class="fu">mutate</span>(<span class="at">type =</span> <span class="fu">reorder</span>(type, pi_hat, var)) </span>
<span id="cb34-11"><a href=""></a></span>
<span id="cb34-12"><a href=""></a>gg_comb2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(comb, <span class="fu">aes</span>(<span class="at">x =</span> pi_hat, <span class="at">y =</span> type)) <span class="sc">+</span> </span>
<span id="cb34-13"><a href=""></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb34-14"><a href=""></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">group =</span> district_id), <span class="at">alpha =</span> <span class="fl">0.5</span>)</span>
<span id="cb34-15"><a href=""></a><span class="fu">print</span>(gg_comb2)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>

</div>
<img data-src="wk09-slides_files/figure-revealjs/unnamed-chunk-18-1.png" width="768" class="r-stretch"></section></section>
<section id="key-things" class="title-slide slide level1 center">
<h1>Key things</h1>
<p>First, the 309 problem.</p>
<p>Second, <span class="math inline">\(\mu_i = \alpha_{j[i]} + \beta x_i\)</span>, where <span class="math inline">\(\alpha_j \sim N(0, \sigma^2_\alpha)\)</span>.</p>
<p>Third, the figure below.</p>

<img data-src="wk09-slides_files/figure-revealjs/unnamed-chunk-19-1.png" width="768" class="r-stretch"></section>

<section id="we-stopped-here-on-1021-well-pick-up-here-next-time." class="title-slide slide level1 center">
<h1>We stopped here on 10/21; we’ll pick up here next time.</h1>

</section>

<section id="start-with-the-simulate-and-recover-exercise" class="title-slide slide level1 center">
<h1>Start with the simulate and recover exercise</h1>

</section>

<section>
<section id="contact-in-the-uk" class="title-slide slide level1 center">
<h1>Contact in the UK</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href=""></a>uk <span class="ot">&lt;-</span> crdata<span class="sc">::</span>uk <span class="sc">|&gt;</span></span>
<span id="cb35-2"><a href=""></a>  <span class="co"># make contacted an indicator</span></span>
<span id="cb35-3"><a href=""></a>  <span class="fu">mutate</span>(<span class="at">contacted =</span> <span class="fu">as.numeric</span>(contacted <span class="sc">==</span> <span class="st">"Contacted"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb35-4"><a href=""></a>  <span class="co"># mutate district_id to factor ordered by contact rate</span></span>
<span id="cb35-5"><a href=""></a>  <span class="fu">mutate</span>(<span class="at">district_id =</span> <span class="fu">str_remove</span>(district_id, <span class="st">"District "</span>), </span>
<span id="cb35-6"><a href=""></a>         <span class="at">district_id =</span> <span class="fu">reorder</span>(district_id, contacted)) <span class="sc">|&gt;</span></span>
<span id="cb35-7"><a href=""></a>  <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 756
Columns: 3
$ district_id              &lt;fct&gt; 492, 492, 492, 492, 492, 374, 350, 350, 350, 463, 463, …
$ contacted                &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1…
$ district_competitiveness &lt;dbl&gt; 0.484, 0.484, 0.484, 0.484, 0.484, 0.510, 0.540, 0.540,…</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href=""></a>gg1_uk <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(uk, <span class="fu">aes</span>(<span class="at">x =</span> district_id, <span class="at">y =</span> contacted)) <span class="sc">+</span> </span>
<span id="cb37-2"><a href=""></a>  <span class="fu">geom_jitter</span>(<span class="at">shape =</span> <span class="dv">21</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">1</span>)</span>
<span id="cb37-3"><a href=""></a><span class="fu">print</span>(gg1_uk)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>

</div>
<img data-src="wk09-slides_files/figure-revealjs/unnamed-chunk-21-1.png" width="768" class="r-stretch"></section>
<section class="slide level2">

<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href=""></a>estimates <span class="ot">&lt;-</span> uk <span class="sc">%&gt;%</span></span>
<span id="cb38-2"><a href=""></a>  <span class="fu">group_by</span>(district_id) <span class="sc">%&gt;%</span></span>
<span id="cb38-3"><a href=""></a>  <span class="fu">summarize</span>(<span class="at">pi_hat =</span> <span class="fu">mean</span>(contacted),</span>
<span id="cb38-4"><a href=""></a>            <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb38-5"><a href=""></a>            <span class="at">se_hat =</span> <span class="fu">sqrt</span>(pi_hat<span class="sc">*</span>(<span class="dv">1</span> <span class="sc">-</span> pi_hat))<span class="sc">/</span><span class="fu">sqrt</span>(n)) <span class="sc">%&gt;%</span></span>
<span id="cb38-6"><a href=""></a>  <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 253
Columns: 4
$ district_id &lt;fct&gt; 319, 320, 323, 326, 328, 329, 330, 331, 337, 338, 339, 344, 347, 348…
$ pi_hat      &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ n           &lt;int&gt; 1, 2, 4, 2, 3, 2, 2, 1, 4, 1, 1, 2, 2, 1, 1, 1, 2, 2, 6, 4, 1, 3, 1,…
$ se_hat      &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href=""></a>gg2_uk <span class="ot">&lt;-</span> gg1_uk <span class="sc">+</span> </span>
<span id="cb40-2"><a href=""></a>  <span class="fu">geom_errorbar</span>(<span class="at">data =</span> estimates, <span class="fu">aes</span>(<span class="at">ymin =</span> pi_hat <span class="sc">-</span> <span class="fl">1.64</span><span class="sc">*</span>se_hat,</span>
<span id="cb40-3"><a href=""></a>                                      <span class="at">ymax =</span> pi_hat <span class="sc">+</span> <span class="fl">1.64</span><span class="sc">*</span>se_hat, </span>
<span id="cb40-4"><a href=""></a>                                      <span class="at">y =</span> <span class="cn">NULL</span>),</span>
<span id="cb40-5"><a href=""></a>                <span class="at">width =</span> .<span class="dv">2</span>, <span class="at">color =</span> <span class="st">"#1b9e77"</span>) <span class="sc">+</span> </span>
<span id="cb40-6"><a href=""></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> estimates, <span class="fu">aes</span>(<span class="at">y =</span> pi_hat), </span>
<span id="cb40-7"><a href=""></a>             <span class="at">color =</span> <span class="st">"#1b9e77"</span>, <span class="at">size =</span> <span class="dv">2</span>)</span>
<span id="cb40-8"><a href=""></a><span class="fu">print</span>(gg2_uk)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>

</div>
<img data-src="wk09-slides_files/figure-revealjs/unnamed-chunk-23-1.png" width="768" class="r-stretch"></section>
<section class="slide level2">

<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href=""></a>no_pooling <span class="ot">&lt;-</span>  uk <span class="sc">%&gt;%</span></span>
<span id="cb41-2"><a href=""></a>  <span class="fu">group_by</span>(district_id) <span class="sc">%&gt;%</span></span>
<span id="cb41-3"><a href=""></a>  <span class="fu">summarize</span>(<span class="at">pi_hat =</span> <span class="fu">mean</span>(contacted))  <span class="sc">%&gt;%</span></span>
<span id="cb41-4"><a href=""></a>  <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 253
Columns: 2
$ district_id &lt;fct&gt; 319, 320, 323, 326, 328, 329, 330, 331, 337, 338, 339, 344, 347, 348…
$ pi_hat      &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href=""></a>complete_pooling <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">district_id =</span> <span class="fu">unique</span>(uk<span class="sc">$</span>district_id)) <span class="sc">%&gt;%</span></span>
<span id="cb43-2"><a href=""></a>  <span class="fu">mutate</span>(<span class="at">pi_hat =</span> <span class="fu">mean</span>(uk<span class="sc">$</span>contacted)) <span class="sc">%&gt;%</span></span>
<span id="cb43-3"><a href=""></a>  <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 253
Columns: 2
$ district_id &lt;fct&gt; 492, 374, 350, 463, 393, 366, 432, 375, 385, 377, 378, 461, 387, 367…
$ pi_hat      &lt;dbl&gt; 0.32, 0.32, 0.32, 0.32, 0.32, 0.32, 0.32, 0.32, 0.32, 0.32, 0.32, 0.…</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<div class="cell">
<div class="sourceCode cell-code" id="cb45" data-code-line-numbers="|1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href=""></a>f <span class="ot">&lt;-</span> contacted <span class="sc">~</span> (<span class="dv">1</span> <span class="sc">|</span> district_id)</span>
<span id="cb45-2"><a href=""></a>fit <span class="ot">&lt;-</span> <span class="fu">glmer</span>(f, <span class="at">data =</span> uk, <span class="at">family =</span> binomial)</span>
<span id="cb45-3"><a href=""></a></span>
<span id="cb45-4"><a href=""></a>arm<span class="sc">::</span><span class="fu">display</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>glmer(formula = contacted ~ (1 | district_id), data = uk, family = binomial)
coef.est  coef.se 
   -0.85     0.10 

Error terms:
 Groups      Name        Std.Dev.
 district_id (Intercept) 0.71    
 Residual                1.00    
---
number of obs: 756, groups: district_id, 253
AIC = 941.8, DIC = 694
deviance = 815.8 </code></pre>
</div>
</div>
</section>
<section class="slide level2">

<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href=""></a>partial_pooling <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">district_id =</span> <span class="fu">unique</span>(uk<span class="sc">$</span>district_id)) <span class="sc">%&gt;%</span></span>
<span id="cb47-2"><a href=""></a>  <span class="fu">mutate</span>(<span class="at">pi_hat =</span> <span class="fu">predict</span>(fit, <span class="at">newdata =</span> ., <span class="at">type =</span> <span class="st">"response"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb47-3"><a href=""></a>  <span class="fu">arrange</span>(district_id) <span class="sc">%&gt;%</span></span>
<span id="cb47-4"><a href=""></a>  <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 253
Columns: 2
$ district_id &lt;fct&gt; 319, 320, 323, 326, 328, 329, 330, 331, 337, 338, 339, 344, 347, 348…
$ pi_hat      &lt;dbl&gt; 0.271, 0.249, 0.216, 0.249, 0.231, 0.249, 0.249, 0.271, 0.216, 0.271…</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href=""></a>comb <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(<span class="fu">list</span>(<span class="st">"No Pooling"</span> <span class="ot">=</span> no_pooling,</span>
<span id="cb49-2"><a href=""></a>                       <span class="st">"Partial Pooling"</span> <span class="ot">=</span> partial_pooling,</span>
<span id="cb49-3"><a href=""></a>                       <span class="st">"Complete Pooling"</span> <span class="ot">=</span> complete_pooling), </span>
<span id="cb49-4"><a href=""></a>                  <span class="at">.id =</span> <span class="st">"type"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb49-5"><a href=""></a>  <span class="fu">mutate</span>(<span class="at">type =</span> <span class="fu">reorder</span>(type, pi_hat, var)) <span class="sc">%&gt;%</span></span>
<span id="cb49-6"><a href=""></a>  <span class="fu">arrange</span>(district_id) <span class="sc">%&gt;%</span></span>
<span id="cb49-7"><a href=""></a>  <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 759
Columns: 3
$ type        &lt;fct&gt; No Pooling, Partial Pooling, Complete Pooling, No Pooling, Partial P…
$ district_id &lt;fct&gt; 319, 319, 319, 320, 320, 320, 323, 323, 323, 326, 326, 326, 328, 328…
$ pi_hat      &lt;dbl&gt; 0.000, 0.271, 0.320, 0.000, 0.249, 0.320, 0.000, 0.216, 0.320, 0.000…</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href=""></a><span class="fu">ggplot</span>(comb, <span class="fu">aes</span>(<span class="at">x =</span> pi_hat, <span class="at">y =</span> type)) <span class="sc">+</span> </span>
<span id="cb51-2"><a href=""></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb51-3"><a href=""></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">group =</span> district_id), <span class="at">alpha =</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>

</div>
<img data-src="wk09-slides_files/figure-revealjs/unnamed-chunk-29-1.png" width="768" class="r-stretch"></section></section>
<section>
<section id="contact-in-the-uk-w-predictors" class="title-slide slide level1 center">
<h1>Contact in the UK (w/ predictors!)</h1>
<p>We can also add predictors of the random parameters, such as the competitiveness of the district.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href=""></a><span class="fu">glimpse</span>(uk)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 756
Columns: 3
$ district_id              &lt;fct&gt; 492, 492, 492, 492, 492, 374, 350, 350, 350, 463, 463, …
$ contacted                &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1…
$ district_competitiveness &lt;dbl&gt; 0.484, 0.484, 0.484, 0.484, 0.484, 0.510, 0.540, 0.540,…</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href=""></a>uk_districts <span class="ot">&lt;-</span> uk <span class="sc">%&gt;%</span> </span>
<span id="cb54-2"><a href=""></a>  <span class="fu">select</span>(district_id, district_competitiveness) <span class="sc">%&gt;%</span></span>
<span id="cb54-3"><a href=""></a>  <span class="fu">distinct</span>() <span class="sc">%&gt;%</span></span>
<span id="cb54-4"><a href=""></a>  <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 253
Columns: 2
$ district_id              &lt;fct&gt; 492, 374, 350, 463, 393, 366, 432, 375, 385, 377, 378, …
$ district_competitiveness &lt;dbl&gt; 0.484, 0.510, 0.540, 0.454, 0.429, 0.676, 0.603, 0.588,…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href=""></a>w_comp <span class="ot">&lt;-</span> partial_pooling <span class="sc">|&gt;</span></span>
<span id="cb56-2"><a href=""></a>  <span class="fu">left_join</span>(uk_districts) <span class="sc">|&gt;</span></span>
<span id="cb56-3"><a href=""></a>  <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 253
Columns: 3
$ district_id              &lt;fct&gt; 319, 320, 323, 326, 328, 329, 330, 331, 337, 338, 339, …
$ pi_hat                   &lt;dbl&gt; 0.271, 0.249, 0.216, 0.249, 0.231, 0.249, 0.249, 0.271,…
$ district_competitiveness &lt;dbl&gt; 0.584, 0.658, 0.657, 0.453, 0.676, 0.686, 0.659, 0.679,…</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href=""></a><span class="fu">ggplot</span>(w_comp, <span class="fu">aes</span>(<span class="at">x =</span> district_competitiveness, <span class="at">y =</span> pi_hat)) <span class="sc">+</span> </span>
<span id="cb58-2"><a href=""></a>  <span class="fu">geom_point</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>

</div>
<img data-src="wk09-slides_files/figure-revealjs/unnamed-chunk-32-1.png" width="768" class="r-stretch"></section>
<section class="slide level2">

<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href=""></a><span class="fu">ggplot</span>(w_comp, <span class="fu">aes</span>(<span class="at">x =</span> district_competitiveness, <span class="at">y =</span> pi_hat)) <span class="sc">+</span> </span>
<span id="cb59-2"><a href=""></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb59-3"><a href=""></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"#1b9e77"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>

</div>
<img data-src="wk09-slides_files/figure-revealjs/unnamed-chunk-33-1.png" width="768" class="r-stretch"></section>
<section class="slide level2">

<p>Hey! We should build this directly into our model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60" data-code-line-numbers="|1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href=""></a>f <span class="ot">&lt;-</span> contacted <span class="sc">~</span> district_competitiveness <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> district_id)</span>
<span id="cb60-2"><a href=""></a>fit <span class="ot">&lt;-</span> <span class="fu">glmer</span>(f, <span class="at">data =</span> uk, <span class="at">family =</span> binomial)</span>
<span id="cb60-3"><a href=""></a></span>
<span id="cb60-4"><a href=""></a>arm<span class="sc">::</span><span class="fu">display</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>glmer(formula = contacted ~ district_competitiveness + (1 | district_id), 
    data = uk, family = binomial)
                         coef.est coef.se
(Intercept)              -3.40     0.65  
district_competitiveness  3.87     0.96  

Error terms:
 Groups      Name        Std.Dev.
 district_id (Intercept) 0.60    
 Residual                1.00    
---
number of obs: 756, groups: district_id, 253
AIC = 927.2, DIC = 740
deviance = 830.5 </code></pre>
</div>
</div>
</section>
<section class="slide level2">

<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href=""></a>partial_pooling <span class="ot">&lt;-</span> uk <span class="sc">%&gt;%</span></span>
<span id="cb62-2"><a href=""></a>  <span class="fu">select</span>(district_id, district_competitiveness) <span class="sc">%&gt;%</span></span>
<span id="cb62-3"><a href=""></a>  <span class="fu">distinct</span>() <span class="sc">%&gt;%</span></span>
<span id="cb62-4"><a href=""></a>  <span class="fu">mutate</span>(<span class="at">pi_hat =</span> <span class="fu">predict</span>(fit, <span class="at">newdata =</span> ., <span class="at">type =</span> <span class="st">"response"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb62-5"><a href=""></a>  <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 253
Columns: 3
$ district_id              &lt;fct&gt; 492, 374, 350, 463, 393, 366, 432, 375, 385, 377, 378, …
$ district_competitiveness &lt;dbl&gt; 0.484, 0.510, 0.540, 0.454, 0.429, 0.676, 0.603, 0.588,…
$ pi_hat                   &lt;dbl&gt; 0.144, 0.183, 0.230, 0.185, 0.137, 0.303, 0.204, 0.258,…</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href=""></a><span class="fu">ggplot</span>(partial_pooling, <span class="fu">aes</span>(<span class="at">x =</span> district_competitiveness, <span class="at">y =</span> pi_hat)) <span class="sc">+</span> </span>
<span id="cb64-2"><a href=""></a>  <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>

</div>
<img data-src="wk09-slides_files/figure-revealjs/unnamed-chunk-36-1.png" width="768" class="r-stretch"></section>
<section class="slide level2">

<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href=""></a>comb <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(<span class="fu">list</span>(<span class="st">"No Pooling"</span> <span class="ot">=</span> no_pooling,</span>
<span id="cb65-2"><a href=""></a>                       <span class="st">"Partial Pooling"</span> <span class="ot">=</span> partial_pooling,</span>
<span id="cb65-3"><a href=""></a>                       <span class="st">"Complete Pooling"</span> <span class="ot">=</span> complete_pooling), </span>
<span id="cb65-4"><a href=""></a>                  <span class="at">.id =</span> <span class="st">"type"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb65-5"><a href=""></a>  <span class="fu">mutate</span>(<span class="at">type =</span> <span class="fu">reorder</span>(type, pi_hat, var)) <span class="sc">%&gt;%</span></span>
<span id="cb65-6"><a href=""></a>  <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 759
Columns: 4
$ type                     &lt;fct&gt; No Pooling, No Pooling, No Pooling, No Pooling, No Pool…
$ district_id              &lt;fct&gt; 319, 320, 323, 326, 328, 329, 330, 331, 337, 338, 339, …
$ pi_hat                   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ district_competitiveness &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href=""></a><span class="fu">ggplot</span>(comb, <span class="fu">aes</span>(<span class="at">x =</span> pi_hat, <span class="at">y =</span> type)) <span class="sc">+</span> </span>
<span id="cb67-2"><a href=""></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb67-3"><a href=""></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">group =</span> district_id), <span class="at">alpha =</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>

</div>
<img data-src="wk09-slides_files/figure-revealjs/unnamed-chunk-38-1.png" width="768" class="r-stretch"></section></section>
<section id="a-simulation-exercise-in-r" class="title-slide slide level1 center">
<h1>A simulation exercise in R</h1>

</section>

<section>
<section id="contact-in-several-countries" class="title-slide slide level1 center">
<h1>Contact in Several Countries</h1>
<p><span class="math display">\[
\text{Pr}(\text{Contacted}_{i} = 1) = \text{logit}^{-1}(\alpha_{jk} + {\bf X}_i\beta)
\]</span> <span class="math display">\[
\alpha_{jk} \sim N(\gamma_{0k} + \gamma_{1k}\text{Competitiveness}_j, \sigma^2_{\alpha}) \text{ for } j = 1, 2,..., J
\]</span></p>
<p><span class="math display">\[
\begin{pmatrix} \gamma_{0k} \\ \gamma_{1k} \end{pmatrix}
\sim
{\large} N\begin{pmatrix}  \begin{pmatrix} \mu_{\gamma_{0}} \\ \mu_{\gamma_{1}} \end{pmatrix},
\begin{pmatrix}         \sigma^2_{\gamma_{0}}                                           &amp;                 \rho\sigma_{\gamma_{0}}\sigma_{\gamma_{1}} \\
\rho\sigma_{\gamma_{0}}\sigma_{\gamma_{1}}         &amp;                \sigma^2_{\gamma_{1}}
\end{pmatrix}\end{pmatrix} \text{ , for }k = 1, 2, ..., K
\]</span></p>
<p><span class="math display">\[
\mu_{\gamma_{0}} = \delta_{00} + \delta_{01}\text{Proportional Rules}_k
\]</span></p>
<p><span class="math display">\[
\mu_{\gamma_{1}} = \delta_{10} + \delta_{11}\text{Proportional Rules}_k
\]</span></p>
</section>
<section class="slide level2">

<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href=""></a>rainey <span class="ot">&lt;-</span> crdata<span class="sc">::</span>rainey2015 <span class="sc">|&gt;</span></span>
<span id="cb68-2"><a href=""></a>  <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 5,126
Columns: 5
$ election_id              &lt;chr&gt; "Canada", "Canada", "Canada", "Canada", "Canada", "Cana…
$ district_id              &lt;chr&gt; "Canada; District 7", "Canada; District 4", "Canada; Di…
$ contacted                &lt;fct&gt; Contacted, Not Contacted, Not Contacted, Not Contacted,…
$ district_competitiveness &lt;dbl&gt; 0.740, 0.420, 0.692, 0.692, 0.610, 0.742, 0.742, 0.742,…
$ electoral_rules          &lt;fct&gt; SMD, SMD, SMD, SMD, SMD, SMD, SMD, SMD, SMD, SMD, SMD, …</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<p>We can fit this model with <code>lmer()</code>, but this <em>relatively small</em> model is too big or complex.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70" data-code-line-numbers="|2,3,4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href=""></a><span class="co"># model is fragile</span></span>
<span id="cb70-2"><a href=""></a>f <span class="ot">&lt;-</span> contacted <span class="sc">~</span> district_competitiveness<span class="sc">*</span>electoral_rules <span class="sc">+</span></span>
<span id="cb70-3"><a href=""></a>               (<span class="dv">1</span> <span class="sc">|</span> district_id) <span class="sc">+</span></span>
<span id="cb70-4"><a href=""></a>               (<span class="dv">1</span> <span class="sc">+</span> district_competitiveness <span class="sc">|</span> election_id)</span>
<span id="cb70-5"><a href=""></a>fit <span class="ot">&lt;-</span> <span class="fu">glmer</span>(f, <span class="at">data =</span> rainey, <span class="at">family =</span> binomial)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Stan would have no problems with this one…</p>
</section>
<section class="slide level2">

<p>And show the estimates.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href=""></a>arm<span class="sc">::</span><span class="fu">display</span>(fit, <span class="at">detail =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>glmer(formula = contacted ~ district_competitiveness * electoral_rules + 
    (1 | district_id) + (1 + district_competitiveness | election_id), 
    data = rainey, family = binomial)
                                            coef.est coef.se z value Pr(&gt;|z|)
(Intercept)                                 -2.35     0.59   -4.01    0.00   
district_competitiveness                     1.21     0.81    1.49    0.14   
electoral_rulesSMD                          -0.74     0.72   -1.03    0.30   
district_competitiveness:electoral_rulesSMD  3.07     1.03    2.99    0.00   

Error terms:
 Groups      Name                     Std.Dev. Corr 
 district_id (Intercept)              0.47          
 election_id (Intercept)              0.18          
             district_competitiveness 0.27     1.00 
 Residual                             1.00          
---
number of obs: 5126, groups: district_id, 567; election_id, 5
AIC = 5580.3, DIC = 5131
deviance = 5347.5 </code></pre>
</div>
</div>
</section>
<section class="slide level2">

<p>Using the <code>lmer()</code>-like formula, we can fit the hiearchical model with Stan.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href=""></a>start_time <span class="ot">&lt;-</span> <span class="fu">Sys.time</span>()</span>
<span id="cb73-2"><a href=""></a>stan_fit <span class="ot">&lt;-</span> <span class="fu">brm</span>(contacted <span class="sc">~</span> district_competitiveness<span class="sc">*</span>electoral_rules <span class="sc">+</span></span>
<span id="cb73-3"><a href=""></a>                  (<span class="dv">1</span> <span class="sc">|</span> district_id) <span class="sc">+</span> </span>
<span id="cb73-4"><a href=""></a>                  (<span class="dv">1</span> <span class="sc">+</span> district_competitiveness <span class="sc">|</span> election_id),</span>
<span id="cb73-5"><a href=""></a>                <span class="at">data =</span> rainey, </span>
<span id="cb73-6"><a href=""></a>                <span class="at">family =</span> bernoulli, </span>
<span id="cb73-7"><a href=""></a>                <span class="at">chains =</span> <span class="dv">10</span>,</span>
<span id="cb73-8"><a href=""></a>                <span class="at">cores =</span> <span class="dv">10</span>,</span>
<span id="cb73-9"><a href=""></a>                <span class="at">iter =</span> <span class="dv">4000</span>, </span>
<span id="cb73-10"><a href=""></a>                <span class="at">backend =</span> <span class="st">"cmdstanr"</span>)</span>
<span id="cb73-11"><a href=""></a>end_time <span class="ot">&lt;-</span> <span class="fu">Sys.time</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And it fits in less than 10 minutes. This took hours or days in 2012 with JAGS.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href=""></a>end_time <span class="sc">-</span> start_time</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Time difference of 4.56 mins</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href=""></a><span class="fu">print</span>(stan_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Family: bernoulli 
  Links: mu = logit 
Formula: contacted ~ district_competitiveness * electoral_rules + (1 | district_id) + (1 + district_competitiveness | election_id) 
   Data: rainey (Number of observations: 5126) 
  Draws: 10 chains, each with iter = 4000; warmup = 2000; thin = 1;
         total post-warmup draws = 20000

Multilevel Hyperparameters:
~district_id (Number of levels: 567) 
              Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
sd(Intercept)     0.52      0.08     0.38     0.69 1.00     4820     8397

~election_id (Number of levels: 5) 
                                        Estimate Est.Error l-95% CI u-95% CI Rhat
sd(Intercept)                               0.62      0.53     0.02     1.97 1.00
sd(district_competitiveness)                0.88      0.69     0.04     2.65 1.00
cor(Intercept,district_competitiveness)    -0.04      0.57    -0.94     0.95 1.00
                                        Bulk_ESS Tail_ESS
sd(Intercept)                               5614     3336
sd(district_competitiveness)                4127     2102
cor(Intercept,district_competitiveness)     7736     8624

Regression Coefficients:
                                            Estimate Est.Error l-95% CI u-95% CI Rhat
Intercept                                      -2.37      0.76    -3.90    -0.87 1.00
district_competitiveness                        1.29      1.05    -0.72     3.41 1.00
electoral_rulesSMD                             -0.76      1.00    -2.82     1.24 1.00
district_competitiveness:electoral_rulesSMD     3.08      1.45     0.17     5.95 1.00
                                            Bulk_ESS Tail_ESS
Intercept                                       5723     9078
district_competitiveness                        4809     6835
electoral_rulesSMD                              6075     8118
district_competitiveness:electoral_rulesSMD     4122     3063

Draws were sampled using sample(hmc). For each parameter, Bulk_ESS
and Tail_ESS are effective sample size measures, and Rhat is the potential
scale reduction factor on split chains (at convergence, Rhat = 1).</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href=""></a><span class="fu">summary</span>(stan_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Family: bernoulli 
  Links: mu = logit 
Formula: contacted ~ district_competitiveness * electoral_rules + (1 | district_id) + (1 + district_competitiveness | election_id) 
   Data: rainey (Number of observations: 5126) 
  Draws: 10 chains, each with iter = 4000; warmup = 2000; thin = 1;
         total post-warmup draws = 20000

Multilevel Hyperparameters:
~district_id (Number of levels: 567) 
              Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
sd(Intercept)     0.52      0.08     0.38     0.69 1.00     4820     8397

~election_id (Number of levels: 5) 
                                        Estimate Est.Error l-95% CI u-95% CI Rhat
sd(Intercept)                               0.62      0.53     0.02     1.97 1.00
sd(district_competitiveness)                0.88      0.69     0.04     2.65 1.00
cor(Intercept,district_competitiveness)    -0.04      0.57    -0.94     0.95 1.00
                                        Bulk_ESS Tail_ESS
sd(Intercept)                               5614     3336
sd(district_competitiveness)                4127     2102
cor(Intercept,district_competitiveness)     7736     8624

Regression Coefficients:
                                            Estimate Est.Error l-95% CI u-95% CI Rhat
Intercept                                      -2.37      0.76    -3.90    -0.87 1.00
district_competitiveness                        1.29      1.05    -0.72     3.41 1.00
electoral_rulesSMD                             -0.76      1.00    -2.82     1.24 1.00
district_competitiveness:electoral_rulesSMD     3.08      1.45     0.17     5.95 1.00
                                            Bulk_ESS Tail_ESS
Intercept                                       5723     9078
district_competitiveness                        4809     6835
electoral_rulesSMD                              6075     8118
district_competitiveness:electoral_rulesSMD     4122     3063

Draws were sampled using sample(hmc). For each parameter, Bulk_ESS
and Tail_ESS are effective sample size measures, and Rhat is the potential
scale reduction factor on split chains (at convergence, Rhat = 1).</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href=""></a>grid <span class="ot">&lt;-</span> rainey <span class="sc">%&gt;%</span></span>
<span id="cb80-2"><a href=""></a>  <span class="fu">select</span>(district_id, </span>
<span id="cb80-3"><a href=""></a>         election_id, </span>
<span id="cb80-4"><a href=""></a>         district_competitiveness, </span>
<span id="cb80-5"><a href=""></a>         electoral_rules)</span>
<span id="cb80-6"><a href=""></a></span>
<span id="cb80-7"><a href=""></a>p <span class="ot">&lt;-</span> <span class="fu">predictions</span>(stan_fit,</span>
<span id="cb80-8"><a href=""></a>                 <span class="at">newdata =</span> grid) <span class="sc">|&gt;</span></span>
<span id="cb80-9"><a href=""></a>  <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 5,126
Columns: 9
$ rowid                    &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, …
$ estimate                 &lt;dbl&gt; 0.696, 0.317, 0.563, 0.563, 0.568, 0.631, 0.631, 0.631,…
$ conf.low                 &lt;dbl&gt; 0.460, 0.141, 0.326, 0.326, 0.339, 0.396, 0.396, 0.396,…
$ conf.high                &lt;dbl&gt; 0.866, 0.563, 0.768, 0.768, 0.789, 0.816, 0.816, 0.816,…
$ district_id              &lt;chr&gt; "Canada; District 7", "Canada; District 4", "Canada; Di…
$ election_id              &lt;chr&gt; "Canada", "Canada", "Canada", "Canada", "Canada", "Cana…
$ district_competitiveness &lt;dbl&gt; 0.740, 0.420, 0.692, 0.692, 0.610, 0.742, 0.742, 0.742,…
$ electoral_rules          &lt;fct&gt; SMD, SMD, SMD, SMD, SMD, SMD, SMD, SMD, SMD, SMD, SMD, …
$ df                       &lt;dbl&gt; Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf, …</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href=""></a>p_typical <span class="ot">&lt;-</span> <span class="fu">predictions</span>(</span>
<span id="cb82-2"><a href=""></a>  stan_fit,</span>
<span id="cb82-3"><a href=""></a>  <span class="at">newdata =</span> grid, </span>
<span id="cb82-4"><a href=""></a>  <span class="at">re_formula =</span> <span class="sc">~</span> (<span class="dv">1</span> <span class="sc">+</span> district_competitiveness <span class="sc">|</span> election_id)</span>
<span id="cb82-5"><a href=""></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb82-6"><a href=""></a>  <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 5,126
Columns: 9
$ rowid                    &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, …
$ estimate                 &lt;dbl&gt; 0.659, 0.297, 0.607, 0.607, 0.510, 0.662, 0.662, 0.662,…
$ conf.low                 &lt;dbl&gt; 0.605, 0.229, 0.559, 0.559, 0.466, 0.607, 0.607, 0.607,…
$ conf.high                &lt;dbl&gt; 0.711, 0.372, 0.652, 0.652, 0.555, 0.713, 0.713, 0.713,…
$ district_id              &lt;chr&gt; "Canada; District 7", "Canada; District 4", "Canada; Di…
$ election_id              &lt;chr&gt; "Canada", "Canada", "Canada", "Canada", "Canada", "Cana…
$ district_competitiveness &lt;dbl&gt; 0.740, 0.420, 0.692, 0.692, 0.610, 0.742, 0.742, 0.742,…
$ electoral_rules          &lt;fct&gt; SMD, SMD, SMD, SMD, SMD, SMD, SMD, SMD, SMD, SMD, SMD, …
$ df                       &lt;dbl&gt; Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf, …</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href=""></a><span class="fu">ggplot</span>(p, <span class="fu">aes</span>(<span class="at">x =</span> district_competitiveness, <span class="at">y =</span> estimate)) <span class="sc">+</span></span>
<span id="cb84-2"><a href=""></a>  <span class="fu">facet_wrap</span>(<span class="fu">vars</span>(election_id)) <span class="sc">+</span></span>
<span id="cb84-3"><a href=""></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb84-4"><a href=""></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> p_typical, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="fl">1.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>

</div>

<img data-src="wk09-slides_files/figure-revealjs/unnamed-chunk-47-1.png" width="768" class="r-stretch"></section></section>

    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="wk09-slides_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="wk09-slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="wk09-slides_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="wk09-slides_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="wk09-slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="wk09-slides_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="wk09-slides_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="wk09-slides_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="wk09-slides_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="wk09-slides_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
    window.document.addEventListener("DOMContentLoaded", function (event) {
      const toggleBodyColorMode = (bsSheetEl) => {
        const mode = bsSheetEl.getAttribute("data-mode");
        const bodyEl = window.document.querySelector("body");
        if (mode === "dark") {
          bodyEl.classList.add("quarto-dark");
          bodyEl.classList.remove("quarto-light");
        } else {
          bodyEl.classList.add("quarto-light");
          bodyEl.classList.remove("quarto-dark");
        }
      }
      const toggleBodyColorPrimary = () => {
        const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
        if (bsSheetEl) {
          toggleBodyColorMode(bsSheetEl);
        }
      }
      toggleBodyColorPrimary();  
      const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
      tabsets.forEach(function(tabset) {
        const tabby = new Tabby('#' + tabset.id);
      });
      const isCodeAnnotation = (el) => {
        for (const clz of el.classList) {
          if (clz.startsWith('code-annotation-')) {                     
            return true;
          }
        }
        return false;
      }
      const onCopySuccess = function(e) {
        // button target
        const button = e.trigger;
        // don't keep focus
        button.blur();
        // flash "checked"
        button.classList.add('code-copy-button-checked');
        var currentTitle = button.getAttribute("title");
        button.setAttribute("title", "Copied!");
        let tooltip;
        if (window.bootstrap) {
          button.setAttribute("data-bs-toggle", "tooltip");
          button.setAttribute("data-bs-placement", "left");
          button.setAttribute("data-bs-title", "Copied!");
          tooltip = new bootstrap.Tooltip(button, 
            { trigger: "manual", 
              customClass: "code-copy-button-tooltip",
              offset: [0, -8]});
          tooltip.show();    
        }
        setTimeout(function() {
          if (tooltip) {
            tooltip.hide();
            button.removeAttribute("data-bs-title");
            button.removeAttribute("data-bs-toggle");
            button.removeAttribute("data-bs-placement");
          }
          button.setAttribute("title", currentTitle);
          button.classList.remove('code-copy-button-checked');
        }, 1000);
        // clear code selection
        e.clearSelection();
      }
      const getTextToCopy = function(trigger) {
          const codeEl = trigger.previousElementSibling.cloneNode(true);
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
      }
      const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
        text: getTextToCopy
      });
      clipboard.on('success', onCopySuccess);
      if (window.document.getElementById('quarto-embedded-source-code-modal')) {
        const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
          text: getTextToCopy,
          container: window.document.getElementById('quarto-embedded-source-code-modal')
        });
        clipboardModal.on('success', onCopySuccess);
      }
        var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
        var mailtoRegex = new RegExp(/^mailto:/);
          var filterRegex = new RegExp('/' + window.location.host + '/');
        var isInternal = (href) => {
            return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
        }
        // Inspect non-navigation links and adorn them if external
     	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
        for (var i=0; i<links.length; i++) {
          const link = links[i];
          if (!isInternal(link.href)) {
            // undo the damage that might have been done by quarto-nav.js in the case of
            // links that we want to consider external
            if (link.dataset.originalHref !== undefined) {
              link.href = link.dataset.originalHref;
            }
          }
        }
      function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
        const config = {
          allowHTML: true,
          maxWidth: 500,
          delay: 100,
          arrow: false,
          appendTo: function(el) {
              return el.closest('section.slide') || el.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'light-border',
          placement: 'bottom-start',
        };
        if (contentFn) {
          config.content = contentFn;
        }
        if (onTriggerFn) {
          config.onTrigger = onTriggerFn;
        }
        if (onUntriggerFn) {
          config.onUntrigger = onUntriggerFn;
        }
          config['offset'] = [0,0];
          config['maxWidth'] = 700;
        window.tippy(el, config); 
      }
      const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
      for (var i=0; i<noterefs.length; i++) {
        const ref = noterefs[i];
        tippyHover(ref, function() {
          // use id or data attribute instead here
          let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
          try { href = new URL(href).hash; } catch {}
          const id = href.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note) {
            return note.innerHTML;
          } else {
            return "";
          }
        });
      }
      const findCites = (el) => {
        const parentEl = el.parentElement;
        if (parentEl) {
          const cites = parentEl.dataset.cites;
          if (cites) {
            return {
              el,
              cites: cites.split(' ')
            };
          } else {
            return findCites(el.parentElement)
          }
        } else {
          return undefined;
        }
      };
      var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
      for (var i=0; i<bibliorefs.length; i++) {
        const ref = bibliorefs[i];
        const citeInfo = findCites(ref);
        if (citeInfo) {
          tippyHover(citeInfo.el, function() {
            var popup = window.document.createElement('div');
            citeInfo.cites.forEach(function(cite) {
              var citeDiv = window.document.createElement('div');
              citeDiv.classList.add('hanging-indent');
              citeDiv.classList.add('csl-entry');
              var biblioDiv = window.document.getElementById('ref-' + cite);
              if (biblioDiv) {
                citeDiv.innerHTML = biblioDiv.innerHTML;
              }
              popup.appendChild(citeDiv);
            });
            return popup.innerHTML;
          });
        }
      }
    });
    </script>
    

</body></html>