{
  "hash": "0e216eeeeaf0b0b9ed0234dbdde9ae6a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 3 Exercises\"\ndistributed: 2026-09-08\nshow-hints: true\n---\n\n\n\nCTK things to add: references to notes as hints (i.e., links to specific sessions.), references to other questions if there's an important link. missing solution, check that notation in exercises matches notes.\n\n\n\n\n\n\n\n## Mean v. median {ref=\"mean-median\"}\n\nSuppose $y$ follows a normal model with mean $\\mu$ and SD $\\sigma$. Then $\\operatorname{avg}(y)$ is the *best* unbiased estimator of $\\mu$. But $\\operatorname{median}(y)$ is also an unbiased estimator of $\\mu$. Use a Monte Carlo simulation to show how $\\operatorname{avg}(y)$ is a better estimator of $\\mu$ than $\\operatorname{median}(y)$.\n\n::: hint\n\nSee [Section 4.2](https://pos5747.github.io/notes/wk03/01-sampling-distribution.html#example-normal-model) of the notes for the sampling distribution of $\\operatorname{avg}(y)$ under a normal model, and [Section 4.1](https://pos5747.github.io/notes/wk03/01-sampling-distribution.html#example-the-toothpaste-cap-problem) for simulating a sampling distribution.\n\n:::\n\n::: sol\n\nThe average is better because the SE of the average estimator is smaller than the SE of the median estimator. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# parameters\nmu <- 0\nsigma <- 1\nN <- 10 # sample size of y\nn_mc_sims <- 10000   # monte carlo repetitions\n\n# containers\nmean_hat <- numeric(n_mc_sims)\nmedian_hat <- numeric(n_mc_sims)\n\n# simulate many data sets y; compute and store estimates for each\nfor (i in 1:n_mc_sims) {\n  y <- rnorm(N, mean = mu, sd = sigma)\n  mean_hat[i]   <- mean(y)\n  median_hat[i] <- median(y)\n}\n\nsd(mean_hat)  # se of avg estimator\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3212223\n```\n\n\n:::\n\n```{.r .cell-code}\nsd(median_hat)  # se of median estimator\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3767166\n```\n\n\n:::\n:::\n\n\n\n:::\n\n\n## Asymptotics as approximations {ref=\"asymptotics\"}\n\nFor a large number of repetitions, do the following:\n\n1. Simulate a data set $y$ with $N = 50$ observations from the exponential distribution with $\\lambda = 2$.\n1. Compute the point estimate $\\hat{\\lambda} = \\frac{1}{\\text{avg}(y)}$. Store this point estimate.\n\nCompare the mean and SD of the simulated point estimates to the theoretical mean and SD of the *asymptotic* sampling distribution. We care, of course, about the *actual* sampling distribution, but we have to use an *asymptotic approximation* in practice. Discuss the differences and whether they seem important or unimportant.\n\nOptional: Go beyond the mean and SD. Use a table of quantiles of the simulated point estimates and theoretical distribution and/or plots of the CDFs to compare the simulated (i.e., actual) and theoretical distributions.\n\n::: hint\n\nSee [Section 6.2](https://pos5747.github.io/notes/wk03/03-fisher-information-matrix.html#theory) of the notes for the asymptotic normal approximation, including the callout there on treating asymptotic results as approximations. [Section 4.4.2](https://pos5747.github.io/notes/wk03/01-sampling-distribution.html#example-exponential-model) simulates the actual sampling distribution of $\\hat{\\lambda}$.\n\n:::\n\n::: hint\n\nFor the exponential model, the asymptotic sampling distribution of $\\hat{\\lambda}$ is $\\hat{\\lambda} \\overset{a}{\\sim} N\\left(\\lambda,\\; \\frac{\\lambda^2}{N}\\right)$. \n\n:::\n\n::: sol\n\n**Solution**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load packages\nlibrary(tinytable)\noptions(tinytable_tt_digits = 3)\noptions(tinytable_latex_placement = \"H\")\n\n# set seed for reproducibility\nset.seed(1234)\n\n# parameters\nlambda <- 2\nN <- 50  # sample size\nR <- 10000  # number of mc repetitions\n\n# loop\nlambda_hat <- numeric(R)  # container to store results\nfor (i in 1:R) {\n y <-  rexp(N, rate = lambda)  # simulate data set\n lambda_hat[i] <- 1/mean(y)  # compute and store estimate\n}\n\n# empirical summaries\nemp_mean <- mean(lambda_hat)\nemp_sd   <- sd(lambda_hat)\n\n# asymptotic\nasy_mean <- lambda\nasy_sd   <- sqrt(lambda^2 / N)\n\n# data frame of results\nres <- data.frame(\n  Statistic   = c(\"Mean\", \"SD\"),\n  Empirical   = c(emp_mean, emp_sd),\n  Asymptotic  = c(asy_mean, asy_sd)\n)\n\n# print table\ntt(\n  res,\n  digits  = 3,   \n  align   = \"lrr\",\n) \n```\n\n::: {.cell-output-display}\n\n```{=html}\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_ff870h78qxf48hoyfdkg = TinyTable.createTableFunctions(\"tinytable_ff870h78qxf48hoyfdkg\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '2', j: 1 }, { i: '2', j: 2 }, { i: '2', j: 3 } ], css_id: 'tinytable_css_y65ikyrtx4xwn4x3uwob',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 } ], css_id: 'tinytable_css_sv52riyasbwi5jq907r9',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_ff870h78qxf48hoyfdkg.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_ff870h78qxf48hoyfdkg td.tinytable_css_y65ikyrtx4xwn4x3uwob, #tinytable_ff870h78qxf48hoyfdkg th.tinytable_css_y65ikyrtx4xwn4x3uwob {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_ff870h78qxf48hoyfdkg td.tinytable_css_sv52riyasbwi5jq907r9, #tinytable_ff870h78qxf48hoyfdkg th.tinytable_css_sv52riyasbwi5jq907r9 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_ff870h78qxf48hoyfdkg\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Statistic</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Empirical</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Asymptotic</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">Mean</td>\n                  <td data-row=\"1\" data-col=\"2\">2.04</td>\n                  <td data-row=\"1\" data-col=\"3\">2</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">SD</td>\n                  <td data-row=\"2\" data-col=\"2\">0.293</td>\n                  <td data-row=\"2\" data-col=\"3\">0.283</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# quantile comparison table\nprobs <- c(0.01, 0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99)\nemp_q <- quantile(lambda_hat, probs = probs)\nasy_q <- qnorm(probs, mean = asy_mean, sd = asy_sd)\n\n# combine into data frame\nquant <- data.frame(\n  p = probs,\n  empirical = emp_q,\n  asymptotic = asy_q,\n  difference = emp_q - asy_q\n)\n\n# make table\ntt(\n  quant,\n  digits  = 3,   # 3 decimals for numbers\n  align   = \"lrr\",\n)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_sipfapu3aqckv54jfi7d = TinyTable.createTableFunctions(\"tinytable_sipfapu3aqckv54jfi7d\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '9', j: 1 }, { i: '9', j: 2 }, { i: '9', j: 3 }, { i: '9', j: 4 } ], css_id: 'tinytable_css_nknol8cy3joard2r5d3k',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 } ], css_id: 'tinytable_css_fh0pax0fowz570eqx13q',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_sipfapu3aqckv54jfi7d.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_sipfapu3aqckv54jfi7d td.tinytable_css_nknol8cy3joard2r5d3k, #tinytable_sipfapu3aqckv54jfi7d th.tinytable_css_nknol8cy3joard2r5d3k {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_sipfapu3aqckv54jfi7d td.tinytable_css_fh0pax0fowz570eqx13q, #tinytable_sipfapu3aqckv54jfi7d th.tinytable_css_fh0pax0fowz570eqx13q {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_sipfapu3aqckv54jfi7d\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">p</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">empirical</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">asymptotic</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">difference</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">0.01</td>\n                  <td data-row=\"1\" data-col=\"2\">1.47</td>\n                  <td data-row=\"1\" data-col=\"3\">1.34</td>\n                  <td data-row=\"1\" data-col=\"4\">0.1302</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">0.05</td>\n                  <td data-row=\"2\" data-col=\"2\">1.61</td>\n                  <td data-row=\"2\" data-col=\"3\">1.53</td>\n                  <td data-row=\"2\" data-col=\"4\">0.073</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">0.1</td>\n                  <td data-row=\"3\" data-col=\"2\">1.69</td>\n                  <td data-row=\"3\" data-col=\"3\">1.64</td>\n                  <td data-row=\"3\" data-col=\"4\">0.0503</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\">0.25</td>\n                  <td data-row=\"4\" data-col=\"2\">1.83</td>\n                  <td data-row=\"4\" data-col=\"3\">1.81</td>\n                  <td data-row=\"4\" data-col=\"4\">0.0242</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">0.5</td>\n                  <td data-row=\"5\" data-col=\"2\">2.01</td>\n                  <td data-row=\"5\" data-col=\"3\">2</td>\n                  <td data-row=\"5\" data-col=\"4\">0.013</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\">0.75</td>\n                  <td data-row=\"6\" data-col=\"2\">2.22</td>\n                  <td data-row=\"6\" data-col=\"3\">2.19</td>\n                  <td data-row=\"6\" data-col=\"4\">0.028</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">0.9</td>\n                  <td data-row=\"7\" data-col=\"2\">2.43</td>\n                  <td data-row=\"7\" data-col=\"3\">2.36</td>\n                  <td data-row=\"7\" data-col=\"4\">0.0628</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\">0.95</td>\n                  <td data-row=\"8\" data-col=\"2\">2.56</td>\n                  <td data-row=\"8\" data-col=\"3\">2.47</td>\n                  <td data-row=\"8\" data-col=\"4\">0.0995</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">0.99</td>\n                  <td data-row=\"9\" data-col=\"2\">2.83</td>\n                  <td data-row=\"9\" data-col=\"3\">2.66</td>\n                  <td data-row=\"9\" data-col=\"4\">0.176</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# load packages\nlibrary(tidyverse)\n\n# plot ecdf and asymptotic distribution\ngg_data <- data.frame(lambda_hat = lambda_hat)\nggplot(gg_data, aes(x = lambda_hat)) +\n  stat_ecdf() +\n  stat_function(fun = function(x) pnorm(x, \n                                        mean = asy_mean, \n                                        sd = asy_sd), \n                color = \"red\") +\n  labs(\n    title = \"ECDF of Simulated ML Estimates vs Asymptotic Sampling Distribution\",\n    x = expression(hat(lambda)),\n    y = \"Cumulative Probability\"\n  )\n```\n\n::: {.cell-output-display}\n![](wk03-exercises_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n\n*Discussion*\n\n- **Center (bias).** The empirical mean of $\\hat{\\lambda}$ is about 2.04, compared to the true $\\lambda=2.000$. This is a difference of roughly 2%. At $N=50$, this upward bias is present but quite small.\n- **Spread.** The empirical SD is about 0.293, while the asymptotic SD is 0.283. This difference is 3.7% of the asymptotic value, so the asymptotic variance formula provides an accurate description of variability.\n- **Quantiles and tails.** For the median, the empirical value is 2.013 compared to an asymptotic prediction of 2. At the 1% and 99% quantiles, the differences are about 0.13 and 0.176, respectively, which correspond to differences of only a few percent relative to the true scale. The ECDF and normal CDF curves are nearly indistinguishable except in the tails.\n- **Bottom line.** With $N=50$, the asymptotic normal distribution closely matches the finite-sample distribution of $\\hat{\\lambda}$. The bias is about 2%, the SD differs by about 4%, and quantile differences are small. The asymptotic normal approximation is accurate and reliable for practical use at this sample size.\n\n:::\n\n## German Tank Problem {ref=\"german-tank\"}\n\nSuppose a discrete uniform distribution from 0 to $K$. The pmf is $f(x; K) = \\frac{1}{K + 1}, \\quad x \\in \\{0, 1, \\ldots, K\\}$. The ML estimator is $\\hat K = \\max(y)$. The method of moments estimator is $\\hat K = 2 \\times \\operatorname{avg}(y)$. Use a Monte Carlo simulation to evaluate bias and variance of each estimator for a small ($N = 3$), medium ($N = 25$), and large sample size ($N = 1,000$). Which estimator do you recommend?\n\n*Note:* This model violates several of the regularity conditions, so the usual asymptotic guarantees do not hold.\n\n::: hint\n\nSee [Section 4.3](https://pos5747.github.io/notes/wk03/01-sampling-distribution.html#bias) of the notes for bias and [Section 1.6](https://pos5747.github.io/notes/wk02/01-maximum-likelihood.html#principle-method-of-moments) for the method of moments.\n\n:::\n\n::: hint\n\n[mean-median]{.ex-ref} similarly compares two estimators. However, the mean and median are both unbiased in that case, so only the variance matters.\n\n:::\n\n::: sol\n\n**Solution**\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load packages\nlibrary(tinytable)\nlibrary(dplyr)\noptions(tinytable_tt_digits = 3)\noptions(tinytable_latex_placement = \"H\")\n\n# set seed for reproducibility\nset.seed(1234)\n\n# parameters\nK  <- 100               # true K\nNs <- c(3, 25, 1000)    # sample sizes\nR  <- 10000             # number of mc repetitions\n\n# container: list of data frames\nres_list <- list()\n\n# loop over sample sizes\nfor (N in Ns) {\n  K_hat_mle <- numeric(R)   # container for MLE\n  K_hat_mom <- numeric(R)   # container for MOM\n  \n  for (i in 1:R) {\n    y <- sample(0:K, N, replace = TRUE)  # simulate data set\n    K_hat_mle[i] <- max(y)                # MLE\n    K_hat_mom[i] <- 2 * mean(y)           # MOM\n  }\n  \n  # empirical summaries\n  emp_mean_mle <- mean(K_hat_mle)\n  emp_sd_mle   <- sd(K_hat_mle)\n  emp_mean_mom <- mean(K_hat_mom)\n  emp_sd_mom   <- sd(K_hat_mom)\n  \n  # store results for this N\n  res_list[[as.character(N)]] <- data.frame(\n    N          = N,\n    Estimator  = c(\"MLE\", \"MOM\"),\n    Mean       = c(emp_mean_mle, emp_mean_mom),\n    SD         = c(emp_sd_mle,   emp_sd_mom),\n    Bias       = c(emp_mean_mle - K, emp_mean_mom - K),\n    MSE        = c(mean((K_hat_mle - K)^2), mean((K_hat_mom - K)^2))\n  )\n}\n\n# combine all into one data frame\nres <- bind_rows(res_list)\n\n# print table\ntt(\n  res,\n  digits = 5,\n  align  = \"lrrrrr\",\n)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_vk6g8sd438ntbq9yb66c = TinyTable.createTableFunctions(\"tinytable_vk6g8sd438ntbq9yb66c\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '6', j: 1 }, { i: '6', j: 2 }, { i: '6', j: 3 }, { i: '6', j: 4 }, { i: '6', j: 5 }, { i: '6', j: 6 } ], css_id: 'tinytable_css_kga1lsk5cicx3kk56hee',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 }, { i: '0', j: 5 }, { i: '0', j: 6 } ], css_id: 'tinytable_css_097rl0akingc300565l3',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_vk6g8sd438ntbq9yb66c.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_vk6g8sd438ntbq9yb66c td.tinytable_css_kga1lsk5cicx3kk56hee, #tinytable_vk6g8sd438ntbq9yb66c th.tinytable_css_kga1lsk5cicx3kk56hee {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_vk6g8sd438ntbq9yb66c td.tinytable_css_097rl0akingc300565l3, #tinytable_vk6g8sd438ntbq9yb66c th.tinytable_css_097rl0akingc300565l3 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_vk6g8sd438ntbq9yb66c\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">N</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Estimator</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Mean</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">SD</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"5\">Bias</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"6\">MSE</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">3</td>\n                  <td data-row=\"1\" data-col=\"2\">MLE</td>\n                  <td data-row=\"1\" data-col=\"3\">75.055</td>\n                  <td data-row=\"1\" data-col=\"4\">19.7364</td>\n                  <td data-row=\"1\" data-col=\"5\">-24.9454</td>\n                  <td data-row=\"1\" data-col=\"6\">1011.7588</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">3</td>\n                  <td data-row=\"2\" data-col=\"2\">MOM</td>\n                  <td data-row=\"2\" data-col=\"3\">99.952</td>\n                  <td data-row=\"2\" data-col=\"4\">33.59</td>\n                  <td data-row=\"2\" data-col=\"5\">-0.048467</td>\n                  <td data-row=\"2\" data-col=\"6\">1128.1803</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">25</td>\n                  <td data-row=\"3\" data-col=\"2\">MLE</td>\n                  <td data-row=\"3\" data-col=\"3\">96.665</td>\n                  <td data-row=\"3\" data-col=\"4\">3.6737</td>\n                  <td data-row=\"3\" data-col=\"5\">-3.3353</td>\n                  <td data-row=\"3\" data-col=\"6\">24.6191</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\">25</td>\n                  <td data-row=\"4\" data-col=\"2\">MOM</td>\n                  <td data-row=\"4\" data-col=\"3\">100.191</td>\n                  <td data-row=\"4\" data-col=\"4\">11.7466</td>\n                  <td data-row=\"4\" data-col=\"5\">0.191144</td>\n                  <td data-row=\"4\" data-col=\"6\">138.0057</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">1000</td>\n                  <td data-row=\"5\" data-col=\"2\">MLE</td>\n                  <td data-row=\"5\" data-col=\"3\">100</td>\n                  <td data-row=\"5\" data-col=\"4\">0</td>\n                  <td data-row=\"5\" data-col=\"5\">0</td>\n                  <td data-row=\"5\" data-col=\"6\">0</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\">1000</td>\n                  <td data-row=\"6\" data-col=\"2\">MOM</td>\n                  <td data-row=\"6\" data-col=\"3\">99.993</td>\n                  <td data-row=\"6\" data-col=\"4\">1.8362</td>\n                  <td data-row=\"6\" data-col=\"5\">-0.007073</td>\n                  <td data-row=\"6\" data-col=\"6\">3.3712</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\nNotice that the ML estimator is severely biased downward in small samples. But it also has a much smaller variance. It's not clear how to trade off these two. However, it's worth noting that the severely biased ML estimator has a *smaller* mean-squared error.\n\n*Which estimator do you recommend?* There isn't an easy right answer here, just make an argument for one or the other from *principles* (e.g., bias, variance, MSE, or others).\n\n:::\n\n## Jensen's Inequality {ref=\"jensen\"}\n\nSuppose the usual exponential model. The ML estimate of the rate $\\lambda$ is $\\hat{\\lambda} = \\frac{1}{\\text{avg}(y)}$. Using the invariance property, the ML estimate of the mean $\\frac{1}{\\lambda}$ is $\\hat{\\mu} = \\frac{1}{\\hat{\\lambda}}$. Show analytically that the ML estimate of the mean is unbiased, while the ML estimate of the rate is biased. \n\n**Jensen's Inequality.**  If $g$ is a convex function and $X$ is a random variable with $\\mathbb E[X]$ finite, then $\\mathbb E\\big[g(X)\\big] \\ge g \\big(\\mathbb E[X]\\big)$,\nwith strict inequality unless $X$ is degenerate (i.e., constant almost surely).\n\n::: hint\n\nSee [Section 4.3.2](https://pos5747.github.io/notes/wk03/01-sampling-distribution.html#example-exponential-distribution) of the notes.\n\n:::\n\n::: hint\n\nFirst show that $\\hat{\\mu}$ is unbiased. Then use Jensen's inequality to show that $\\hat{\\lambda}$ is biased upward. You do not need to find the size of the bias, just use Jensen's inequality to show that the ML estimate of the rate is biased. To use Jensen's inequality, let $g(x)=1/x$, and notice that $g(x)$ is convex on $(0,\\infty)$ (since $g''(x)=2/x^3>0$).\n\n:::\n\n::: sol\n\n**Solution**\n\n*1) Unbiasedness of the ML estimate of the mean*\n\n$\\hat{\\mu} = \\text{avg}(y) = \\frac{1}{N} \\sum_{i = 1}^N y_i$ is the sample mean of iid observations. $\\mathbb E[y_i]=\\frac{1}{\\lambda}$. Then \n\n$$\n\\begin{aligned}\n\\mathbb E[\\hat\\mu] \n  &= \\mathbb E \\left[ \\frac{1}{N} \\sum_{i = 1}^N y_i \\right] && \\text{(definition of $\\hat\\mu$)}\\\\\n  &= \\frac{1}{N} \\cdot \\mathbb E \\left[\\sum_{i = 1}^N y_i \\right] && \\text{(linearity)}\\\\\n  &= \\frac{1}{N} \\cdot \\left[\\sum_{i = 1}^N \\mathbb E (y_i) \\right] && \\text{(sum of expectations)}\\\\\n  &= \\frac{1}{N} \\cdot \\left[\\sum_{i = 1}^N \\frac{1}{\\lambda} \\right] && \\text{(each has mean $1/\\lambda$)}\\\\\n  &= \\frac{1}{N} \\cdot \\left[N \\cdot \\frac{1}{\\lambda} \\right] && \\text{(sum $N$ identical terms)}\\\\\n  &= \\frac{1}{\\lambda} && \\text{(simplify)}\\\\\n  &= \\mu && \\text{(definition of $\\mu$)}\n\\end{aligned}\n$$\n\nBecause $\\mathbb E(\\hat\\mu) = \\mu$, $\\hat{\\mu}$ is an unbiased estimate of the mean.\n\n*2) Bias of the ML estimate of the rate*\n\n$\\hat{\\lambda} = \\dfrac{1}{\\text{avg}(y)} = \\left(\\dfrac{1}{N}\\sum_{i=1}^N y_i\\right)^{-1}$. Let $g(x)=1/x$, and notice that $g(x)$ is convex on $(0,\\infty)$ (since $g''(x)=2/x^3>0$). Then\n\n$$\n\\begin{aligned}\n\\mathbb E[\\hat{\\lambda}]\n  &= \\mathbb E\\left[ \\frac{1}{\\text{avg}(y)} \\right] && \\text{(definition of $\\hat{\\lambda}$)}\\\\\n  &= \\mathbb E\\left[g\\big(\\text{avg}(y)\\big)\\right] && \\text{(definition of $g$ above)}\\\\\n  &> g\\big(\\mathbb E[\\text{avg}(y)]\\big) && \\text{(Jensen's inequality, $g$ convex)}\\\\\n  &= \\frac{1}{\\mathbb E[\\text{avg}(y)]} && \\text{(apply $g$)}\\\\\n  &= \\frac{1}{\\frac{1}{N}\\sum_{i=1}^N \\mathbb E(y_i)} && \\text{(linearity of expectation)}\\\\\n  &= \\frac{1}{\\frac{1}{N}\\sum_{i=1}^N \\frac{1}{\\lambda}} && \\text{(each $y_i$ has mean $1/\\lambda$)}\\\\\n  &= \\frac{1}{\\frac{1}{N}\\cdot N \\cdot \\frac{1}{\\lambda}} && \\text{(sum of $N$ identical terms)}\\\\\n  &= \\lambda && \\text{(simplify)}\n\\end{aligned}\n$$\n\nSince the inequality is strict for finite $N$ (the distribution of $\\text{avg}(y)$ is non-degenerate), $\\mathbb E[\\hat{\\lambda}] > \\lambda$. Thus, the ML estimate of the **rate** is biased upward.\n\n:::\n\n\n## Poisson {ref=\"poisson\"}\n\nSuppose a Poisson model. The ML estimate of the mean parameter $\\lambda$ is $\\hat\\lambda = \\text{avg}(y)$. Find an estimate of the SE using the observed Fisher information.\n\n::: hint\n\nSee [Section 6.2](https://pos5747.github.io/notes/wk03/03-fisher-information-matrix.html#theory) of the notes for the four steps that turn the log-likelihood into an SE estimate, and [Section 6.6](https://pos5747.github.io/notes/wk03/03-fisher-information-matrix.html#example-exponential-model) for those steps worked out for the exponential model.\n\n:::\n\n::: sol\n\n**Solution**\n\nThe log-likelihood is $\\ell(\\lambda) = \\sum_{i=1}^N \\big[y_i \\log \\lambda - \\lambda - \\log(y_i!)\\big]$.\n\nFirst, find the second derivative with respect to $\\lambda$.\n\n$$\n\\begin{aligned}\n\\ell(\\lambda)\n&= \\sum_{i=1}^N \\big[y_i \\log \\lambda - \\lambda - \\log(y_i!)\\big]\n&& \\text{Poisson log-likelihood} \\\\[6pt]\n\\frac{\\partial \\ell}{\\partial \\lambda}\n&= \\sum_{i=1}^N \\left( y_i \\cdot \\frac{1}{\\lambda} - 1 - 0 \\right)\n&& \\text{use } \\frac{d}{d\\lambda}\\log \\lambda = \\frac{1}{\\lambda},\\; \\frac{d}{d\\lambda}(-\\lambda) = -1,\\; \\log(y_i!) \\text{ is constant} \\\\[6pt]\n&= \\sum_{i=1}^N \\left( \\frac{y_i}{\\lambda} - 1 \\right)\n= \\frac{1}{\\lambda} \\sum_{i=1}^N y_i - N\n&& \\text{collect terms} \\\\[10pt]\n\\frac{\\partial^2 \\ell}{\\partial \\lambda^2}\n&= \\frac{\\partial}{\\partial \\lambda} \\left( \\frac{1}{\\lambda} \\sum_{i=1}^N y_i - N \\right)\n&& \\text{differentiate again} \\\\[6pt]\n&= \\sum_{i=1}^N \\left( - \\frac{y_i}{\\lambda^2} \\right) - 0\n&& \\text{use } \\frac{d}{d\\lambda}\\left(\\frac{1}{\\lambda}\\right) = -\\frac{1}{\\lambda^2} \\text{, } N \\text{ is constant} \\\\[6pt]\n&= - \\sum_{i=1}^N \\frac{y_i}{\\lambda^2}.\n\\end{aligned}\n$$\n\nThe observed Fisher information is\n\n$$\n\\mathcal I_{\\text{obs}}(\\lambda)\n= -\\frac{\\partial^2 \\ell}{\\partial \\lambda^2}\n= \\sum_{i=1}^N \\frac{y_i}{\\lambda^2}.\n$$\n\nAsymptotically, $\\operatorname{Var}(\\hat\\lambda) \\approx \\mathcal I_{\\text{obs}}(\\lambda)^{-1}$.^[Rather than \"approximately equals\" ($\\approx$), it's more technically correct to write \"asymptotically equals.\" However, we treat \"asymptotically equals\" to mean \"approximately\" in practice. Given the practical orientation of the course, it seems better to write \"approximately\" here.]\n\nTo find the estimate of the SE, replace $\\lambda$ with $\\hat\\lambda$:\n\n$$\n\\widehat{\\operatorname{SE}}(\\hat\\lambda)\n= \\sqrt{\\mathcal I_{\\text{obs}}(\\hat\\lambda)^{-1}}\n= \\sqrt{\\frac{\\hat\\lambda^2}{\\sum_{i=1}^N y_i}}\n= \\sqrt{\\frac{\\hat\\lambda^2}{N \\hat\\lambda}}\n= \\sqrt{\\frac{\\hat\\lambda}{N}}\n= \\sqrt{\\frac{\\operatorname{avg}(y)}{N}},\n$$\n\nsince $\\sum_{i=1}^N y_i = N \\hat\\lambda$.\n\n:::\n\n## `operations` {ref=\"operations\"}\n\nThe code below loads the number of enforcement operations for each district in Bogota from Holland (2015) from the {crdata} package. See `?crdata::holland2015` for details. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load holland2015 data set from crdata package\nholland2015 <- crdata::holland2015 \n\n# get operations in bogota only\nops <- holland2015$operations[holland2015$city == \"bogota\"]\n\n# print\nops\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 15 10 15 20  8  4  8 16  4 28  2  8  4  4  4  4  8  3  4\n```\n\n\n:::\n:::\n\n\n\n**A Poisson model.**\n\n**Task:** Using the Poisson estimators from [poisson]{.ex-ref}, find the ML estimate and SE estimate of $\\lambda$ for a Poisson model. \n\nBut before moving on, compare the SD of the predictive distribution (no need to simulate, it depends only and directly on $\\lambda$) and the SD of the data. Why might this be a problem for the SE estimate?\n\n::: hint\n\nSee [Section 3.1](https://pos5747.github.io/notes/wk02/03-predictive-distribution.html#example-poisson-distribution) of the notes for the predictive distribution of a Poisson model. [Section A.5](https://pos5747.github.io/notes/appendicies/999-distributions.html#poisson-distribution) gives its SD.\n\n:::\n\n::: sol\n\n**Solution.**\n\nFirst, fit the Poisson model and compute the ML estimate and SE of $\\lambda$ without using `optim()`, following the observed-information derivation above. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load packages\nlibrary(tidyverse)\nlibrary(tinytable)\n\n# load holland2015 data set from crdata package\nholland2015 <- crdata::holland2015 \n\n# get operations in bogota only\nops <- holland2015$operations[holland2015$city == \"bogota\"]\n\n# estimate lambda with ml\nN <- length(ops)\nlambda_hat_pois <- mean(ops); lambda_hat_pois\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 8.894737\n```\n\n\n:::\n\n```{.r .cell-code}\nse_lambda_hat_pois  <- sqrt(lambda_hat_pois / N); se_lambda_hat_pois\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6842105\n```\n\n\n:::\n\n```{.r .cell-code}\n# compare predictive SD to data SD\nsd_pred_pois <- sqrt(lambda_hat_pois)   # predictive SD under Poisson\nsd_data      <- sd(ops)                 # empirical SD\n\n# summarize results in a small table\nres_pois <- data.frame(\n  Statistic = c(\"Predictive SD \", \"Data SD\"),\n  Value     = c(sd_pred_pois, sd_data)\n)\n\ntt(res_pois, digits = 3, align = \"lr\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_xbx33nsh0kuy95teq0bz = TinyTable.createTableFunctions(\"tinytable_xbx33nsh0kuy95teq0bz\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '2', j: 1 }, { i: '2', j: 2 } ], css_id: 'tinytable_css_p5vo8uiqk3w3kdv2wd7b',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 } ], css_id: 'tinytable_css_m21wapgtbpj4ir25pafl',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_xbx33nsh0kuy95teq0bz.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_xbx33nsh0kuy95teq0bz td.tinytable_css_p5vo8uiqk3w3kdv2wd7b, #tinytable_xbx33nsh0kuy95teq0bz th.tinytable_css_p5vo8uiqk3w3kdv2wd7b {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_xbx33nsh0kuy95teq0bz td.tinytable_css_m21wapgtbpj4ir25pafl, #tinytable_xbx33nsh0kuy95teq0bz th.tinytable_css_m21wapgtbpj4ir25pafl {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_xbx33nsh0kuy95teq0bz\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Statistic</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Value</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">Predictive SD</td>\n                  <td data-row=\"1\" data-col=\"2\">2.98</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">Data SD</td>\n                  <td data-row=\"2\" data-col=\"2\">6.94</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\nThis poses a big problem for our SE estimate. The SE estimate depends on the variance. If the variance is wildly underestimated, the the SE will be wildly underestimated as well.\n\n:::\n\n## Exponential {ref=\"exponential\"}\n\nSuppose an exponential model of $y$. We know that the ML estimate of the rate $\\lambda$ is $\\hat \\lambda = \\frac{1}{\\operatorname{avg}(y)}$. By the invariance property, the ML estimate of the mean $\\mu = \\frac{1}{\\lambda}$ is $\\hat \\mu = \\frac{1}{\\hat \\lambda}$. \n\n1. Use the observed Fisher information to find a closed-form estimate of the SE of $\\hat \\lambda$. \n1. Then use the delta method to find a closed-form estimate of the SE of $\\hat \\mu$.\n\n::: hint\n\nSee [Section 6.6](https://pos5747.github.io/notes/wk03/03-fisher-information-matrix.html#example-exponential-model) of the notes for the first part and [Section 7.2](https://pos5747.github.io/notes/wk03/04-delta-method.html#poisson-from-lambda-to-sd) for the delta method with one parameter.\n\n:::\n\n::: hint\n\nFor an exponential model with rate $\\lambda$, the density is\n$f(y; \\lambda) = \\lambda e^{-\\lambda y}$, so\n$\\ell(\\lambda) = \\sum \\big(\\log \\lambda - \\lambda y_i\\big)$.\n\n:::\n\n::: sol\n\n**Solution**\n\nThe log-likelihood is\n$$\n\\ell(\\lambda) \\;=\\; \\sum_{i=1}^N \\big[\\log \\lambda \\;-\\; \\lambda y_i\\big].\n$$\n\nFirst, find the second derivative with respect to $\\lambda$.\n\n$$\n\\begin{aligned}\n\\ell(\\lambda)\n&= \\sum_{i=1}^N \\big[\\log \\lambda - \\lambda y_i\\big]\n&& \\text{Exponential log-likelihood} \\\\[6pt]\n\\frac{\\partial \\ell}{\\partial \\lambda}\n&= \\sum_{i=1}^N \\left(\\frac{1}{\\lambda} - y_i\\right)\n&& \\text{use } \\frac{d}{d\\lambda}\\log \\lambda = \\frac{1}{\\lambda},\\; \\frac{d}{d\\lambda}(-\\lambda y_i) = -y_i \\\\[6pt]\n&= \\frac{N}{\\lambda} \\;-\\; \\sum_{i=1}^N y_i\n&& \\text{collect terms} \\\\[10pt]\n\\frac{\\partial^2 \\ell}{\\partial \\lambda^2}\n&= \\frac{\\partial}{\\partial \\lambda}\\!\\left(\\frac{N}{\\lambda} - \\sum_{i=1}^N y_i\\right)\n&& \\text{differentiate again} \\\\[6pt]\n&= -\\,\\frac{N}{\\lambda^2} \\;-\\; 0\n&& \\text{use } \\frac{d}{d\\lambda}\\!\\left(\\frac{1}{\\lambda}\\right) = -\\frac{1}{\\lambda^2},\\; \\sum y_i \\text{ is constant}.\n\\end{aligned}\n$$\n\nThe observed Fisher information is\n$$\n\\mathcal I_{\\text{obs}}(\\lambda)\n= -\\frac{\\partial^2 \\ell}{\\partial \\lambda^2}\n= \\frac{N}{\\lambda^2}.\n$$\n\nTo find the estimate of the SE, replace $\\lambda$ with $\\hat\\lambda$:\n$$\n\\widehat{\\operatorname{SE}}(\\hat\\lambda)\n= \\sqrt{\\mathcal I_{\\text{obs}}(\\hat\\lambda)^{-1}}\n= \\sqrt{\\frac{\\hat\\lambda^{2}}{N}}\n= \\frac{\\hat\\lambda}{\\sqrt{N}}\n= \\frac{1}{\\sqrt{N}\\,\\operatorname{avg}(y)}.\n$$\n\nNow suppose we use the invariance property to obtain $\\hat\\mu = \\dfrac{1}{\\hat\\lambda}$. Then we can use the delta method to estimate the SE with $\\tau(\\lambda) = \\dfrac{1}{\\lambda}$.\n\nThe first derivative is $\\tau'(\\lambda) = -\\frac{1}{\\lambda^2}$.\n\nPlugging in, we have\n$$\n\\begin{aligned}\n\\widehat{\\operatorname{Var}}(\\hat\\mu)\n  &\\approx \\big[\\tau'(\\hat\\lambda)\\big]^2 \\cdot \\widehat{\\operatorname{Var}}(\\hat\\lambda)\n   \\;=\\; \\left(\\frac{1}{\\hat\\lambda^2}\\right)^2 \\cdot \\frac{\\hat\\lambda^{2}}{N} \\\\[6pt]\n  &= \\frac{1}{N\\,\\hat\\lambda^{2}}.\n\\end{aligned}\n$$\n\nAnd the standard error is\n$$\n\\widehat{\\mathrm{SE}}(\\hat\\mu)\n\\;\\approx\\; \\sqrt{\\frac{1}{N\\,\\hat\\lambda^{2}}}\n\\;=\\; \\frac{1}{\\sqrt{N}\\,\\hat\\lambda}\n\\;=\\; \\frac{\\operatorname{avg}(y)}{\\sqrt{N}}.\n$$\n\n:::\n\n## Delta method, by hand {ref=\"delta-by-hand\"}\n\nSuppose you obtain the ML estimate $\\hat\\theta=(\\hat a,\\hat b)=(2,\\,1)$ with an estimated covariance matrix of\n  $$\n  \\widehat{\\mathrm{Var}}(\\hat\\theta)\n  =\n  \\widehat{\\mathrm{Var}}(\\hat a,\\hat b)\n  =\n  \\begin{bmatrix}\n  1 & \\tfrac{1}{2}\\\\[2pt]\n  \\tfrac{1}{2} & 1\n  \\end{bmatrix}.\n  $$ \n  \nHowever, you want to estimate the quantity of interest $q = \\tau(a,b)=\\dfrac{a}{b}$. Find $\\hat q$ using the invariance property and estimate the SE of $\\hat q$ using the delta method. (Find the gradient analytically.) Confirm your work with R.\n\n::: hint\n\nSee [Section 7.3.3](https://pos5747.github.io/notes/wk03/04-delta-method.html#the-matrix-algebra) of the notes.\n\n:::\n\n::: hint\n\n[exponential]{.ex-ref} is a one-parameter version of this multi-parameter calculation.\n\n:::\n\n::: sol\n\n**Solution**\n\nFirst, find the gradient. For $\\tau(a,b)=a/b$,\n\n$$\n\\nabla\\tau(a,b)=\n\\begin{bmatrix}\n\\frac{\\partial}{\\partial a}(a/b)\\\\[6pt]\n\\frac{\\partial}{\\partial b}(a/b)\n\\end{bmatrix}\n=\n\\begin{bmatrix}\n1/b\\\\[4pt]\n-\\,a/b^2\n\\end{bmatrix}.\n$$\nPlugging in $(\\hat a,\\hat b)=(2,1)$, we have $\\nabla\\tau(\\hat a,\\hat b)=\\begin{bmatrix} 1\\\\[2pt] -2 \\end{bmatrix}$.\n\nNow do the required matrix multiplication.\n\n$$\n\\begin{aligned}\n\\widehat{\\mathrm{Var}}[\\tau(\\hat\\theta)]\n&\\approx\n\\overbrace{\\begin{bmatrix}1 & -2\\end{bmatrix}}^{\\nabla\\tau(\\hat\\theta)^{\\!\\top}}\n\\Biggl(\n\\underbrace{\\begin{bmatrix}\n1 & \\tfrac{1}{2}\\\\[2pt]\n\\tfrac{1}{2} & 1\n\\end{bmatrix}}_{\\widehat{\\mathrm{Var}}(\\hat\\theta)}\n\\underbrace{\\begin{bmatrix}1\\\\ -2\\end{bmatrix}}_{\\nabla\\tau(\\hat\\theta)}\n\\Biggr) \\\\[10pt]\n&=\n\\begin{bmatrix}1 & -2\\end{bmatrix}\n\\begin{bmatrix}\n1\\cdot 1 + \\tfrac{1}{2}\\cdot(-2)\\\\[4pt]\n\\tfrac{1}{2}\\cdot 1 + 1\\cdot(-2)\n\\end{bmatrix}\n=\n\\begin{bmatrix}1 & -2\\end{bmatrix}\n\\begin{bmatrix}\n0\\\\[2pt]\n-1.5\n\\end{bmatrix}\n= 0 + 3 = 3.\n\\end{aligned}\n$$\nThus $\\widehat{\\mathrm{Var}}[\\widehat{\\tau}]=3$ and $\\widehat{\\mathrm{SE}}(\\widehat{\\tau})=\\sqrt{3}$.\n\nWe can confirm our work with R.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# given values\na_hat <- 2\nb_hat <- 1\nV_hat <- matrix(c(1, 1/2,\n                  1/2, 1), nrow = 2, byrow = TRUE)\n\n# gradient at (a_hat, b_hat) for tau(a,b) = a/b\ngrad <- c(1 / b_hat, -a_hat / b_hat^2)  # c(1, -2)\n\n# delta method\nvar_tau_hat <- grad %*% V_hat %*% grad\nse_tau_hat  <- sqrt(var_tau_hat)\n\nvar_tau_hat  # 3\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     [,1]\n[1,]    3\n```\n\n\n:::\n\n```{.r .cell-code}\nse_tau_hat   # sqrt(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         [,1]\n[1,] 1.732051\n```\n\n\n:::\n:::\n\n\n\n:::\n\n## Turnout rates, part 1 {ref=\"turnout1\"}\n\nLoad a [tibble version of the 2024 turnout data](https://gist.github.com/carlislerainey/fda3b4eb7e95d50949a445d9ae7f02c8) from the [UF Election Lab](https://election.lab.ufl.edu/2024-general-election-turnout/) into R. \n\n\nModel the proportion of the voting-eligible population that voted using a beta distribution. Estimate the parameters of the beta distribution $\\alpha$ and $\\beta$ as well as the mean $\\mu = \\frac{\\alpha}{\\alpha + \\beta}$ and the SD $\\sigma = \\sqrt{\\frac{\\alpha \\beta}{(\\alpha + \\beta)^2 (\\alpha + \\beta + 1)}}$. Use a parametric bootstrap to estimate the SE of each.\n\n::: hint\n\nSee [Section 5.2](https://pos5747.github.io/notes/wk03/02-parametric-bootstrap.html#example-beta-distribution) of the notes.\n\n:::\n\n::: hint\n\nFitting a beta model with `optim()` 1,000s of times might lead to a convergence error in a couple of fits. These might be important, but for the sake of *this exercise* we can ignore them.\n\n:::\n\n::: sol\n\n**Solution**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load packages\nlibrary(tidyverse)\nlibrary(tinytable)\n\n# load data as tibble \nturnout_2024 <- tribble(\n  ~state,             ~vep_turnout,\n  \"Alabama\",          0.5893,\n  \"Alaska\",           0.6378,\n  \"Arizona\",          0.6360,\n  \"Arkansas\",         0.5348,\n  \"California\",       0.6206,\n  \"Colorado\",         0.7314,\n  \"Connecticut\",      0.6708,\n  \"Delaware\",         0.6702,\n  \"District of Columbia\", 0.6357,\n  \"Florida\",          0.6671,\n  \"Georgia\",          0.6826,\n  \"Hawaii\",           0.5027,\n  \"Idaho\",            0.6344,\n  \"Illinois\",         0.6325,\n  \"Indiana\",          0.5869,\n  \"Iowa\",             0.7078,\n  \"Kansas\",           0.6318,\n  \"Kentucky\",         0.6219,\n  \"Louisiana\",        0.6077,\n  \"Maine\",            0.7424,\n  \"Maryland\",         0.6930,\n  \"Massachusetts\",    0.6803,\n  \"Michigan\",         0.7464,\n  \"Minnesota\",        0.7635,\n  \"Mississippi\",      0.5745,\n  \"Missouri\",         0.6434,\n  \"Montana\",          0.6820,\n  \"Nebraska\",         0.6796,\n  \"Nevada\",           0.6580,\n  \"New Hampshire\",    0.7405,\n  \"New Jersey\",       0.6724,\n  \"New Mexico\",       0.5957,\n  \"New York\",         0.6044,\n  \"North Carolina\",   0.7032,\n  \"North Dakota\",     0.6310,\n  \"Ohio\",             0.6539,\n  \"Oklahoma\",         0.5328,\n  \"Oregon\",           0.7194,\n  \"Pennsylvania\",     0.7143,\n  \"Rhode Island\",     0.6328,\n  \"South Carolina\",   0.6214,\n  \"South Dakota\",     0.6400,\n  \"Tennessee\",        0.5761,\n  \"Texas\",            0.5657,\n  \"Utah\",             0.6415,\n  \"Vermont\",          0.7089,\n  \"Virginia\",         0.7119,\n  \"Washington\",       0.7017,\n  \"West Virginia\",    0.5546,\n  \"Wisconsin\",        0.7664,\n  \"Wyoming\",          0.6128\n)\n\n# beta log-likelihood\nbeta_ll_fn <- function(theta, y) { \n  alpha <- theta[1] \n  beta <- theta[2] \n  ll <- sum(dbeta(y, shape1 = alpha, shape2 = beta, log = TRUE))\n  return(ll)\n}\n\n# create a function to fit the beta model\nest_beta <- function(y) {\n  est <- optim(par = c(3, 3), fn = beta_ll_fn, y = y,\n               control = list(fnscale = -1),\n               method = \"BFGS\") # for >1d problems\n  if (est$convergence != 0) print(\"Model did not converge!\")\n  res <- list(est = est$par)\n  return(res)\n}\n\n# ml estimates\nml_est <- est_beta(turnout_2024$vep_turnout)\na <- ml_est$est[1]; a  # alpha\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 39.59784\n```\n\n\n:::\n\n```{.r .cell-code}\nb <- ml_est$est[2]; b  # beta\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 21.29332\n```\n\n\n:::\n\n```{.r .cell-code}\na / (a + b)  # mean; using a and b for readability\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6503053\n```\n\n\n:::\n\n```{.r .cell-code}\nsqrt( (a * b) / ((a + b)^2 * (a + b + 1)) ) # SD\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.06061623\n```\n\n\n:::\n\n```{.r .cell-code}\n# parametric bootstrap\nn_bs <- 100\nbs_alpha_hat <- \n  bs_beta_hat <- \n  bs_mu_hat <-\n  bs_sigma_hat <-\n  numeric(n_bs)  # containers for the estimates\n\nfor (i in 1:n_bs) {\n  # bootstrap sample\n  bs_y <- rbeta(length(turnout_2024$vep_turnout), shape1 = ml_est$est[1], shape2 = ml_est$est[2])\n  \n  # fit model to bootstrapped sample\n  bs_est <- est_beta(bs_y)\n  \n  # store ml estimates of alpha and beta for readability below\n  bs_a <- bs_est$est[1]\n  bs_b <- bs_est$est[2]\n\n  # compute and store all qis\n  bs_alpha_hat[i] <- bs_a\n  bs_beta_hat[i]  <- bs_b\n  bs_mu_hat[i]    <- bs_a / (bs_a + bs_b)\n  bs_sigma_hat[i] <- sqrt( (bs_a * bs_b) / ((bs_a + bs_b)^2 * (bs_a + bs_b + 1)) )\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Model did not converge!\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# bootstrap SEs\nbs_se_alpha_hat <- sd(bs_alpha_hat)\nbs_se_beta_hat  <- sd(bs_beta_hat)\nbs_se_mu_hat    <- sd(bs_mu_hat)\nbs_se_sigma_hat <- sd(bs_sigma_hat)\n\n# tinytable (avoid underscores in visible labels)\ntab_df <- tibble::tibble(\n  Parameter     = c(\"$\\\\alpha$\", \"$\\\\beta$\", \"$\\\\mu$\", \"$\\\\sigma$\"),\n  `ML estimate` = c(a_hat = a, \n                    b_hat = b, \n                    mu_hat = a / (a + b), \n                    sigma_hat = sqrt( (a * b) / ((a + b)^2 * (a + b + 1)) )),\n  `Bootstrap SE`= c(bs_se_alpha_hat, bs_se_beta_hat, bs_se_mu_hat, bs_se_sigma_hat)\n)\ntt(\n  tab_df,\n  digits = 3,\n  caption = \"Beta model: ML estimates and parametric-bootstrap standard errors.\",\n)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_jyko4ektzkfn8vfjxqv2 = TinyTable.createTableFunctions(\"tinytable_jyko4ektzkfn8vfjxqv2\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '4', j: 1 }, { i: '4', j: 2 }, { i: '4', j: 3 } ], css_id: 'tinytable_css_abeqf7ls491zb5oiay5s',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 } ], css_id: 'tinytable_css_9q65y0wv22rhbawb77da',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_jyko4ektzkfn8vfjxqv2.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_jyko4ektzkfn8vfjxqv2 td.tinytable_css_abeqf7ls491zb5oiay5s, #tinytable_jyko4ektzkfn8vfjxqv2 th.tinytable_css_abeqf7ls491zb5oiay5s {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_jyko4ektzkfn8vfjxqv2 td.tinytable_css_9q65y0wv22rhbawb77da, #tinytable_jyko4ektzkfn8vfjxqv2 th.tinytable_css_9q65y0wv22rhbawb77da {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_jyko4ektzkfn8vfjxqv2\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <caption>Beta model: ML estimates and parametric-bootstrap standard errors.</caption>\n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Parameter</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">ML estimate</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Bootstrap SE</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">$\\alpha$</td>\n                  <td data-row=\"1\" data-col=\"2\">39.5978</td>\n                  <td data-row=\"1\" data-col=\"3\">7.99754</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">$\\beta$</td>\n                  <td data-row=\"2\" data-col=\"2\">21.2933</td>\n                  <td data-row=\"2\" data-col=\"3\">4.36365</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">$\\mu$</td>\n                  <td data-row=\"3\" data-col=\"2\">0.6503</td>\n                  <td data-row=\"3\" data-col=\"3\">0.00827</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\">$\\sigma$</td>\n                  <td data-row=\"4\" data-col=\"2\">0.0606</td>\n                  <td data-row=\"4\" data-col=\"3\">0.00547</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\n:::\n\n## Turnout rates, part 2 {ref=\"turnout2\"}\n\nEstimate the SEs of $\\hat{\\mu}$ numerically (i.e., using `optim()` with `hessian = TRUE` combined with the delta method with `numDeriv::grad()`). Compare to the results from the parametric bootstrap in part 1.\n\n::: hint\n\nSee [Section 6.7](https://pos5747.github.io/notes/wk03/03-fisher-information-matrix.html#beta-model-and-optim) of the notes for $\\widehat{\\operatorname{Var}}(\\hat\\theta)$ from `optim()`, and [Section 7.3.4](https://pos5747.github.io/notes/wk03/04-delta-method.html#numerical-gradient) for the numerical gradient.\n\n:::\n\n::: hint\n\nThis is like [delta-by-hand]{.ex-ref}, except that $\\widehat{\\operatorname{Var}}(\\hat\\theta)$ is computed by `optim()` rather than given in the text of the question.. \n\nIn [poisson]{.ex-ref}, you found the observed information for a single parameter. Here, the observed information is a $2 \\times 2$ matrix.\n\n:::\n\n::: sol\n\n**Solution**\n\nFirst, find the variance matrix estimate with `optim()`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(numDeriv)  # for numerical gradients\n\n# refit the model, this time keeping the hessian\n# (turnout_2024 and beta_ll_fn come from part 1)\nest <- optim(par = c(3, 3), fn = beta_ll_fn, y = turnout_2024$vep_turnout,\n             control = list(fnscale = -1),\n             method = \"BFGS\",\n             hessian = TRUE)\n\ntheta_hat <- est$par        # c(alpha_hat, beta_hat)\ninfo_obs  <- -est$hessian   # observed information (note the negative)\nvar_hat   <- solve(info_obs)  # estimated covariance matrix of theta_hat\n\ntheta_hat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 39.59784 21.29332\n```\n\n\n:::\n\n```{.r .cell-code}\nvar_hat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         [,1]     [,2]\n[1,] 61.29559 32.19541\n[2,] 32.19541 17.53257\n```\n\n\n:::\n\n```{.r .cell-code}\nsqrt(diag(var_hat))  # ses of alpha_hat and beta_hat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 7.829150 4.187191\n```\n\n\n:::\n:::\n\n\n\nNow use the delta method to convert the variance (matrix) estimates of $(\\hat{alpha}, \\hat{\\beta})$ to an estimate of the variance of $\\hat{\\mu}$. \n\n- The quantity of interest is $\\mu = \\tau(\\alpha, \\beta) = \\frac{\\alpha}{\\alpha + \\beta}$. \n- The delta method is $\\widehat{\\operatorname{Var}}[\\tau(\\hat\\theta)] \\approx \\nabla\\tau(\\hat\\theta)^\\top \\widehat{\\operatorname{Var}}(\\hat\\theta) \\nabla\\tau(\\hat\\theta)$. \n\nWe could differentiate $\\tau()$ by hand here, but `numDeriv::grad()` can do it numerically and that's what the question asks us to do!\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# the quantity of interest as a function of theta\nmu_fn <- function(theta) {\n  a <- theta[1]\n  b <- theta[2]\n  a / (a + b)\n}\n\n# numerical gradient of tau() evaluated at theta_hat\ngrad_mu <- grad(func = mu_fn, x = theta_hat)\ngrad_mu\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  0.005742948 -0.010679799\n```\n\n\n:::\n\n```{.r .cell-code}\n# delta method\nvar_mu_hat <- t(grad_mu) %*% var_hat %*% grad_mu\nse_mu_hat  <- sqrt(var_mu_hat)\n\nse_mu_hat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            [,1]\n[1,] 0.008487219\n```\n\n\n:::\n:::\n\n\n\nNow compare the two of SEs for $\\hat{\\mu}$. (`bs_se_mu_hat` is the bootstrap SE  computed in part 1.)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# tinytable (avoid underscores in visible labels)\ncompare_df <- tibble::tibble(\n  Parameter         = c(\"$\\\\mu$\"),\n  `Bootstrap SE`    = c(bs_se_mu_hat),\n  `Delta method SE` = c(se_mu_hat)\n)\ntt(\n  compare_df,\n  digits = 3,\n  caption = \"Beta model: parametric-bootstrap and delta-method SEs compared\",\n)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_qvzdy6pw4scbq5vtl7dg = TinyTable.createTableFunctions(\"tinytable_qvzdy6pw4scbq5vtl7dg\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '1', j: 1 }, { i: '1', j: 2 }, { i: '1', j: 3 } ], css_id: 'tinytable_css_csldfi9cjtmpfheeelbx',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 } ], css_id: 'tinytable_css_07fwfualf0j9mowqjjxo',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_qvzdy6pw4scbq5vtl7dg.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_qvzdy6pw4scbq5vtl7dg td.tinytable_css_csldfi9cjtmpfheeelbx, #tinytable_qvzdy6pw4scbq5vtl7dg th.tinytable_css_csldfi9cjtmpfheeelbx {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_qvzdy6pw4scbq5vtl7dg td.tinytable_css_07fwfualf0j9mowqjjxo, #tinytable_qvzdy6pw4scbq5vtl7dg th.tinytable_css_07fwfualf0j9mowqjjxo {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_qvzdy6pw4scbq5vtl7dg\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <caption>Beta model: parametric-bootstrap and delta-method SEs compared</caption>\n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Parameter</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Bootstrap SE</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Delta method SE</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">$\\mu$</td>\n                  <td data-row=\"1\" data-col=\"2\">0.00827</td>\n                  <td data-row=\"1\" data-col=\"3\">0.00849</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\n:::\n\n## Two CIs {ref=\"two-cis\"}\n\nConsider a simple Bernoulli model for $y \\in \\{0,1\\}$ with parameter $\\pi \\in [0,1]$. Create a small sample with a rare event: take $N = 20$ trials with exactly one success.\n\n**Part 1.** *Wald confidence interval.*\n\nCompute the ML estimate $\\hat \\pi = \\operatorname{avg}(y)$, the Wald SE $\\widehat{\\mathrm{SE}}(\\hat \\pi) = \\sqrt{\\hat \\pi(1-\\hat \\pi)/N}$, and the usual $95\\%$ Wald confidence interval $\\hat \\pi \\pm 1.96 \\cdot\\widehat{\\mathrm{SE}}(\\hat \\pi)$. What do you notice about the interval relative to the parameter space $[0,1]$?\n\n**Part 2.** *Parametric bootstrap confidence interval.*\n\nUse a *parametric bootstrap* to obtain a $95\\%$ percentile confidence interval for $\\pi$ based on the fitted model $\\text{Bernoulli}(\\hat \\pi)$. Compare the bootstrap interval with the Wald interval. What stands out? Briefly explain.\n\n::: hint\n\nSee [Section 6.5](https://pos5747.github.io/notes/wk03/03-fisher-information-matrix.html#from-curvature-to-wald-confidence-intervals) of the notes for the Wald interval and [Section 5.1](https://pos5747.github.io/notes/wk03/02-parametric-bootstrap.html#example-toothpaste-cap-problem) for a bootstrap percentile interval on a Bernoulli model.\n\n:::\n\n::: hint\n\nThis is like the parametric bootstrap from [turnout1]{.ex-ref}. Repeatedly simulate $y^{*(b)}_1,\\dots,y^{*(b)}_N \\stackrel{iid}{\\sim} \\text{Bernoulli}(\\hat \\pi)$, recompute $\\hat \\pi^{*(b)} = \\operatorname{avg}(y^{*(b)})$, and then take the empirical $2.5^\\text{th}$ and $97.5^\\text{th}$ percentiles of $\\{\\hat \\pi^{*(b)}\\}$.\n\n:::\n\n::: sol\n\n**Solution.**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\n\n# data: N = 20 with exactly one success\nN <- 20\ny <- c(1, rep(0, N - 1))  # rare event sample\ny <- sample(y)            # shuffle (irrelevant, but tidy)\n\n# ml estimate and wald 95%ci\npi_hat   <- mean(y)\nse <- sqrt(pi_hat * (1 - pi_hat) / N)\nwald_ci <- pi_hat + c(-1, 1) * 1.96 * se\n\npi_hat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.05\n```\n\n\n:::\n\n```{.r .cell-code}\nse\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.04873397\n```\n\n\n:::\n\n```{.r .cell-code}\nwald_ci\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.04551858  0.14551858\n```\n\n\n:::\n:::\n\n\n\nThe Wald interval extends below 0, which is outside the parameter space $[0,1]$.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# parametric bootstrap w/ percentile 95% ci\nn_bs <- 2000\nbs_est <- numeric(n_bs)  # a container for the estimates\nfor (i in 1:n_bs) {\n  bs_y <- rbinom(20, size = 1, prob = pi_hat)\n  bs_est[i] <- mean(bs_y)\n}\n\nprint(quantile(bs_est, probs = c(0.025, 0.975)), digits = 2)  # 95% ci\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n 2.5% 97.5% \n 0.00  0.15 \n```\n\n\n:::\n:::\n\n\n\nThe Wald interval uses a normal approximation centered at $\\hat \\pi$ with variance estimated by Fisher information. With extreme $\\hat \\pi$ near zero and small $N$, this approximation is poor and the lower bound of the CI can dip below 0. In contrast, the parametric bootstrap respects the model's support by construction (every $\\hat \\pi^{*(b)} \\in [0,1]$), so the percentile interval stays within $[0,1]$ and typically provides more reasonable coverage in this setting.\n\n:::\n",
    "supporting": [
      "wk03-exercises_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}