{
  "hash": "b576fe4127e8c12bf9c9762b322ebd18",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 3 Exercises\"\nformat:\n  pdf:\n    number-sections: true\n    include-in-header: \n      - preamble.tex\nsolutions: false\n---\n\n\n\n\n\n## Mean v. median\n\nSuppose $y$ follows a normal model with mean $\\mu$ and SD $\\sigma$. Then $\\operatorname{avg}(y)$ is the *best* unbiased estimator of $\\mu$. But $\\operatorname{median}(y)$ is also an unbiased estimator of $\\mu$. Use a Monte Carlo simulation to show how $\\operatorname{avg}(y)$ is a better estimator of $\\mu$ than $\\operatorname{median}(y)$.\n\n::: {.content-visible when-meta=\"solutions\"} \n\nThe average is better because the SE of the average estimator is smaller than the SE of the median estimator. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# parameters\nmu <- 0\nsigma <- 1\nN <- 10 # sample size of y\nn_mc_sims <- 10000   # monte carlo repetitions\n\n# containers\nmean_hat <- numeric(n_mc_sims)\nmedian_hat <- numeric(n_mc_sims)\n\n# simulate many data sets y; compute and store estimates for each\nfor (i in 1:n_mc_sims) {\n  y <- rnorm(N, mean = mu, sd = sigma)\n  mean_hat[i]   <- mean(y)\n  median_hat[i] <- median(y)\n}\n\nsd(mean_hat)  # se of avg estimator\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3172921\n```\n\n\n:::\n\n```{.r .cell-code}\nsd(median_hat)  # se of median estimator\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.370894\n```\n\n\n:::\n:::\n\n\n\n:::\n\n\n## Asymptotics as approximations\n\nFor a large number of repetitions, do the following:\n\n1. Simulate a data set $y$ with $N = 50$ observations from the exponential distribution with $\\lambda = 2$.\n1. Compute the point estimate $\\hat{\\lambda} = \\frac{1}{\\text{avg}(y)}$. Store this point estimate.\n\nCompare the mean and SD of the simulated point estimates to the theoretical mean and SD of the *asymptotic* sampling distribution. We care, of course, about the *actual* sampling distribution, but we have to use an *asymptotic approximation* in practice. Discuss the differences and whether they seem important or unimportant.\n\n*Hint*: For the exponential model, the asymptotic sampling distribution of $\\hat{\\lambda}$ is $\\hat{\\lambda} \\overset{a}{\\sim} N\\left(\\lambda,\\; \\frac{\\lambda^2}{N}\\right)$.\n\nOptional: Go beyond the mean and SD. Use a table of quantiles of the simulated point estimates and theoretical distribution and/or plots of the CDFs to compare the simulated (i.e., actual) and theoretical distributions.\n\n::: {.content-visible when-meta=\"solutions\"} \n\n**Solution**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load packages\nlibrary(tinytable)\noptions(tinytable_tt_digits = 3)\noptions(tinytable_latex_placement = \"H\")\n\n# set seed for reproducibility\nset.seed(1234)\n\n# parameters\nlambda <- 2\nN <- 50  # sample size\nR <- 10000  # number of mc repetitions\n\n# loop\nlambda_hat <- numeric(R)  # container to store results\nfor (i in 1:R) {\n y <-  rexp(N, rate = lambda)  # simulate data set\n lambda_hat[i] <- 1/mean(y)  # compute and store estimate\n}\n\n# empirical summaries\nemp_mean <- mean(lambda_hat)\nemp_sd   <- sd(lambda_hat)\n\n# asymptotic\nasy_mean <- lambda\nasy_sd   <- sqrt(lambda^2 / N)\n\n# data frame of results\nres <- data.frame(\n  Statistic   = c(\"Mean\", \"SD\"),\n  Empirical   = c(emp_mean, emp_sd),\n  Asymptotic  = c(asy_mean, asy_sd)\n)\n\n# print table\ntt(\n  res,\n  digits  = 3,   \n  align   = \"lrr\",\n) \n```\n\n::: {.cell-output-display}\n\\begin{table}[H]\n\\centering\n\\begin{tblr}[         %% tabularray outer open\n]                     %% tabularray outer close\n{                     %% tabularray inner open\ncolspec={Q[]Q[]Q[]},\n}                     %% tabularray inner close\n\\toprule\nStatistic & Empirical & Asymptotic \\\\ \\midrule %% TinyTableHeader\nMean & 2.04 & 2 \\\\\nSD & 0.293 & 0.283 \\\\\n\\bottomrule\n\\end{tblr}\n\\end{table}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# quantile comparison table\nprobs <- c(0.01, 0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99)\nemp_q <- quantile(lambda_hat, probs = probs)\nasy_q <- qnorm(probs, mean = asy_mean, sd = asy_sd)\n\n# combine into data frame\nquant <- data.frame(\n  p = probs,\n  empirical = emp_q,\n  asymptotic = asy_q,\n  difference = emp_q - asy_q\n)\n\n# make table\ntt(\n  quant,\n  digits  = 3,   # no rounding for the text column; 3 decimals for numbers\n  align   = \"lrr\",\n)\n```\n\n::: {.cell-output-display}\n\\begin{table}[H]\n\\centering\n\\begin{tblr}[         %% tabularray outer open\n]                     %% tabularray outer close\n{                     %% tabularray inner open\ncolspec={Q[]Q[]Q[]Q[]},\n}                     %% tabularray inner close\n\\toprule\np & empirical & asymptotic & difference \\\\ \\midrule %% TinyTableHeader\n0.01 & 1.47 & 1.34 & 0.1302 \\\\\n0.05 & 1.61 & 1.53 & 0.073 \\\\\n0.1 & 1.69 & 1.64 & 0.0503 \\\\\n0.25 & 1.83 & 1.81 & 0.0242 \\\\\n0.5 & 2.01 & 2 & 0.013 \\\\\n0.75 & 2.22 & 2.19 & 0.028 \\\\\n0.9 & 2.43 & 2.36 & 0.0628 \\\\\n0.95 & 2.56 & 2.47 & 0.0995 \\\\\n0.99 & 2.83 & 2.66 & 0.176 \\\\\n\\bottomrule\n\\end{tblr}\n\\end{table}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# load packages\nlibrary(tidyverse)\n\n# plot ecdf and asymptotic distribution\ngg_data <- data.frame(lambda_hat = lambda_hat)\nggplot(gg_data, aes(x = lambda_hat)) +\n  stat_ecdf() +\n  stat_function(fun = function(x) pnorm(x, \n                                        mean = asy_mean, \n                                        sd = asy_sd), \n                color = \"red\") +\n  labs(\n    title = \"ECDF of Simulated ML Estimates vs Asymptotic Sampling Distribution\",\n    x = expression(hat(lambda)),\n    y = \"Cumulative Probability\"\n  )\n```\n\n::: {.cell-output-display}\n![](wk03-exr-sol_files/figure-pdf/unnamed-chunk-4-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n*Discussion*\n\n- **Center (bias).** The empirical mean of $\\hat{\\lambda}$ is about 2.04, compared to the true $\\lambda=2.000$. This is a difference of roughly 2%. At $N=50$, this upward bias is present but quite small.\n- **Spread.** The empirical SD is about 0.293, while the asymptotic SD is 0.283. This difference is 3.7% of the asymptotic value, so the asymptotic variance formula provides an accurate description of variability.\n- **Quantiles and tails.** For the median, the empirical value is 2.013 compared to an asymptotic prediction of 2. At the 1% and 99% quantiles, the differences are about 0.13 and 0.176, respectively, which correspond to differences of only a few percent relative to the true scale. The ECDF and normal CDF curves are nearly indistinguishable except in the tails.\n- **Bottom line.** With $N=50$, the asymptotic normal distribution closely matches the finite-sample distribution of $\\hat{\\lambda}$. The bias is about 2%, the SD differs by about 4%, and quantile differences are small. The asymptotic normal approximation is accurate and reliable for practical use at this sample size.\n\n:::\n\n## German Tank Problem\n\nSuppose a discrete uniform distribution from 0 to $K$. The pmf is $f(x; K) = \\frac{1}{K + 1}, \\quad x \\in \\{0, 1, \\ldots, K\\}$. The ML estimator is $\\hat K = \\max(y)$. The method of moments estimator is $\\hat K = 2 \\times \\operatorname{avg}(y)$. Use a Monte Carlo simulation to evaluate bias and variance of each estimator for a small ($N = 3$), medium ($N = 25$), and large sample size ($N = 1,000$). Which estimator do you recommend?\n\n*Note:* This model violates several of the regularity conditions, so the usual asymptotic guarantees do not hold.\n\n::: {.content-visible when-meta=\"solutions\"} \n\n**Solution**\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load packages\nlibrary(tinytable)\nlibrary(dplyr)\noptions(tinytable_tt_digits = 3)\noptions(tinytable_latex_placement = \"H\")\n\n# set seed for reproducibility\nset.seed(1234)\n\n# parameters\nK  <- 100               # true K\nNs <- c(3, 25, 1000)    # sample sizes\nR  <- 10000             # number of mc repetitions\n\n# container: list of data frames\nres_list <- list()\n\n# loop over sample sizes\nfor (N in Ns) {\n  K_hat_mle <- numeric(R)   # container for MLE\n  K_hat_mom <- numeric(R)   # container for MOM\n  \n  for (i in 1:R) {\n    y <- sample(0:K, N, replace = TRUE)  # simulate data set\n    K_hat_mle[i] <- max(y)                # MLE\n    K_hat_mom[i] <- 2 * mean(y)           # MOM\n  }\n  \n  # empirical summaries\n  emp_mean_mle <- mean(K_hat_mle)\n  emp_sd_mle   <- sd(K_hat_mle)\n  emp_mean_mom <- mean(K_hat_mom)\n  emp_sd_mom   <- sd(K_hat_mom)\n  \n  # store results for this N\n  res_list[[as.character(N)]] <- data.frame(\n    N          = N,\n    Estimator  = c(\"MLE\", \"MOM\"),\n    Mean       = c(emp_mean_mle, emp_mean_mom),\n    SD         = c(emp_sd_mle,   emp_sd_mom),\n    Bias       = c(emp_mean_mle - K, emp_mean_mom - K),\n    MSE        = c(mean((K_hat_mle - K)^2), mean((K_hat_mom - K)^2))\n  )\n}\n\n# combine all into one data frame\nres <- bind_rows(res_list)\n\n# print table\ntt(\n  res,\n  digits = 5,\n  align  = \"lrrrrr\",\n)\n```\n\n::: {.cell-output-display}\n\\begin{table}[H]\n\\centering\n\\begin{tblr}[         %% tabularray outer open\n]                     %% tabularray outer close\n{                     %% tabularray inner open\ncolspec={Q[]Q[]Q[]Q[]Q[]Q[]},\n}                     %% tabularray inner close\n\\toprule\nN & Estimator & Mean & SD & Bias & MSE \\\\ \\midrule %% TinyTableHeader\n3 & MLE & 75.055 & 19.7364 & -24.9454 & 1011.7588 \\\\\n3 & MOM & 99.952 & 33.59 & -0.048467 & 1128.1803 \\\\\n25 & MLE & 96.665 & 3.6737 & -3.3353 & 24.6191 \\\\\n25 & MOM & 100.191 & 11.7466 & 0.191144 & 138.0057 \\\\\n1000 & MLE & 100 & 0 & 0 & 0 \\\\\n1000 & MOM & 99.993 & 1.8362 & -0.007073 & 3.3712 \\\\\n\\bottomrule\n\\end{tblr}\n\\end{table}\n:::\n:::\n\n\n\nNotice that the ML estimator is severely biased downward in small samples. But it also has a much smaller variance. It's not clear how to tradeoff these two. However, it's worth noting the the severely biased ML estimator has a *smaller* mean-squared error.\n\n:::\n\n## Jensen's Inequality\n\nSuppose the usual exponential model. The ML estimate of the rate $\\lambda$ is $\\hat{\\lambda} = \\frac{1}{\\text{avg}(y)}$. Using the invariance property, the ML estimate of the mean $\\frac{1}{\\lambda}$ is $\\hat{\\mu} = \\frac{1}{\\hat{\\lambda}}$. Show analytically that the ML estimate of the mean is unbiased, while the ML estimate of the rate is biased. \n\n**Jensen's Inequality.**  If $g$ is a convex function and $X$ is a random variable with $\\mathbb E[X]$ finite, then $\\mathbb E\\big[g(X)\\big] \\ge g \\big(\\mathbb E[X]\\big)$,\nwith strict inequality unless $X$ is degenerate (i.e., constant almost surely).\n\n*Hint: First show that $\\hat{\\mu}$ is unbiased. Then use Jensen's inequality to show that $\\hat{\\lambda}$ is biased upward. You do not need to find the size of the bias, just use Jensen's inequality to show that the ML estimate of the rate is biased. To use Jensen's inequality, let $g(x)=1/x$, and notice that $g(x)$ is convex on $(0,\\infty)$ (since $g''(x)=2/x^3>0$).*\n\n::: {.content-visible when-meta=\"solutions\"} \n\n**Solution**\n\n*1) Unbiasedness of the ML estimate of the mean*\n\n$\\hat{\\mu} = \\text{avg}(y) = \\frac{1}{N} \\sum_{i = 1}^N y_i$ is the sample mean of iid observations. $\\mathbb E[y_i]=\\frac{1}{\\lambda}$. Then \n\n$$\n\\begin{aligned}\n\\mathbb E[\\hat\\mu] \n  &= \\mathbb E \\left[ \\frac{1}{N} \\sum_{i = 1}^N y_i \\right] && \\text{(definition of $\\hat\\mu$)}\\\\\n  &= \\frac{1}{N} \\cdot \\mathbb E \\left[\\sum_{i = 1}^N y_i \\right] && \\text{(linearity)}\\\\\n  &= \\frac{1}{N} \\cdot \\left[\\sum_{i = 1}^N \\mathbb E (y_i) \\right] && \\text{(sum of expectations)}\\\\\n  &= \\frac{1}{N} \\cdot \\left[\\sum_{i = 1}^N \\frac{1}{\\lambda} \\right] && \\text{(each has mean $1/\\lambda$)}\\\\\n  &= \\frac{1}{N} \\cdot \\left[N \\cdot \\frac{1}{\\lambda} \\right] && \\text{(sum $N$ identical terms)}\\\\\n  &= \\frac{1}{\\lambda} && \\text{(simplify)}\\\\\n  &= \\mu && \\text{(definition of $\\mu$)}\n\\end{aligned}\n$$\n\nBecause $\\mathbb E(\\hat\\mu) = \\mu$, $\\hat{\\mu}$ is unbiased estimate of the mean.\n\n*2) Bias of the ML estimate of the rate*\n\n$\\hat{\\lambda} = \\dfrac{1}{\\text{avg}(y)} = \\left(\\dfrac{1}{N}\\sum_{i=1}^N y_i\\right)^{-1}$. Let $g(x)=1/x$, and notice that $g(x)$ is convex on $(0,\\infty)$ (since $g''(x)=2/x^3>0$). Then\n\n$$\n\\begin{aligned}\n\\mathbb E[\\hat{\\lambda}]\n  &= \\mathbb E\\left[ \\frac{1}{\\text{avg}(y)} \\right] && \\text{(definition of $\\hat{\\lambda}$)}\\\\\n  &= \\mathbb E\\left[g\\big(\\text{avg}(y)\\big)\\right] && \\text{(definition of $g$ above)}\\\\\n  &> g\\big(\\mathbb E[\\text{avg}(y)]\\big) && \\text{(Jensen's inequality, $g$ convex)}\\\\\n  &= \\frac{1}{\\mathbb E[\\text{avg}(y)]} && \\text{(apply $g$)}\\\\\n  &= \\frac{1}{\\frac{1}{N}\\sum_{i=1}^N \\mathbb E(y_i)} && \\text{(linearity of expectation)}\\\\\n  &= \\frac{1}{\\frac{1}{N}\\sum_{i=1}^N \\frac{1}{\\lambda}} && \\text{(each $y_i$ has mean $1/\\lambda$)}\\\\\n  &= \\frac{1}{\\frac{1}{N}\\cdot N \\cdot \\frac{1}{\\lambda}} && \\text{(sum of $N$ identical terms)}\\\\\n  &= \\lambda && \\text{(simplify)}\n\\end{aligned}\n$$\n\nSince the inequality is strict for finite $N$ (the distribution of $\\text{avg}(y)$ is non-degenerate), $\\mathbb E[\\hat{\\lambda}] > \\lambda$. Thus, the ML estimate of the **rate** is biased upward.\n\n:::\n\n\n## Poisson\n\nSuppose a Poisson model. The ML estimate of the mean parameter $\\lambda$ is $\\hat\\lambda = \\text{avg}(y)$. Find an estimate of the SE using the observed Fisher information.\n\n::: {.content-visible when-meta=\"solutions\"} \n\n**Solution**\n\nThe log-likelihood is $\\ell(\\lambda) = \\sum_{i=1}^N \\big[y_i \\log \\lambda - \\lambda - \\log(y_i!)\\big]$.\n\nFirst, find the second derivative with respect to $\\lambda$.\n\n$$\n\\begin{aligned}\n\\ell(\\lambda)\n&= \\sum_{i=1}^N \\big[y_i \\log \\lambda - \\lambda - \\log(y_i!)\\big]\n&& \\text{Poisson log-likelihood} \\\\[6pt]\n\\frac{\\partial \\ell}{\\partial \\lambda}\n&= \\sum_{i=1}^N \\left( y_i \\cdot \\frac{1}{\\lambda} - 1 - 0 \\right)\n&& \\text{use } \\frac{d}{d\\lambda}\\log \\lambda = \\frac{1}{\\lambda},\\; \\frac{d}{d\\lambda}(-\\lambda) = -1,\\; \\log(y_i!) \\text{ is constant} \\\\[6pt]\n&= \\sum_{i=1}^N \\left( \\frac{y_i}{\\lambda} - 1 \\right)\n= \\frac{1}{\\lambda} \\sum_{i=1}^N y_i - N\n&& \\text{collect terms} \\\\[10pt]\n\\frac{\\partial^2 \\ell}{\\partial \\lambda^2}\n&= \\frac{\\partial}{\\partial \\lambda} \\left( \\frac{1}{\\lambda} \\sum_{i=1}^N y_i - N \\right)\n&& \\text{differentiate again} \\\\[6pt]\n&= \\sum_{i=1}^N \\left( - \\frac{y_i}{\\lambda^2} \\right) - 0\n&& \\text{use } \\frac{d}{d\\lambda}\\left(\\frac{1}{\\lambda}\\right) = -\\frac{1}{\\lambda^2} \\text{, } N \\text{ is constant} \\\\[6pt]\n&= - \\sum_{i=1}^N \\frac{y_i}{\\lambda^2}.\n\\end{aligned}\n$$\n\nThe observed Fisher information is\n\n$$\n\\mathcal I_{\\text{obs}}(\\lambda)\n= -\\frac{\\partial^2 \\ell}{\\partial \\lambda^2}\n= \\sum_{i=1}^N \\frac{y_i}{\\lambda^2}.\n$$\n\nAsymptotically, $\\operatorname{Var}(\\hat\\lambda) \\approx \\mathcal I_{\\text{obs}}(\\lambda)^{-1}$.^[Rather than \"approximately equals\" ($\\approx$), it's more technically correct to write \"asymptotically equals.\" However, we treat \"asymptotically equals\" to mean \"approximately\" in practice. Given the practical orientation of the course, it seems better to write \"approximately\" here.]\n\nTo find the estimate of the SE, replace $\\lambda$ with $\\hat\\lambda$:\n\n$$\n\\widehat{\\operatorname{SE}}(\\hat\\lambda)\n= \\sqrt{\\mathcal I_{\\text{obs}}(\\hat\\lambda)^{-1}}\n= \\sqrt{\\frac{\\hat\\lambda}{N}}\n= \\sqrt{\\frac{\\operatorname{avg}(y)}{N}}.\n$$\n\n:::\n\n## `operations`\n\nThe code below loads the number of enforcement operations for each district in Bogota from Holland (2015) from the {crdata} package. See `?crdata::holland2015` for details. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load holland2015 data set from crdata package\nholland2015 <- crdata::holland2015 \n\n# get operations in bogota only\nops <- holland2015$operations[holland2015$city == \"bogota\"]\n\n# print\nops\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 15 10 15 20  8  4  8 16  4 28  2  8  4  4  4  4  8  3  4\n```\n\n\n:::\n:::\n\n\n\n**A Poisson model.**\n\n**Task:** Using the Poisson estimators from the previous question, find the ML estimate and SE estimate of $\\lambda$ for a Poisson model. \n\nBut before moving on, compare the SD of the predictive distribution (no need to simulate, it depends only and directly on $\\lambda$) and the SD of the data. Why might this be a problem for the SE estimate?\n\n**A negative-binomial model.**\n\nFor the Poisson model, the mean and variance of the outcome are directly linked. In fact, both equal $\\lambda$. For most outcomes (almost all?), the variance is *much* larger than the average. This means a huge mismatch between the variance of the outcomes and the model. \n\nThe negative binomial model has an additional parameter $r$ that allows the variance to be larger than (but not smaller than) the mean. For almost all datasets, this is a good default. \n\nThe negative binomial distribution is often parameterized by a mean $\\mu > 0$ and a dispersion (or \"size\") parameter $r > 0$.^[There are other common parameterizations that are less interpretable for our purposes.] Its probability mass function is\n\n$$\n\\Pr(Y=y) \\;=\\; \\frac{\\Gamma(y+r)}{\\Gamma(r)\\,y!}\n\\left(\\frac{r}{r+\\mu}\\right)^{r}\n\\left(\\frac{\\mu}{r+\\mu}\\right)^{y}, \\qquad y=0,1,2,\\dots,\n$$\n\nwhich has mean $\\mu$ and variance $\\mu+\\mu^2/r$. In R, the base function `dnbinom()` directly supports this mean–size parameterization when the `mu` argument is supplied (e.g., `dnbinom(y, size = r, mu = mu)`).\n\n**Task**. Use `optim()` to estimate the mean and its SE for the `ops` variable. Compare to the Poisson estimates.\n\n\n::: {.content-visible when-meta=\"solutions\"} \n\n**Solution.**\n\nFirst, fit the Poisson model and compute the ML estimate and SE of $\\lambda$ without using `optim()`, following the observed-information derivation above. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load packages\nlibrary(tidyverse)\nlibrary(tinytable)\n\n# load holland2015 data set from crdata package\nholland2015 <- crdata::holland2015 \n\n# get operations in bogota only\nops <- holland2015$operations[holland2015$city == \"bogota\"]\n\n# estimate lambda with ml\nN <- length(ops)\nlambda_hat_pois <- mean(ops); lambda_hat_pois\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 8.894737\n```\n\n\n:::\n\n```{.r .cell-code}\nse_lambda_hat_pois  <- sqrt(lambda_hat_pois / N); se_lambda_hat_pois\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6842105\n```\n\n\n:::\n\n```{.r .cell-code}\n# compare predictive SD to data SD\nsd_pred_pois <- sqrt(lambda_hat_pois)   # predictive SD under Poisson\nsd_data      <- sd(ops)                 # empirical SD\n\n# summarize results in a small table\nres_pois <- data.frame(\n  Statistic = c(\"Predictive SD \", \"Data SD\"),\n  Value     = c(sd_pred_pois, sd_data)\n)\n\ntt(res_pois, digits = 3, align = \"lr\")\n```\n\n::: {.cell-output-display}\n\\begin{table}[H]\n\\centering\n\\begin{tblr}[         %% tabularray outer open\n]                     %% tabularray outer close\n{                     %% tabularray inner open\ncolspec={Q[]Q[]},\n}                     %% tabularray inner close\n\\toprule\nStatistic & Value \\\\ \\midrule %% TinyTableHeader\nPredictive SD & 2.98 \\\\\nData SD & 6.94 \\\\\n\\bottomrule\n\\end{tblr}\n\\end{table}\n:::\n:::\n\n\n\nNow use `optim()` to fit a negative-binomial model. Compare to the Poisson estimates.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# negative-binomial log-likelihood (mean–size parameterization)\nnb_ll_fn <- function(theta, y) {\n  mu <- theta[1]\n  r  <- theta[2]\n  sum(dnbinom(y, size = r, mu = mu, log = TRUE))\n}\n\n# function to fit nb model\nest_nb <- function(y) {\n  est <- optim(\n    par     = c(3, 1),   # starting values\n    fn      = nb_ll_fn,\n    y       = y,\n    control = list(fnscale = -1),\n    hessian = TRUE\n  )\n  \n  info_obs <- -est$hessian          # observed information\n  var_hat  <- solve(info_obs)        # covariance matrix estimate\n  \n  if (est$convergence != 0) print(\"Model did not converge!\")\n  \n  list(theta_hat = est$par, var_hat = var_hat)\n}\n\n# fit nb model to ops\nfit_nb <- est_nb(ops)\n\n# nb mean estimate and its se\nmu_hat_nb <- fit_nb$theta_hat[1]; mu_hat_nb\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 8.894568\n```\n\n\n:::\n\n```{.r .cell-code}\nse_mu_hat_nb  <- sqrt(fit_nb$var_hat[1,1]); se_mu_hat_nb\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.434298\n```\n\n\n:::\n\n```{.r .cell-code}\n# comparison table\nres_compare <- data.frame(\n  Model      = c(\"Poisson\", \"Negative-binomial\"),\n  Parameter  = c(\"lambda\",  \"mu\"),\n  Estimate   = c(lambda_hat_pois, mu_hat_nb),\n  SE         = c(se_lambda_hat_pois,  se_mu_hat_nb)\n)\n\ntt(res_compare, digits = 3, align = \"l l r r\")\n```\n\n::: {.cell-output-display}\n\\begin{table}[H]\n\\centering\n\\begin{tblr}[         %% tabularray outer open\n]                     %% tabularray outer close\n{                     %% tabularray inner open\ncolspec={Q[]Q[]Q[]Q[]},\n}                     %% tabularray inner close\n\\toprule\nModel & Parameter & Estimate & SE \\\\ \\midrule %% TinyTableHeader\nPoisson & lambda & 8.89 & 0.684 \\\\\nNegative-binomial & mu & 8.89 & 1.434 \\\\\n\\bottomrule\n\\end{tblr}\n\\end{table}\n:::\n:::\n\n\n\n:::\n\n## Exponential\n\nSuppose an exponential model of $y$. We know that the ML estimate of the rate $\\lambda$ is $\\hat \\lambda = \\frac{1}{\\operatorname{avg}(y)}$. By the invariance property, the ML estimate of the mean $\\mu = \\frac{1}{\\lambda}$ is $\\hat \\mu = \\frac{1}{\\hat \\lambda}$. \n\n1. Use the observed Fisher information to find a closed-form estimate of the SE of $\\hat \\lambda$. \n1. Then use the delta method to find a closed-form estimate of the SE of $\\hat \\mu$.\n\n*Hint: For an exponential model with rate $\\lambda$, the density is\n$f(y; \\lambda) = \\lambda e^{-\\lambda y}$, so\n$\\ell(\\lambda) = \\sum \\big(\\log \\lambda - \\lambda y_i\\big)$.*\n\n::: {.content-visible when-meta=\"solutions\"} \n\n**Solution**\n\nThe log-likelihood is\n$$\n\\ell(\\lambda) \\;=\\; \\sum_{i=1}^N \\big[\\log \\lambda \\;-\\; \\lambda y_i\\big].\n$$\n\nFirst, find the second derivative with respect to $\\lambda$.\n\n$$\n\\begin{aligned}\n\\ell(\\lambda)\n&= \\sum_{i=1}^N \\big[\\log \\lambda - \\lambda y_i\\big]\n&& \\text{Exponential log-likelihood} \\\\[6pt]\n\\frac{\\partial \\ell}{\\partial \\lambda}\n&= \\sum_{i=1}^N \\left(\\frac{1}{\\lambda} - y_i\\right)\n&& \\text{use } \\frac{d}{d\\lambda}\\log \\lambda = \\frac{1}{\\lambda},\\; \\frac{d}{d\\lambda}(-\\lambda y_i) = -y_i \\\\[6pt]\n&= \\frac{N}{\\lambda} \\;-\\; \\sum_{i=1}^N y_i\n&& \\text{collect terms} \\\\[10pt]\n\\frac{\\partial^2 \\ell}{\\partial \\lambda^2}\n&= \\frac{\\partial}{\\partial \\lambda}\\!\\left(\\frac{N}{\\lambda} - \\sum_{i=1}^N y_i\\right)\n&& \\text{differentiate again} \\\\[6pt]\n&= -\\,\\frac{N}{\\lambda^2} \\;-\\; 0\n&& \\text{use } \\frac{d}{d\\lambda}\\!\\left(\\frac{1}{\\lambda}\\right) = -\\frac{1}{\\lambda^2},\\; \\sum y_i \\text{ is constant}.\n\\end{aligned}\n$$\n\nThe observed Fisher information is\n$$\n\\mathcal I_{\\text{obs}}(\\lambda)\n= -\\frac{\\partial^2 \\ell}{\\partial \\lambda^2}\n= \\frac{N}{\\lambda^2}.\n$$\n\nTo find the estimate of the SE, replace $\\lambda$ with $\\hat\\lambda$:\n$$\n\\widehat{\\operatorname{SE}}(\\hat\\lambda)\n= \\sqrt{\\mathcal I_{\\text{obs}}(\\hat\\lambda)^{-1}}\n= \\sqrt{\\frac{\\hat\\lambda^{2}}{N}}\n= \\frac{\\hat\\lambda}{\\sqrt{N}}\n= \\frac{1}{\\sqrt{N}\\,\\operatorname{avg}(y)}.\n$$\n\nNow suppose we use the invariance property to obtain $\\hat\\mu = \\dfrac{1}{\\hat\\lambda}$. Then we can use the delta method to estimate the SE with $\\tau(\\lambda) = \\dfrac{1}{\\lambda}$.\n\nThe first derivative is $\\tau'(\\lambda) = -\\frac{1}{\\lambda^2}$.\n\nPlugging in, we have\n$$\n\\begin{aligned}\n\\widehat{\\operatorname{Var}}(\\hat\\mu)\n  &\\approx \\big[\\tau'(\\hat\\lambda)\\big]^2 \\cdot \\widehat{\\operatorname{Var}}(\\hat\\lambda)\n   \\;=\\; \\left(\\frac{1}{\\hat\\lambda^2}\\right)^2 \\cdot \\frac{\\hat\\lambda^{2}}{N} \\\\[6pt]\n  &= \\frac{1}{N\\,\\hat\\lambda^{2}}.\n\\end{aligned}\n$$\n\nAnd the standard error is\n$$\n\\widehat{\\mathrm{SE}}(\\hat\\mu)\n\\;\\approx\\; \\sqrt{\\frac{1}{N\\,\\hat\\lambda^{2}}}\n\\;=\\; \\frac{1}{\\sqrt{N}\\,\\hat\\lambda}\n\\;=\\; \\frac{\\operatorname{avg}(y)}{\\sqrt{N}}.\n$$\n\n:::\n\n## Delta method, by hand\n\nSuppose you obtain the ML estimate $\\hat\\theta=(\\hat a,\\hat b)=(2,\\,1)$ with an estimated covariance matrix of\n  $$\n  \\widehat{\\mathrm{Var}}(\\hat\\theta)\n  =\n  \\widehat{\\mathrm{Var}}(\\hat a,\\hat b)\n  =\n  \\begin{bmatrix}\n  1 & \\tfrac{1}{2}\\\\[2pt]\n  \\tfrac{1}{2} & 1\n  \\end{bmatrix}.\n  $$ \n  \nHowever, you want to estimate the quantity of interest $q = \\tau(a,b)=\\dfrac{a}{b}$. Find $\\hat q$ using the invariance property and estimate the SE of $\\hat q$ using the delta method. (Find the gradient analytically.) Confirm your work with R.\n\n::: {.content-visible when-meta=\"solutions\"}\n\n**Solution**\n\nFirst, find the gradient. For $\\tau(a,b)=a/b$,\n\n$$\n\\nabla\\tau(a,b)=\n\\begin{bmatrix}\n\\frac{\\partial}{\\partial a}(a/b)\\\\[6pt]\n\\frac{\\partial}{\\partial b}(a/b)\n\\end{bmatrix}\n=\n\\begin{bmatrix}\n1/b\\\\[4pt]\n-\\,a/b^2\n\\end{bmatrix}.\n$$\nPlugging in $(\\hat a,\\hat b)=(2,1)$, we have $\\nabla\\tau(\\hat a,\\hat b)=\\begin{bmatrix} 1\\\\[2pt] -2 \\end{bmatrix}$.\n\nNow do the required matrix multiplication.\n\n$$\n\\begin{aligned}\n\\widehat{\\mathrm{Var}}[\\tau(\\hat\\theta)]\n&\\approx\n\\overbrace{\\begin{bmatrix}1 & -2\\end{bmatrix}}^{\\nabla\\tau(\\hat\\theta)^{\\!\\top}}\n\\Biggl(\n\\underbrace{\\begin{bmatrix}\n1 & \\tfrac{1}{2}\\\\[2pt]\n\\tfrac{1}{2} & 1\n\\end{bmatrix}}_{\\widehat{\\mathrm{Var}}(\\hat\\theta)}\n\\underbrace{\\begin{bmatrix}1\\\\ -2\\end{bmatrix}}_{\\nabla\\tau(\\hat\\theta)}\n\\Biggr) \\\\[10pt]\n&=\n\\begin{bmatrix}1 & -2\\end{bmatrix}\n\\begin{bmatrix}\n1\\cdot 1 + \\tfrac{1}{2}\\cdot(-2)\\\\[4pt]\n\\tfrac{1}{2}\\cdot 1 + 1\\cdot(-2)\n\\end{bmatrix}\n=\n\\begin{bmatrix}1 & -2\\end{bmatrix}\n\\begin{bmatrix}\n0\\\\[2pt]\n-1.5\n\\end{bmatrix}\n= 0 + 3 = 3.\n\\end{aligned}\n$$\nThus $\\widehat{\\mathrm{Var}}[\\widehat{\\tau}]=3$ and $\\widehat{\\mathrm{SE}}(\\widehat{\\tau})=\\sqrt{3}$.\n\nWe can confirm our work with R.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# given values\na_hat <- 2\nb_hat <- 1\nV_hat <- matrix(c(1, 1/2,\n                  1/2, 1), nrow = 2, byrow = TRUE)\n\n# gradient at (a_hat, b_hat) for tau(a,b) = a/b\ngrad <- c(1 / b_hat, -a_hat / b_hat^2)  # c(1, -2)\n\n# delta method\nvar_tau_hat <- grad %*% V_hat %*% grad\nse_tau_hat  <- sqrt(var_tau_hat)\n\nvar_tau_hat  # 3\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     [,1]\n[1,]    3\n```\n\n\n:::\n\n```{.r .cell-code}\nse_tau_hat   # sqrt(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         [,1]\n[1,] 1.732051\n```\n\n\n:::\n:::\n\n\n\n:::\n\n## $(\\alpha, \\beta)$ to SD\n\nIn the notes, we saw how to use the invariance principle and the delta method to obtain an ML estimate of the mean $\\mu$ and its SE from ML estimates of $\\alpha$ and $\\beta$ and their estimated covariance matrix. \n\nSimilarly, use the invariance principle and the delta method to find an ML estimate of the SD $\\sigma$ and its SE. Recall that $\\sigma = \\sqrt{\\dfrac{\\alpha \\beta}{(\\alpha + \\beta)^2 (\\alpha + \\beta + 1)}}$ for the beta distribution. Use a numerical gradient.\n\n::: {.content-visible when-meta=\"solutions\"} \n\n**Solution.**\n\nFirst, find the ML estimates of $\\alpha$ and $\\beta$ and estimate their covariance.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# log-likelihood function (using dbeta)\nbeta_ll_fn <- function(theta, y) { \n  alpha <- theta[1] \n  beta  <- theta[2] \n  sum(dbeta(y, shape1 = alpha, shape2 = beta, log = TRUE))\n}\n\n# function to fit beta model \nest_beta <- function(y) {\n  est <- optim(\n    par     = c(2, 2),      # decent starting values\n    fn      = beta_ll_fn,\n    y       = y,\n    control = list(fnscale = -1),  \n    method  = \"BFGS\",\n    hessian = TRUE\n  ) \n  \n  info_obs <- -est$hessian            # observed information (note the negative)\n  var_hat  <- solve(info_obs)         # covariance matrix estimate\n  \n  if (est$convergence != 0) print(\"Model did not converge!\")\n  \n  list(theta_hat = est$par, var_hat = var_hat)\n}\n\n# load packages\nlibrary(tidyverse)\nlibrary(Lahman)  # data from Lahman's baseball database\n\n# create data frame with batting average\nbstats <- battingStats() |> \n  filter(yearID == 2023, AB >= 100) |>            # 2023; at least 100 AB\n  transmute(player_id = playerID, batting_average = BA) |>\n  drop_na() |>\n  arrange(desc(batting_average))\n\n# estimate beta model using the batting average data\nfit <- est_beta(bstats$batting_average)\nfit$theta_hat   \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  37.07655 114.92550\n```\n\n\n:::\n\n```{.r .cell-code}\nfit$var_hat \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          [,1]     [,2]\n[1,]  5.964783 18.40870\n[2,] 18.408705 57.83667\n```\n\n\n:::\n:::\n\n\n\nTo find $\\hat \\sigma$ plug $(\\hat\\alpha,\\hat\\beta)$ into $\\sigma = \\tau(\\alpha,\\beta)$.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# compact notation for readability (matches the notes)\na <- fit$theta_hat[1]  # alpha_hat\nb <- fit$theta_hat[2]  # beta_hat\n\n# sigma_hat via invariance property\nsigma_hat <- sqrt( (a*b) / ((a + b)^2 * (a + b + 1)) )\nsigma_hat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.03471841\n```\n\n\n:::\n:::\n\n\n\n\nWe use a numerical gradient for \n$$\n\\tau(\\theta) = \\sigma(\\alpha,\\beta)\n= \\sqrt{\\frac{\\alpha\\beta}{(\\alpha+\\beta)^2(\\alpha+\\beta+1)}}.\n$$\n\nRecall the delta method $\\widehat{\\mathrm{Var}}[\\tau(\\hat\\theta)] \\approx \\nabla\\tau(\\hat\\theta)^\\top \\widehat{\\mathrm{Var}}(\\hat\\theta) \\nabla\\tau(\\hat\\theta)$. Here, we use a numerical $\\nabla\\tau(\\hat\\theta)$ computed using `numDeriv::grad()`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(numDeriv)   # for numerical gradients\n\n# define tau(theta) = sigma(alpha, beta)\nsigma_fn <- function(theta) {\n  a <- theta[1]; b <- theta[2]\n  sqrt( (a*b) / ((a + b)^2 * (a + b + 1)) )\n}\n\n# numerical gradient of tau at (a, b)\ngrad_sigma <- grad(func = sigma_fn, x = fit$theta_hat)\ngrad_sigma   # 2 x 1 gradient vector evaluated at (a, b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  0.0001263342 -0.0001908174\n```\n\n\n:::\n\n```{.r .cell-code}\n# delta method variance and SE\nvar_hat_sigma <- t(grad_sigma) %*% fit$var_hat %*% grad_sigma\nse_hat_sigma  <- sqrt(var_hat_sigma)\n\nvar_hat_sigma\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             [,1]\n[1,] 1.313558e-06\n```\n\n\n:::\n\n```{.r .cell-code}\nse_hat_sigma\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            [,1]\n[1,] 0.001146105\n```\n\n\n:::\n:::\n\n\n\n:::\n\n## Turnout rates\n\nLoad a [tibble version of the 2024 turnout data](https://gist.github.com/carlislerainey/fda3b4eb7e95d50949a445d9ae7f02c8) from the [UF Election Lab](https://election.lab.ufl.edu/2024-general-election-turnout/) into R. \n\n\nModel the proportion of the voting-eligible population that voted using a beta distribution. Estimate the parameters of the beta distribution $\\alpha$ and $\\beta$ as well as the mean $\\mu = \\frac{\\alpha}{\\alpha + \\beta}$ and the SD $\\sigma = \\sqrt{\\frac{\\alpha \\beta}{(\\alpha + \\beta)^2 (\\alpha + \\beta + 1)}}$\n}$. Use a parametric bootstrap to estimate the SE of each.\n\n::: {.content-visible when-meta=\"solutions\"} \n\n**Solution**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load packages\nlibrary(tidyverse)\nlibrary(tinytable)\n\n# load data as tibble \nturnout_2024 <- tribble(\n  ~state,             ~vep_turnout,\n  \"Alabama\",          0.5893,\n  \"Alaska\",           0.6378,\n  \"Arizona\",          0.6360,\n  \"Arkansas\",         0.5348,\n  \"California\",       0.6206,\n  \"Colorado\",         0.7314,\n  \"Connecticut\",      0.6708,\n  \"Delaware\",         0.6702,\n  \"District of Columbia\", 0.6357,\n  \"Florida\",          0.6671,\n  \"Georgia\",          0.6826,\n  \"Hawaii\",           0.5027,\n  \"Idaho\",            0.6344,\n  \"Illinois\",         0.6325,\n  \"Indiana\",          0.5869,\n  \"Iowa\",             0.7078,\n  \"Kansas\",           0.6318,\n  \"Kentucky\",         0.6219,\n  \"Louisiana\",        0.6077,\n  \"Maine\",            0.7424,\n  \"Maryland\",         0.6930,\n  \"Massachusetts\",    0.6803,\n  \"Michigan\",         0.7464,\n  \"Minnesota\",        0.7635,\n  \"Mississippi\",      0.5745,\n  \"Missouri\",         0.6434,\n  \"Montana\",          0.6820,\n  \"Nebraska\",         0.6796,\n  \"Nevada\",           0.6580,\n  \"New Hampshire\",    0.7405,\n  \"New Jersey\",       0.6724,\n  \"New Mexico\",       0.5957,\n  \"New York\",         0.6044,\n  \"North Carolina\",   0.7032,\n  \"North Dakota\",     0.6310,\n  \"Ohio\",             0.6539,\n  \"Oklahoma\",         0.5328,\n  \"Oregon\",           0.7194,\n  \"Pennsylvania\",     0.7143,\n  \"Rhode Island\",     0.6328,\n  \"South Carolina\",   0.6214,\n  \"South Dakota\",     0.6400,\n  \"Tennessee\",        0.5761,\n  \"Texas\",            0.5657,\n  \"Utah\",             0.6415,\n  \"Vermont\",          0.7089,\n  \"Virginia\",         0.7119,\n  \"Washington\",       0.7017,\n  \"West Virginia\",    0.5546,\n  \"Wisconsin\",        0.7664,\n  \"Wyoming\",          0.6128\n)\n\n# beta log-likelihood\nbeta_ll_fn <- function(theta, y) { \n  alpha <- theta[1] \n  beta <- theta[2] \n  ll <- sum(dbeta(y, shape1 = alpha, shape2 = beta, log = TRUE))\n  return(ll)\n}\n\n# create a function to fit the beta model\nest_beta <- function(y) {\n  est <- optim(par = c(3, 3), fn = beta_ll_fn, y = y,\n               control = list(fnscale = -1),\n               method = \"BFGS\") # for >1d problems\n  if (est$convergence != 0) print(\"Model did not converge!\")\n  res <- list(est = est$par)\n  return(res)\n}\n\n# ml estimates\nml_est <- est_beta(turnout_2024$vep_turnout)\na <- ml_est$est[1]; a  # alpha\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 39.59784\n```\n\n\n:::\n\n```{.r .cell-code}\nb <- ml_est$est[2]; b  # beta\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 21.29332\n```\n\n\n:::\n\n```{.r .cell-code}\na / (a + b)  # mean; using a and b for readability\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6503053\n```\n\n\n:::\n\n```{.r .cell-code}\nsqrt( (a * b) / ((a + b)^2 * (a + b + 1)) ) # SD\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.06061623\n```\n\n\n:::\n\n```{.r .cell-code}\n# parametric bootstrap\nn_bs <- 100\nbs_alpha <- \n  bs_beta <- \n  bs_mu <-\n  bs_sigma <-\n  numeric(n_bs)  # containers for the estimates\n\nfor (i in 1:n_bs) {\n  # bootstrap sample\n  bs_y <- rbeta(length(y), shape1 = ml_est$est[1], shape2 = ml_est$est[2])\n  \n  # fit model to bootstrapped sample\n  bs_est <- est_beta(bs_y)\n  \n  # store ml estimates of alpha and beta for readability below\n  bs_a <- bs_est$est[1]\n  bs_b <- bs_est$est[2]\n\n  # compute and store all qis\n  bs_alpha[i] <- bs_a\n  bs_beta[i]  <- bs_b\n  bs_mu[i]    <- bs_a / (bs_a + bs_b)\n  bs_sigma[i] <- sqrt( (bs_a * bs_b) / ((bs_a + bs_b)^2 * (bs_a + bs_b + 1)) )\n}\n\n# bootstrap SEs\nse_alpha <- sd(bs_alpha)\nse_beta  <- sd(bs_beta)\nse_mu    <- sd(bs_mu)\nse_sigma <- sd(bs_sigma)\n\n# tinytable (avoid underscores in visible labels)\ntab_df <- tibble::tibble(\n  Parameter     = c(\"$\\\\alpha$\", \"$\\\\beta$\", \"$\\\\mu$\", \"$\\\\sigma$\"),\n  `ML estimate` = c(a_hat = a, \n                    b_hat = b, \n                    mu_hat = a / (a + b), \n                    sigma_hat = sqrt( (a * b) / ((a + b)^2 * (a + b + 1)) )),\n  `Bootstrap SE`= c(se_alpha, se_beta, se_mu, se_sigma)\n)\ntt(\n  tab_df,\n  digits = 3,\n  caption = \"Beta model: ML estimates and parametric-bootstrap standard errors.\",\n)\n```\n\n::: {.cell-output-display}\n\\begin{table}[H]\n\\centering\n\\begin{talltblr}[         %% tabularray outer open\ncaption={Beta model: ML estimates and parametric-bootstrap standard errors.},\n]                     %% tabularray outer close\n{                     %% tabularray inner open\ncolspec={Q[]Q[]Q[]},\n}                     %% tabularray inner close\n\\toprule\nParameter & ML estimate & Bootstrap SE \\\\ \\midrule %% TinyTableHeader\n$\\alpha$ & 39.5978 & 1.4765 \\\\\n$\\beta$ & 21.2933 & 0.78647 \\\\\n$\\mu$ & 0.6503 & 0.00209 \\\\\n$\\sigma$ & 0.0606 & 0.00112 \\\\\n\\bottomrule\n\\end{talltblr}\n\\end{table}\n:::\n:::\n\n\n\n:::\n\n\n\n\n## `duration`\n\n**Part 1.** *Parametric models.*\n\nModel `duration` in the `coalition` data set (from the **brglm2** package) using three different distributions: an exponential distribution, a Weibull distribution, and a log-normal distribution. \n\nFor each distribution:\n\n1. Estimate the parameter(s) using maximum likelihood.\n1. Estimate the covariance matrix. \n1. Estimate the mean using the invariance property.\n1. Estimate the SE using the delta method.\n\n*Hint:* Use `optim()` and `numDeriv::grad()`. Complete each step for the exponential model, then copy-and-paste the code and make the needed changes for the Weibull and log-normal.\n\n**Part 2.** Classical estimate.\n\nCompute the classical mean and SE estimates by taking the average $\\hat\\mu = \\operatorname{avg}(y)$ and the standard error $\\widehat{\\mathrm{SE}}(\\hat\\mu) = \\dfrac{\\operatorname{SD}(y)}{\\sqrt{N}}$.\n\n**Part 3.**\n\nCompare these four estimates and their standard error estimates. What stands out? Explain.\n\n**Some Background.**\n\nWhen we model duration data, we often focus on the hazard function, which describes the relative chance of an event at time $t$, given that the unit has survived until $t$. The hazard tells us how the risk of failure changes with time.\n\nThe *exponential distribution* is the simplest model. The density is\n$$\nf(t \\mid \\lambda) = \\lambda e^{-\\lambda t}, \\quad t > 0, \\; \\lambda > 0,\n$$\nand the mean is $\\mathbb{E}[T] = 1/\\lambda$. The hazard is $h(t) = \\lambda$, which is constant over time. This means the chance of failure in the next instant does not depend on how long the unit has lasted so far. This \"memoryless\" property makes the exponential convenient, but often unrealistic.\n\nThe *Weibull distribution* generalizes the exponential by allowing the hazard to change with time. The density is\n$$\nf(t \\mid k, \\lambda) = \\frac{k}{\\lambda}\\left(\\frac{t}{\\lambda}\\right)^{k-1}\n  \\exp\\!\\left[-\\left(\\frac{t}{\\lambda}\\right)^k\\right], \\quad t > 0, \\; k,\\lambda > 0,\n$$\nand the mean is $\\mathbb{E}[T] = \\lambda \\,\\Gamma\\!\\big(1 + 1/k\\big)$. The hazard is\n$$\nh(t) = \\frac{k}{\\lambda}\\left(\\frac{t}{\\lambda}\\right)^{k-1}.\n$$\nWhen $k = 1$, this reduces to the exponential with a constant hazard. If $k > 1$, the hazard increases with time, which might capture processes like aging or wear-out. If $k < 1$, the hazard decreases with time, which might represent situations where early failures are more likely. This flexibility makes the Weibull especially useful.\n\nThe *lognormal distribution* assumes that the log of the durations is normally distributed. The density is\n$$\nf(t \\mid \\mu, \\sigma) = \\frac{1}{t\\sigma \\sqrt{2\\pi}}\n  \\exp\\!\\left(-\\frac{(\\ln t - \\mu)^2}{2\\sigma^2}\\right), \\quad t > 0, \\; \\sigma > 0,\n$$\nand the mean is $\\mathbb{E}[T] = \\exp(\\mu + \\tfrac{1}{2}\\sigma^2)$. The hazard is non-monotone: it starts low, rises for a while, and then falls. This \"hump-shaped\" hazard works well when events are most likely after some waiting time, but less likely if they haven’t occurred by then—for example, the adoption of a new technology or the incubation period of a disease.\n\n\n::: {.content-visible when-meta=\"solutions\"}\n\n**Solution.**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load packages\nlibrary(brglm2)\nlibrary(numDeriv)\n\n# data\ndata(\"coalition\", package = \"brglm2\")\ny <- coalition$duration\n```\n:::\n\n\n\n**1) Exponential model.**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# log-likelihood\nlog_lik <- function(lambda, y) {\n  sum(dexp(y, rate = lambda, log = TRUE))\n}\n\n# find ml estimate\nfit <- optim(\n  par     = 1,\n  fn      = log_lik,\n  y       = y,\n  method  = \"BFGS\",\n  control = list(fnscale = -1),\n  hessian = TRUE\n)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in dexp(y, rate = lambda, log = TRUE): NaNs produced\nWarning in dexp(y, rate = lambda, log = TRUE): NaNs produced\nWarning in dexp(y, rate = lambda, log = TRUE): NaNs produced\nWarning in dexp(y, rate = lambda, log = TRUE): NaNs produced\nWarning in dexp(y, rate = lambda, log = TRUE): NaNs produced\nWarning in dexp(y, rate = lambda, log = TRUE): NaNs produced\nWarning in dexp(y, rate = lambda, log = TRUE): NaNs produced\nWarning in dexp(y, rate = lambda, log = TRUE): NaNs produced\nWarning in dexp(y, rate = lambda, log = TRUE): NaNs produced\nWarning in dexp(y, rate = lambda, log = TRUE): NaNs produced\nWarning in dexp(y, rate = lambda, log = TRUE): NaNs produced\nWarning in dexp(y, rate = lambda, log = TRUE): NaNs produced\nWarning in dexp(y, rate = lambda, log = TRUE): NaNs produced\nWarning in dexp(y, rate = lambda, log = TRUE): NaNs produced\nWarning in dexp(y, rate = lambda, log = TRUE): NaNs produced\nWarning in dexp(y, rate = lambda, log = TRUE): NaNs produced\nWarning in dexp(y, rate = lambda, log = TRUE): NaNs produced\nWarning in dexp(y, rate = lambda, log = TRUE): NaNs produced\nWarning in dexp(y, rate = lambda, log = TRUE): NaNs produced\n```\n\n\n:::\n\n```{.r .cell-code}\nlambda_hat <- fit$par\n\n# covariance \ninfo_obs <- -fit$hessian\nvar_hat  <- solve(info_obs)\n\n# invariance property + delta method\ntau <- function(lambda) 1 / lambda\nmean_hat_exp <- tau(lambda_hat)\ng <- grad(tau, x = lambda_hat)  # 1x1 gradient\nvar_mean <- t(g) %*% var_hat %*% g\nse_mean_exp  <- sqrt(var_mean)\n\n# print key results\nlambda_hat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0542343\n```\n\n\n:::\n\n```{.r .cell-code}\nmean_hat_exp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 18.43851\n```\n\n\n:::\n\n```{.r .cell-code}\nse_mean_exp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         [,1]\n[1,] 1.040192\n```\n\n\n:::\n:::\n\n\n\n**2) Weibull model.**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# log-likelihood\nlog_lik <- function(theta, y) {\n  k  <- theta[1]\n  s <- theta[2]\n  sum(dweibull(y, shape = k, scale = s, log = TRUE))\n}\n\n# find ml estimate\nfit <- optim(\n  par     = c(1, 1),\n  fn      = log_lik,\n  y       = y,\n  method  = \"BFGS\",\n  control = list(fnscale = -1),\n  hessian = TRUE\n)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in dweibull(y, shape = k, scale = s, log = TRUE): NaNs produced\nWarning in dweibull(y, shape = k, scale = s, log = TRUE): NaNs produced\nWarning in dweibull(y, shape = k, scale = s, log = TRUE): NaNs produced\nWarning in dweibull(y, shape = k, scale = s, log = TRUE): NaNs produced\nWarning in dweibull(y, shape = k, scale = s, log = TRUE): NaNs produced\nWarning in dweibull(y, shape = k, scale = s, log = TRUE): NaNs produced\nWarning in dweibull(y, shape = k, scale = s, log = TRUE): NaNs produced\nWarning in dweibull(y, shape = k, scale = s, log = TRUE): NaNs produced\nWarning in dweibull(y, shape = k, scale = s, log = TRUE): NaNs produced\nWarning in dweibull(y, shape = k, scale = s, log = TRUE): NaNs produced\nWarning in dweibull(y, shape = k, scale = s, log = TRUE): NaNs produced\nWarning in dweibull(y, shape = k, scale = s, log = TRUE): NaNs produced\nWarning in dweibull(y, shape = k, scale = s, log = TRUE): NaNs produced\nWarning in dweibull(y, shape = k, scale = s, log = TRUE): NaNs produced\nWarning in dweibull(y, shape = k, scale = s, log = TRUE): NaNs produced\nWarning in dweibull(y, shape = k, scale = s, log = TRUE): NaNs produced\nWarning in dweibull(y, shape = k, scale = s, log = TRUE): NaNs produced\nWarning in dweibull(y, shape = k, scale = s, log = TRUE): NaNs produced\nWarning in dweibull(y, shape = k, scale = s, log = TRUE): NaNs produced\nWarning in dweibull(y, shape = k, scale = s, log = TRUE): NaNs produced\nWarning in dweibull(y, shape = k, scale = s, log = TRUE): NaNs produced\nWarning in dweibull(y, shape = k, scale = s, log = TRUE): NaNs produced\n```\n\n\n:::\n\n```{.r .cell-code}\nk_hat  <- fit$par[1]\ns_hat <- fit$par[2]\n\n# covariance \ninfo_obs <- -fit$hessian\nvar_hat  <- solve(info_obs)\n\n# invariance property + delta method\ntau <- function(theta) {\n  k <- theta[1]\n  s <- theta[2]\n  s * gamma(1 + 1/k)\n}\nmean_hat_weib <- tau(c(k_hat, s_hat))\ng <- numDeriv::grad(tau, x = c(k_hat, s_hat)) \nvar_mean <- t(g) %*% var_hat %*% g\nse_mean_weib  <- sqrt(var_mean)\n\n# print key results\nk_hat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.138367\n```\n\n\n:::\n\n```{.r .cell-code}\ns_hat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 19.28594\n```\n\n\n:::\n\n```{.r .cell-code}\nmean_hat_weib\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 18.40969\n```\n\n\n:::\n\n```{.r .cell-code}\nse_mean_weib\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          [,1]\n[1,] 0.9138076\n```\n\n\n:::\n:::\n\n\n\n**3) Log-normal model.**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# log-likelihood\nlog_lik <- function(theta, y) {\n  mu  <- theta[1]\n  sig <- theta[2]\n  sum(dlnorm(y, meanlog = mu, sdlog = sig, log = TRUE))\n}\n\n# find ml estimate\nfit <- optim(\n  par     = c(0, 1),\n  fn      = log_lik,\n  y       = y,\n  method  = \"BFGS\",\n  control = list(fnscale = -1),\n  hessian = TRUE\n)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in dlnorm(y, meanlog = mu, sdlog = sig, log = TRUE): NaNs produced\nWarning in dlnorm(y, meanlog = mu, sdlog = sig, log = TRUE): NaNs produced\nWarning in dlnorm(y, meanlog = mu, sdlog = sig, log = TRUE): NaNs produced\nWarning in dlnorm(y, meanlog = mu, sdlog = sig, log = TRUE): NaNs produced\nWarning in dlnorm(y, meanlog = mu, sdlog = sig, log = TRUE): NaNs produced\nWarning in dlnorm(y, meanlog = mu, sdlog = sig, log = TRUE): NaNs produced\nWarning in dlnorm(y, meanlog = mu, sdlog = sig, log = TRUE): NaNs produced\nWarning in dlnorm(y, meanlog = mu, sdlog = sig, log = TRUE): NaNs produced\nWarning in dlnorm(y, meanlog = mu, sdlog = sig, log = TRUE): NaNs produced\nWarning in dlnorm(y, meanlog = mu, sdlog = sig, log = TRUE): NaNs produced\n```\n\n\n:::\n\n```{.r .cell-code}\nmu_hat  <- fit$par[1]\nsig_hat <- fit$par[2]\n\n# covariance \ninfo_obs <- -fit$hessian\nvar_hat  <- solve(info_obs)\n\n# invariance property + delta method\ntau <- function(theta) {\n  mu  <- theta[1]\n  sig <- theta[2]\n  exp(mu + 0.5 * sig^2)\n}\nmean_hat_lnorm <- tau(c(mu_hat, sig_hat))\ng <- numDeriv::grad(tau, x = c(mu_hat, sig_hat)) \nvar_mean <- t(g) %*% var_hat %*% g\nse_mean_lnorm  <- sqrt(var_mean)\n\n# print key results\nmu_hat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.4355\n```\n\n\n:::\n\n```{.r .cell-code}\nsig_hat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.147172\n```\n\n\n:::\n\n```{.r .cell-code}\nmean_hat_lnorm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 22.05417\n```\n\n\n:::\n\n```{.r .cell-code}\nse_mean_lnorm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         [,1]\n[1,] 1.838451\n```\n\n\n:::\n:::\n\n\n\n**4) Classical.**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# classical mean and SE of coalition$duration\nmean_classical <- mean(coalition$duration)\nse_classical   <- sd(coalition$duration) / sqrt(length(coalition$duration))\n\nmean_classical\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 18.4379\n```\n\n\n:::\n\n```{.r .cell-code}\nse_classical\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8553566\n```\n\n\n:::\n:::\n\n\n\n**A summary table.**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tinytable)\n\n# collect results including classical\nres <- data.frame(\n  Model = c(\"Classical\", \"Exponential\", \"Weibull\", \"Log-normal\"),\n  Mean  = c(mean_classical, mean_hat_exp, mean_hat_weib, mean_hat_lnorm),\n  SE    = c(se_classical,   se_mean_exp,  se_mean_weib,  se_mean_lnorm)\n)\n\n# format nicely\ntt(\n  res,\n  digits = 4,\n  align  = \"lrr\"\n)\n```\n\n::: {.cell-output-display}\n\\begin{table}[H]\n\\centering\n\\begin{tblr}[         %% tabularray outer open\n]                     %% tabularray outer close\n{                     %% tabularray inner open\ncolspec={Q[]Q[]Q[]},\n}                     %% tabularray inner close\n\\toprule\nModel & Mean & SE \\\\ \\midrule %% TinyTableHeader\nClassical & 18.44 & 0.8554 \\\\\nExponential & 18.44 & 1.0402 \\\\\nWeibull & 18.41 & 0.9138 \\\\\nLog-normal & 22.05 & 1.8385 \\\\\n\\bottomrule\n\\end{tblr}\n\\end{table}\n:::\n:::\n\n\nHowever, while these models make different parametric assumptions, they all fit the observed durations moderately well. At least none severely deviates from the observed pattern.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](wk03-exr-sol_files/figure-pdf/unnamed-chunk-20-1.pdf)\n:::\n:::\n\n\n\n\n\n\n:::\n\n\n## Two CIs\n\nConsider a simple Bernoulli model for $y \\in \\{0,1\\}$ with parameter $\\pi \\in [0,1]$. Create a small sample with a rare event: take $N = 20$ trials with exactly one success.\n\n**Part 1.** *Wald confidence interval.*\n\nCompute the ML estimate $\\hat \\pi = \\operatorname{avg}(y)$, the Wald SE $\\widehat{\\mathrm{SE}}(\\hat \\pi) = \\sqrt{\\hat \\pi(1-\\hat \\pi)/N}$, and the usual $95\\%$ Wald confidence interval $\\hat \\pi \\pm 1.96 \\cdot\\widehat{\\mathrm{SE}}(\\hat \\pi)$. What do you notice about the interval relative to the parameter space $[0,1]$?\n\n**Part 2.** *Parametric bootstrap confidence interval.*\n\nUse a *parametric bootstrap* to obtain a $95\\%$ percentile confidence interval for $\\pi$ based on the fitted model $\\text{Bernoulli}(\\hat \\pi)$. Compare the bootstrap interval with the Wald interval. What stands out? Briefly explain.\n\n*Hint:* For the bootstrap, repeatedly simulate $y^{*(b)}_1,\\dots,y^{*(b)}_N \\stackrel{iid}{\\sim} \\text{Bernoulli}(\\hat \\pi)$, recompute $\\hat \\pi^{*(b)} = \\operatorname{avg}(y^{*(b)})$, and then take the empirical $2.5^\\text{th}$ and $97.5^\\text{th}$ percentiles of $\\{\\hat \\pi^{*(b)}\\}$.\n\n::: {.content-visible when-meta=\"solutions\"}\n\n**Solution.**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\n\n# data: N = 20 with exactly one success\nN <- 20\ny <- c(1, rep(0, N - 1))  # rare event sample\ny <- sample(y)            # shuffle (irrelevant, but tidy)\n\n# ml estimate and wald 95%ci\npi_hat   <- mean(y)\nse <- sqrt(pi_hat * (1 - pi_hat) / N)\nwald_ci <- pi_hat + c(-1, 1) * 1.96 * se\n\npi_hat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.05\n```\n\n\n:::\n\n```{.r .cell-code}\nse\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.04873397\n```\n\n\n:::\n\n```{.r .cell-code}\nwald_ci\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.04551858  0.14551858\n```\n\n\n:::\n:::\n\n\n\nThe Wald interval extends below 0, which is outside the parameter space $[0,1]$.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# parametric bootstrap w/ percentile 95% ci\nn_bs <- 2000\nbs_est <- numeric(n_bs)  # a container for the estimates\nfor (i in 1:n_bs) {\n  bs_y <- rbinom(20, size = 1, prob = pi_hat)\n  bs_est[i] <- mean(bs_y)\n}\n\nprint(quantile(bs_est, probs = c(0.025, 0.975)), digits = 2)  # 95% ci\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n 2.5% 97.5% \n 0.00  0.15 \n```\n\n\n:::\n:::\n\n\n\nThe Wald interval uses a normal approximation centered at $\\hat \\pi$ with variance estimated by Fisher information. With extreme $\\hat \\pi$ near zero and small $N$, this approximation is poor and the lower bound of the CI can dip below 0. In contrast, the parametric bootstrap respects the model's support by construction (every $\\hat \\pi^{*(b)} \\in [0,1]$), so the percentile interval stays within $[0,1]$ and typically provides more reasonable coverage in this setting.\n\n:::\n\n",
    "supporting": [
      "wk03-exr-sol_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "\\usepackage{float}\n\\usepackage{tabularray}\n\\usepackage[normalem]{ulem}\n\\usepackage{graphicx}\n\\usepackage{rotating}\n\\UseTblrLibrary{booktabs}\n\\UseTblrLibrary{siunitx}\n\\NewTableCommand{\\tinytableDefineColor}[3]{\\definecolor{#1}{#2}{#3}}\n\\newcommand{\\tinytableTabularrayUnderline}[1]{\\underline{#1}}\n\\newcommand{\\tinytableTabularrayStrikeout}[1]{\\sout{#1}}\n"
      ]
    },
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}