{
  "hash": "9500f967bfc95f56214b47e17ec69934",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 2 Exercises\"\ndistributed: 2026-09-01\nshow-hints: true\n---\n\n\n\nDo all the exercises below. The Extra Practice problems at the end are optional.\n\n\n\n\n\n\n\n# Maximum Likelihood\n\n## A Function of What? {ref=\"function-of-what\"}\n\nFor the Bernoulli model, we wrote the likelihood as $L(\\pi) = \\pi^{k}(1 - \\pi)^{(N - k)}$, where $k$ is the number of successes in $N$ trials. In this expression, which symbol is the variable, and which symbols are fixed? In one sentence describe the question that $L(\\pi)$ answers.\n\n::: hint\n\nIn the pmf $f(x; \\pi)$, we treat $\\pi$ as fixed and $x$ as the variable. What changed when we relabeled $f(x; \\pi)$ as $L(\\pi)$? \n\n:::\n\n::: hint\n\nBefore the notes ever write $L(\\pi)$, the Bernoulli section evaluates the same fixed toothpaste-cap data at several candidate values of $\\pi$ (0.1, 0.45, 0.55, and 0.9), one at a time. Reread that paragraph.\n\n:::\n\n::: sol\n\nThe likelihood flips the usual roles compared to $f(x; \\pi)$. For the likelihood, the data are fixed (we observed them!), and the parameter varies. In $L(\\pi)$, the variable is $\\pi$. The data (or summaries $k$ and $N$, in this case) are fixed numbers. $L(\\pi)$ answers the question: *if the parameter were $\\pi$, how likely would these data be?* ML then picks the $\\pi$ that makes the observed data most likely.\n\n**Something that's wrong**: the likelihood is *not* a probability distribution over $\\pi$. It doesn't integrate to one. It does not allow a probability claim about the parameter.\n\n:::\n\n## Why the Log? Predict, Then Check {ref=\"why-the-log\"}\n\nSuppose you observe 2,000 Bernoulli trials with $\\pi = 0.5$, so each observation has probability exactly 0.5. The likelihood is the product of these 2,000 probabilities.\n\nPredict what the first line below returns *before you run it*, and write down your reasoning.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\ny <- rbinom(2000, 1, 0.5)\n\nprod(dbinom(y, 1, 0.5))             # the likelihood, computed directly\nsum(dbinom(y, 1, 0.5, log = TRUE))  # the log-likelihood\n```\n:::\n\n\n\nNow run both lines. Explain what happened, why it's expected, and why it matters for ML. The log fixes this computational problem, but it also helps with the calculus. How?\n\n::: hint\n\nEach of the 2,000 factors equals 0.5, so the product is $0.5^{2000}$. Figure out roughly how big that is as a power of ten. Compare that to the smallest positive number R can store (i.e., run `.Machine$double.xmin`).\n\nA rule of thumb: $2^{10} = 1024 \\approx 10^3$. Thus, ten halvings cost about three orders of magnitude. \n\n:::\n\n::: hint\n\nThe notes give two separate reasons for taking the log (i.e., where they define $L(\\pi)$ in the Bernoulli example). One reason is what you just watched happen in R. The other reason is about calculus.\n\n:::\n\n::: sol\n\nStart with the prediction. Each factor is 0.5, so the product is $0.5^{2000} \\approx 10^{-600}$. Computers can't track numbers that small (the smallest positive number R can store is about $10^{-308}$; run `.Machine$double.xmin`), so `prod()` returns exactly 0.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\ny <- rbinom(2000, 1, 0.5)\n\nprod(dbinom(y, 1, 0.5))             # the likelihood, computed directly\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(dbinom(y, 1, 0.5, log = TRUE))  # the log-likelihood\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -1386.294\n```\n\n\n:::\n:::\n\n\n\nThe log-likelihood works just fine, though. It's $2000 \\log(0.5) \\approx -1386.29$. This is a very ordinary number that computers can handle.\n\n(Importantly, a hill-climbing algorithm can't climb a function that returns 0 everywhere!)\n\nAnd this matters for the calculus, too. The log turns the product into a sum. Derivatives are much easier with sums. \n\n:::\n\n## What a Grid Can Miss {ref=\"grid-miss\"}\n\nSuppose a colleague estimates a Bernoulli $\\pi$ by computing the log-likelihood at the eleven values $0, 0.1, 0.2, \\ldots, 1$ and reporting the best of the eleven as \"the ML estimate.\" In one or two sentences, in what sense is that answer wrong, and how would you tighten it? (If you'd like to actually run a grid search, that's [ep-grid]{.ex-ref}.)\n\n::: sol\n\nA grid can *bracket* the maximum, but it almost never *contains* it. The true ML estimate is $k/N$. Unless we're lucky, this will not be a multiple of 0.1. To tighten the answer, we could make the grid finer near the peak (or just use calculus or `optim()`).\n\n:::\n\n## From Derivative to Estimator {ref=\"deriv-to-est\"}\n\nLast week, you found $\\frac{d\\ell}{d\\pi}$ for $\\ell(\\pi) = S \\log(\\pi) + (N - S)\\log(1 - \\pi)$. Set the derivative equal to zero and solve for $\\hat{\\pi}$.\n\n::: sol\n\nWe have $\\frac{d\\ell}{d\\pi} = \\frac{S}{\\pi} - \\frac{N - S}{1 - \\pi}$. Setting it to zero at $\\pi = \\hat{\\pi}$ and clearing the fractions, we obtain\n\n$$\n\\begin{aligned}\n\\frac{S}{\\hat{\\pi}} &= \\frac{N - S}{1 - \\hat{\\pi}} \\\\\nS(1 - \\hat{\\pi}) &= (N - S)\\hat{\\pi} \\\\\nS - S\\hat{\\pi} &= N\\hat{\\pi} - S\\hat{\\pi} \\\\\nS &= N\\hat{\\pi} \\\\\n\\hat{\\pi} &= \\frac{S}{N}.\n\\end{aligned}\n$$\n\nThe ML estimate is the fraction of successes (the sample average of the 0s and 1s).\n\n:::\n\n## Reading a Contour Plot {ref=\"contour\"}\n\nThe plot below shows the log-likelihood for the notes' beta-distribution example. We have 100 observations (simulated from a beta distribution). I computed the log-likelihood $\\log L(\\alpha, \\beta)$ over a grid of parameter pairs.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](wk02-exercises_files/figure-html/ex05-contour-1.png){width=768}\n:::\n:::\n\n\n\na. Roughly where is the ML estimate?\nb. What does a single labeled curve on this plot mean?\nc. For the Bernoulli model, we found $\\hat{\\pi}$ with pencil and paper. Why can't we do that here?\n\n::: {.hint label=\"For part (a)\"}\n\nEach labeled curve gives the log-likelihood value along it; higher numbers sit closer to the peak. Find the region where the labeled values are highest and read off its $(\\alpha, \\beta)$ coordinates.\n\n:::\n\n::: {.hint label=\"For part (b)\"}\n\nThe plot shows the height of $\\log L(\\alpha, \\beta)$. Along one curve, what is constant?\n\n:::\n\n::: {.hint label=\"For part (c)\"}\n\nLook back at what stopped us in the notes' beta example.\n\n:::\n\n::: sol\n\n**Part (a)** At the center of the innermost region, around $\\alpha = 12$, $\\beta = 12$. (The notes' `optim()` run puts it at $\\hat{\\alpha} \\approx 12.0$ and $\\hat{\\beta} \\approx 11.9$.)\n\n**Part (b)** A curve is a *level set*, such that every pair $(\\alpha, \\beta)$ on that curve produces the same value of the log-likelihood.\n\n**Part (c)** The beta log-likelihood contains $\\log B(\\alpha, \\beta)$. We can *evaluate* that term for any $\\alpha$ and $\\beta$ we like (R's `lbeta()` does it instantly), but differentiating it and setting the two derivatives to zero leaves a pair of equations we can't solve for $\\alpha$ and $\\beta$ on paper. An *intractable* likelihood means we have no closed-form maximizer. (This is the usual situation; our first few tractable models are the exceptions.)\n\n:::\n\n## Diagnose the Error {ref=\"diagnose-fnscale\"}\n\nA classmate wants the ML estimate of a Poisson rate $\\lambda$ for the data below, and their code runs without an error or a warning:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny <- c(12, 7, 9, 12, 10)\n\nll_pois <- function(par, y) {\n  sum(dpois(y, lambda = par, log = TRUE))\n}\n\nest <- optim(par = 1,\n             fn = ll_pois,\n             y = y,\n             method = \"Brent\",\n             lower = 0.001, upper = 100)\nest$par\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 100\n```\n\n\n:::\n:::\n\n\n\nBut the estimate is absurd. The average of `y` is 10, but $\\hat{\\lambda}$ comes back as 100. What went wrong? What's the fix? What is the *category* of the mistake: a typo, an algebra slip, or something else?\n\n::: hint\n\nWhen you hand `optim()` a function what does it do by default: maximize or minimize? See the Details section of `?optim`.\n\n:::\n\n::: sol\n\n`optim()` is a *minimizer* by default. By default it looks for the \"minimum likelihood.\" But the Poisson log-likelihood always gets smaller as $\\lambda$ moves away from the average of `y`. The search \"climbed\" to the edge of the parameter space (i.e., [0.001 to 100]) and stopped.\n\nDon't read too much into *which* bound `optim()` found. `method = \"Brent\"` assumes the function has a single interior minimum. In this case, the log-likelihood at `lower = 0.001` is even smaller than at `upper = 100`, so `optim()` didn't even land on the smaller of the two endpoints. It just climbed downhill (in the wrong direction!) until it ran out of space.\n\nThe fix is `control = list(fnscale = -1)`. This flips the function over, which turns a minimizer into a maximizer.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nest <- optim(par = 1,\n             fn = ll_pois,\n             y = y,\n             control = list(fnscale = -1),\n             method = \"Brent\",\n             lower = 0.001, upper = 100)\nest$par\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10\n```\n\n\n:::\n:::\n\n\n\nNow $\\hat{\\lambda} = 10$, which matches the closed form.\n\nIt's not a typo and it's not algebra. The code computed exactly what it was told to compute. It is a misuse of the tool (or a misunderstanding of how the tool works). This is a dangerous category of error. No error or warning appeared. \n\n:::\n\n## Trust It or Not? {ref=\"trust-optim\"}\n\nYour `optim()` call returns `$convergence = 1`, and `$par` equals the upper bound you supplied. Do you trust the estimate? What do you check or change next?\n\n::: hint\n\n`?optim`'s Value section documents every code `$convergence` can return, not only `0`. Look up what `1` means there before you decide anything else.\n\n:::\n\n::: sol\n\nNo. `$convergence = 1` means the algorithm hit its iteration limit without converging (see `?optim`). A parameter estimate sitting exactly on a boundary is a red flag.\n\n:::\n\n## An Unfamiliar Density {ref=\"unfamiliar-density\"}\n\nSuppose a random variable has pdf $f(x; \\theta) = \\theta x^{\\theta - 1}$ for $0 < x < 1$ and $\\theta > 0$, and suppose we collect $N$ iid observations $x = \\{x_1, x_2, \\ldots, x_N\\}$.^[This is Exercise 9 on p. 425 of DeGroot and Schervish's *Probability and Statistics*.] Find the ML estimator of $\\theta$.\n\n::: hint\n\nWhat steps did we follow for the Bernoulli and the Poisson? Start the same way here by writing $L(\\theta)$ as a product over the observations.\n\n:::\n\n::: hint\n\nTake the log and bring the exponent down. You should end up with two terms: one involving $\\log \\theta$ and one involving $\\sum \\log x_i$.\n\n:::\n\n::: {.hint label=\"Self-check\"}\n\nYour formula and `optim()` must agree. For `x <- c(0.2, 0.5, 0.9)`, evaluate your $\\hat{\\theta}$ formula, then run the code below and compare.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(0.2, 0.5, 0.9)\n\nll_fn <- function(theta, x) {\n  sum(log(theta) + (theta - 1)*log(x))\n}\n\nest <- optim(par = 1,\n             fn = ll_fn,\n             x = x,\n             control = list(fnscale = -1),\n             method = \"Brent\",\n             lower = 0, upper = 100)\nest$par\n```\n:::\n\n\n\n:::\n\n::: sol\n\nThe recipe carries over unchanged. The only new bit is keeping track of $\\sum \\log x_i$.\n\nFirst, write down the likelihood and simplify the product:\n\n$$\nL(\\theta) = \\prod_{i = 1}^N \\theta x_i^{\\theta - 1} = \\theta^N \\prod_{i = 1}^N x_i^{\\theta - 1}.\n$$\n\nSecond, take the log. The product becomes a sum, and $\\log(a^b) = b \\log(a)$ brings the exponent down:\n\n$$\n\\log L(\\theta) = N \\log \\theta + (\\theta - 1) \\sum_{i = 1}^N \\log x_i.\n$$\n\nThird, differentiate with respect to $\\theta$:\n\n$$\n\\frac{d \\log L}{d\\theta} = \\frac{N}{\\theta} + \\sum_{i = 1}^N \\log x_i.\n$$\n\nFourth, set the derivative to zero at $\\theta = \\hat{\\theta}$ and solve:\n\n$$\n\\hat{\\theta} = \\frac{N}{-\\sum_{i = 1}^N \\log x_i}.\n$$\n\nFor the check data, $\\hat{\\theta} = 3 / [-(\\log 0.2 + \\log 0.5 + \\log 0.9)] \\approx 1.246$, and `optim()` returns the same 1.246.\n\n:::\n\n# The Invariance Property\n\n## One Line of Invariance {ref=\"invariance-one-line\"}\n\nLet $\\hat{\\theta}$ be the ML estimate of $\\theta$. Suppose we are interested in $\\psi = \\theta^2$. What is the ML estimate of $\\psi$?\n\n::: hint\n\nThis week's notes has a chapter built entirely turning an ML estimate of one quantity into an ML estimate of a function of it, without writing down a new likelihood.\n\n:::\n\n::: sol\n\nBy the invariance property, the ML estimate of a function of a parameter is the function of the ML estimate:\n\n$$\n\\hat{\\psi} = \\hat{\\theta}^2.\n$$\n\nThat's the whole answer. The brevity is the point. We don't need to derive a new likelihood for $\\psi$.\n\n:::\n\n## The Exponential Model {ref=\"exponential-model\"}\n\nThe exponential distribution has pdf $f(t; \\lambda) = \\lambda e^{-\\lambda t}$ for $t \\geq 0$ and $\\lambda > 0$. We might use the exponential distribution to model *durations*. A duration is the time until an event, such as the end of a coalition government.\n\na. Suppose we collect $N$ iid durations $t = \\{t_1, t_2, \\ldots, t_N\\}$. Find the ML estimator of $\\lambda$.\nb. The parameter $\\lambda$ is called the *rate*. The *mean* of the exponential distribution is $\\frac{1}{\\lambda}$.^[Showing this takes integration by parts; here we'll take it as known.] Give the ML estimator of the mean. \n\n::: {.hint label=\"For part (a)\"}\n\nThis is very similar to the derivation of the ML estimate of $\\lambda$ for the Poisson distribution, with one important difference. Be careful with your algebra!\n\n:::\n\n::: {.hint label=\"Self-check\"}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# simulate durations from a known rate and see whether your formulas\n# recover it\nset.seed(1)\nlambda_true <- 2\nt <- rexp(500, rate = lambda_true)\n\n# fill in your part (a) estimator, as a function of t\nlambda_hat <- NA\n\n# a numerical check: maximize the exponential log-likelihood directly\nll_fn <- function(lambda, t) sum(dexp(t, rate = lambda, log = TRUE))\nlambda_hat_numeric <- optim(par = 1, fn = ll_fn, t = t,\n                             method = \"Brent\", lower = 1e-6, upper = 20,\n                             control = list(fnscale = -1))$par\n\n# these two should agree closely\nlambda_hat\nlambda_hat_numeric\n\n# fill in your part (b) estimator, as a function of lambda_hat\nmean_hat <- NA\n\n# an independent numerical check: reparameterize the same likelihood in\n# terms of the mean and maximize over that instead\nll_fn_mean <- function(mu, t) sum(dexp(t, rate = 1 / mu, log = TRUE))\nmean_hat_numeric <- optim(par = 1, fn = ll_fn_mean, t = t,\n                           method = \"Brent\", lower = 1e-6, upper = 20,\n                           control = list(fnscale = -1))$par\n\n# these two should agree closely\nmean_hat\nmean_hat_numeric\n```\n:::\n\n\n\n:::\n\n::: sol\n\n**Part (a)** The key move is that the product of exponentials collects into a single exponential of a sum.\n\nFirst, write down the likelihood and simplify:\n\n$$\nL(\\lambda) = \\prod_{i = 1}^N \\lambda e^{-\\lambda t_i} = \\lambda^N e^{-\\lambda \\sum_{i = 1}^N t_i}.\n$$\n\nSecond, take the log. The product becomes a sum, and $\\log e^u = u$:\n\n$$\n\\log L(\\lambda) = N \\log \\lambda - \\lambda \\sum_{i = 1}^N t_i.\n$$\n\nThird, differentiate:\n\n$$\n\\frac{d \\log L}{d\\lambda} = \\frac{N}{\\lambda} - \\sum_{i = 1}^N t_i.\n$$\n\nFourth, set the derivative to zero at $\\lambda = \\hat{\\lambda}$ and solve:\n\n$$\n\\hat{\\lambda} = \\frac{N}{\\sum_{i = 1}^N t_i} = \\frac{1}{\\text{avg}(t)}.\n$$\n\nThus, the ML estimator of the rate is the reciprocal of the average duration.\n\n**Part (b)** By the invariance property, the ML estimator of the mean $\\frac{1}{\\lambda}$ is\n\n$$\n\\widehat{\\text{mean}} = \\frac{1}{\\hat{\\lambda}} = \\text{avg}(t).\n$$\n\nThe ML estimate of the mean duration is the average duration, which seems sensible.\n\n:::\n\n## Four Models, One Number {ref=\"four-models\"}\n\nSuppose you observe the binary outcome `y <- c(0, 1, 0, 1, 1, 1, 0)` and you want to estimate the *mean* of the distribution that generated it. Naturally, you'd model these data as Bernoulli and estimate $\\pi$. But suppose that instead you model these 0s and 1s with a *normal* distribution. What is your ML estimate of the mean? What if you use the Poisson? The exponential?\n\nComplete the table below: for each model, the ML estimates of the parameters, then the estimate of the mean via the invariance property. What do you notice? Explain why it happens.\n\n| Distribution | Parameter(s) | ML estimates | Estimate of the mean |\n|---|---|---|---|\n| Bernoulli | $\\pi$ | ?? | ?? |\n| Normal | $\\mu$, $\\sigma^2$ | ?? | ?? |\n| Poisson | $\\lambda$ | ?? | ?? |\n| Exponential | $\\lambda$ | ?? | ?? |\n\n::: hint\n\nFor each model, what is $E(Y)$ in terms of that model's parameter? (Three of the four means *are* the parameter. The fourth is a transformation of the parameter.)\n\n:::\n\n::: hint\n\nEstimate each model's parameters by ML (all four estimators appear in the notes or in [exponential-model]{.ex-ref}). If needed, transform the estimates with the invariance property.\n\n:::\n\n::: sol\n\nHere's the completed table, for `y` with $\\text{avg}(y) = \\frac{4}{7} \\approx 0.571$.\n\n| Distribution | Parameter(s) | ML estimates | Estimate of the mean |\n|---|---|---|---|\n| Bernoulli | $\\pi$ | $\\hat{\\pi} = \\text{avg}(y) \\approx 0.571$ | $\\hat{\\pi} \\approx 0.571$ (no transformation needed: $E(Y) = \\pi$) |\n| Normal | $\\mu$, $\\sigma^2$ | $\\hat{\\mu} = \\text{avg}(y) \\approx 0.571$ and $\\hat{\\sigma}^2 = \\frac{\\sum (y_i - \\bar{y})^2}{N} \\approx 0.245$ | $\\hat{\\mu} \\approx 0.571$ |\n| Poisson | $\\lambda$ | $\\hat{\\lambda} = \\text{avg}(y) \\approx 0.571$ | $\\hat{\\lambda} \\approx 0.571$ ($E(Y) = \\lambda$) |\n| Exponential | $\\lambda$ | $\\hat{\\lambda} = \\frac{1}{\\text{avg}(y)} = 1.75$ | $\\frac{1}{\\hat{\\lambda}} = \\text{avg}(y) \\approx 0.571$ |\n\nNo matter which distribution we use, we obtain the *identical* estimate of the mean. Not the same in expectation. Not the same asymptotically. It's the exact same number, every time. The reason: in each of these four models, setting the derivative to zero forces the model's own mean to match the sample mean. The four likelihoods use different distributions and different parameters, but every one of them lands on $\\text{avg}(y)$. \n\nAnd importantly, whatever properties one of these estimators has, the others share. If one is consistent, all are consistent. If one is unbiased, all are unbiased.\n\nThe lesson is worth stating carefully: *the quality of an estimator doesn't always depend on every part of the model being right.* It often depends on *what quantity you're targeting*. These four models agree exactly about the mean of these data. And, as [implied-sd]{.ex-ref} and the model-checking exercises below show, they disagree wildly about almost everything else.\n\n:::\n\n## N or N − 1? {ref=\"n-or-nm1\"}\n\nR's `var(y)` is *not* the ML estimate of $\\sigma^2$ for a normal model. What's the difference between the two? Which one is bigger? And does the difference matter at $N = 10{,}000$? Check your answers numerically on any vector you like.\n\n::: hint\n\nThe notes derive the ML estimator for $\\sigma^2$ by solving $\\frac{d \\log L}{d \\sigma^2} = 0$. Find that derivation. What is the denominator? Compare it to the denominator for `var()`, which is explained deep in the Details of `?var`. \n\n:::\n\n::: {.hint label=\"Self-check\"}\n\nFor the numeric check, build the sum of squared deviations from the mean. Then use the two alternative denominators. Compare each result to `var()`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# pick any vector, e.g.:\ny <- rnorm(1000)\n\nvar(y)\n\n# your ML formula for sigma^2, using y directly (not from var(y))\n```\n:::\n\n\n\n:::\n\n::: sol\n\n`var()` divides the sum of squared deviations by $N - 1$ (the classic, unbiased estimator). The ML estimator divides by $N$ (see the notes). So `var()` is bigger, by the factor $\\frac{N}{N-1}$.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\ny <- rnorm(10000, mean = 5, sd = 2)\n\nvar(y)                             # divides by N - 1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.099462\n```\n\n\n:::\n\n```{.r .cell-code}\nsum((y - mean(y))^2) / length(y)   # ml estimate: divides by N\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.099052\n```\n\n\n:::\n:::\n\n\n\nAt $N = 10{,}000$ the two differ in the fourth decimal, which is nothing in practice. But the conceptual distinction is important. They are different estimators, derived from different principles, and at small $N$ the difference can be visible.\n\n:::\n\n## The SD the Model Implies {ref=\"implied-sd\"}\n\nHolland (2015) measures the number of enforcement operations (i.e., a \"count\") against street vendors across districts in three Latin American cities. The data are in `crdata::holland2015`.^[`crdata` isn't on CRAN. Install it once with `remotes::install_github(\"carlislerainey/crdata\")`.] The notes estimated the Poisson rate $\\lambda$ separately for each city. Now let's estimate the standard deviation of the number of operations (rather than the rate or mean).\n\na. What does the Poisson model *assume* about the SD of the data, in terms of $\\lambda$?\nb. Use the invariance property to estimate the SD of the operations counts in each city from $\\hat{\\lambda}$.\nc. Compute the sample SD in each city and compare. What do you find, and what does it tell you about the model?\n\n::: {.hint label=\"For parts (a) and (b)\"}\n\nFor a Poisson distribution, how is the variance related to the mean? Write the SD as a function of $\\lambda$, then estimate it by plugging in $\\hat{\\lambda}$.\n\nThe [distributions appendix](https://pos5747.github.io/notes/appendicies/999-distributions.html#poisson-distribution) has the answer.\n\n:::\n\n::: {.hint label=\"For part (c)\"}\n\nYou already grouped the operations counts by city to compute $\\hat{\\lambda}$ in part (b). Apply that same grouping here, and compute each city's sample SD with `sd()`.\n\n:::\n\n::: sol\n\n**Part (a)** Recall that the Poisson has $\\text{Var}(Y) = E(Y) = \\lambda$, so the model assumes the SD is $\\sqrt{\\lambda}$. In this case, the spread is *determined by* the mean. The variance and the mean have no freedom to differ.\n\n**Parts (b) and (c)** By invariance, we estimate the SD with $\\widehat{\\text{SD}} = \\sqrt{\\hat{\\lambda}}$.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load holland's data\nholland2015 <- crdata::holland2015\n\nholland2015 |>\n  group_by(city) |>\n  summarize(lambda_hat = mean(operations),\n            sd_implied = sqrt(lambda_hat),\n            sd_sample  = sd(operations))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  city     lambda_hat sd_implied sd_sample\n  <chr>         <dbl>      <dbl>     <dbl>\n1 bogota         8.89       2.98      6.94\n2 lima          23.2        4.82     18.8 \n3 santiago       2.71       1.64      4.94\n```\n\n\n:::\n:::\n\n\n\nThe comparison fails in every city, and in the same direction: the sample SDs run roughly two to four times the model-implied SDs (Santiago 4.9 vs. 1.6; Bogotá 6.9 vs. 3.0; Lima 18.8 vs. 4.8). These counts are far more dispersed than a Poisson allows. This is called *overdispersion*, and it's almost always present in count data.\n\nNotice what kind of failure this is. Nothing is wrong with $\\sqrt{\\hat{\\lambda}}$ as an estimate of *the model's* SD. Invariance did its job. The problem lies with the model. The Poisson assumes a particular relationship between the SD and the mean. These data are inconsistent with that assumed relationship. This is exactly the mismatch the predictive-distribution chapter showed graphically for Lima.\n\n:::\n\n# When the Recipe Fails\n\n## The Discrete Uniform {ref=\"discrete-uniform\"}\n\nSuppose a discrete uniform distribution on $\\{0, 1, \\ldots, K\\}$, with pmf $f(x; K) = \\frac{1}{K + 1}$ for $x \\in \\{0, 1, \\ldots, K\\}$. Suppose we observe a sample of size 3: 276, 159, and 912.\n\na. Find the ML estimate of $K$. *Hint: The likelihood is discontinuous in $K$, so differentiate-and-solve will mislead you. But the maximum is immediately apparent once you write out the likelihood.*\nb. Find the method of moments estimate of $K$. *Hint: The mean of this distribution is $\\tfrac{K}{2}$. Set the sample mean equal to the model mean and solve.*\nc. For these data, the method of moments estimate falls below the largest observation. This is unsatisfying because it's an estimate of $K$ that the data themselves rule out. How bad can this get? Construct a three-observation dataset that makes the ratio $\\hat{K}_{MM} / \\max(x)$ as small as you can. What is the smallest value the ratio can take with three observations?\nd. In a sentence or two, say what these two failures teach us about choosing an estimator.\n\n::: {.hint label=\"For part (c)\"}\n\nThe ratio you're minimizing is $2 \\cdot \\text{avg}(x) / \\max(x)$ (i.e., part (b)'s formula divided by the largest observation). With $\\max(x)$ fixed, which direction should you push the other two observations to shrink the average? Work that out before you pick numbers.\n\n:::\n\n::: {.hint label=\"For part (c), a second nudge\"}\n\nFact: this distribution never produces a value below 0, so that's the floor for any observation you choose. Combined with part (b)'s formula, how far can you push $\\text{avg}(x)$ down without changing $\\max(x)$?\n\n:::\n\n::: {.hint label=\"Self-check\"}\n\nPlug your candidate dataset from part (c) into the code below and confirm the ratio matches what you computed by hand.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(a, b, c)               # your three-observation dataset from part (c)\nK_hat_mm <- 2 * mean(x)       # method of moments estimate, from part (b)\nratio <- K_hat_mm / max(x)\nratio\n```\n:::\n\n\n\n:::\n\n::: sol\n\n**Part (a)** The likelihood is\n\n$$\nL(K) = \\prod_{i=1}^N \\frac{1}{K+1} = \\left(\\frac{1}{K+1}\\right)^N\n$$\n\nif every observation lies in $\\{0, 1, \\ldots, K\\}$, and $0$ if *any* observation exceeds $K$. This function is not differentiable, so the recipe isn't useful. To make $L(K)$ as large as possible, we make $K$ as small as the data allow, so $\\hat{K}_{ML} = \\max(x) = 912$.\n\n**Part (b)** Set the sample mean equal to the model mean, $\\text{avg}(x) = \\frac{\\hat{K}_{MM}}{2}$. Then, solving for $\\hat{K}_{MM}$ gives $\\hat{K}_{MM} = 2 \\cdot \\text{avg}(x) = 2 \\cdot 449 = 898$.\n\n**Part (c)** We want $2 \\cdot \\text{avg}(x)$ small while $\\max(x)$ stays large, so push the other two observations as low as they can go, which is $x = (0, 0, 912)$. Then $\\text{avg}(x) = 304$, $\\hat{K}_{MM} = 608$, and the ratio is $608/912 = \\tfrac{2}{3}$. This means that $\\tfrac{2}{3}$ is the floor. With three observations, $\\text{avg}(x) \\geq \\frac{\\max(x)}{3}$.\n\n$$\n\\hat{K}_{MM} = 2 \\cdot \\text{avg}(x) \\;\\geq\\; \\frac{2}{3}\\max(x).\n$$\n\n**Part (d)** Both estimators \"work\" in the sense that the procedure produces a number. But each misbehaves differently. The ML estimate is the smallest *logically possible* value of $K$, which intuition says is probably too low. And the method of moments can produce values of $K$ the data have already contradicted.\n\n:::\n\n# Checking the Model\n\n## The Remaining Wait {ref=\"memorylessness\"}\n\nThe exponential distribution from [exponential-model]{.ex-ref} is our first model for durations. What does the model actually claim about waiting? This turns out to be really interesting and important!\n\na. Show that the cdf of the exponential distribution is $F(t; \\lambda) = \\Pr(T \\leq t) = 1 - e^{-\\lambda t}$. Then define the *survival function* $S(t; \\lambda) = \\Pr(T > t) = 1 - F(t; \\lambda)$ and interpret it (i.e., for an input $t$, what does $S$ return)?\nb. Suppose you've already waited $s$ units of time without the event occurring. Using the definition of conditional probability and the survival function, find $\\Pr(T > t + s \\mid T > s)$. Compare your answer to $\\Pr(T > t)$. What do you notice? Write it down in one sentence *before* you start part (c).\nc. Now check your sentence against a simulation. The code below draws 10,000 durations and computes, *for the draws that lasted past time 2*, how much *longer* they lasted.\n\n    ```r\n    set.seed(123)\n    durations <- rexp(10000, rate = 1)\n    remaining <- durations[durations > 2] - 2\n    ```\n\n    Compare the distribution of `remaining` to the distribution of the original `durations` (plotting both ECDFs in one panel works well). Do the plots confirm or refute your sentence from (b)?\nd. Name one political process that your finding might describe well, and one it clearly can't. Say why.\n\n::: {.hint label=\"For part (a)\"}\n\nThe cdf accumulates the density: $F(t; \\lambda) = \\int_0^t \\lambda e^{-\\lambda u}\\, du$. Use integration rules from Week 1.\n\n:::\n\n::: {.hint label=\"For part (b)\"}\n\nWhat is the event \"$T > t + s$ *and* $T > s$\"? Notice that one of the two conditions implies the other.\n\n:::\n\n::: {.hint label=\"For part (b), a second nudge\"}\n\nWrite the conditional probability as a ratio of survival functions and substitute $S(t; \\lambda) = e^{-\\lambda t}$.\n\n:::\n\n::: sol\n\n**Part (a)** Integrate the pdf from $0$ to $t$:\n\n$$\nF(t; \\lambda) = \\int_0^t \\lambda e^{-\\lambda u}\\, du = \\lambda \\left[ \\frac{-1}{\\lambda} e^{-\\lambda u} \\right]_0^t = -e^{-\\lambda t} + e^{0} = 1 - e^{-\\lambda t}.\n$$\n\nSubtracting from one, we obtain the survival function:\n\n$$\nS(t; \\lambda) = \\Pr(T > t) = e^{-\\lambda t}.\n$$\n\n$S$ returns the probability that the event *has not yet occurred* by time $t$. (The cdf returns the probability that it *has*.) If $t = 3$ years and $S(3; \\lambda) = 0.20$, there's a 20% chance the event happens after year three.\n\n**Part (b)** The key step: when $T > t + s$, then $T > s$ automatically, so the joint event is just $T > t + s$. By the definition of conditional probability,\n\n$$\n\\Pr(T > t + s \\mid T > s) = \\frac{\\Pr(T > t + s)}{\\Pr(T > s)} = \\frac{e^{-\\lambda (t + s)}}{e^{-\\lambda s}} = e^{-\\lambda t} = \\Pr(T > t).\n$$\n\nDividing exponentials subtracts the exponents, so the $s$ cancels and the two are exactly the same. **This is important**: the probability of waiting at least $t$ more units of time doesn't depend on how long you've already waited. The distribution of the remaining wait, given that you've waited $s$ already, is exactly the distribution of the original wait. This is the **memoryless property**, and the exponential is the *only* continuous distribution that has it.\n\n**Part (c)** Here $s = 2$. The vector `remaining` holds the leftover durations of the draws that made it past time 2, so it is a sample from the distribution of $T - s$ given $T > s$. Plotting its ECDF over the ECDF of the original `durations` allows us to check part (b)'s claim at every $t$ at once.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\ndurations <- rexp(10000, rate = 1)\nremaining <- durations[durations > 2] - 2\n\n# stack the two sets of durations into one tidy data frame\ndf <- bind_rows(\n  data.frame(duration = durations, type = \"original\"),\n  data.frame(duration = remaining, type = \"remaining\")\n)\n\n# compare the two ecdfs in a single panel\nggplot(df, aes(x = duration, color = type)) +\n  stat_ecdf()\n```\n\n::: {.cell-output-display}\n![](wk02-exercises_files/figure-html/ex15-solution-1.png){width=672}\n:::\n:::\n\n\n\nThe two ECDFs sit right on top of each other! Of the 10,000 draws, only 1353 survived past time 2, so the `remaining` curve rests on about a seventh as much data and wiggles around a little more.\n\n**Part (d)** The property is perhaps plausible for waits \"with no internal clock,\" such as the time between militarized disputes in a region or between filibusters in a session. (The classic non-political example is the time between lightning strikes, and [hockey]{.ex-ref} tests the time between hits in a hockey game.) Memorylessness fails for cabinet duration, the example mentioned back in [exponential-model]{.ex-ref}. If I ask how much longer a coalition will last, you'd definitely want to know how long it has lasted already. Human lifespans are similar. If I asked how much longer a person will live, you'd definitely want to know how old that person is now.\n\n:::\n\n## Herron's Hockey Data {ref=\"hockey\"}\n\nHerron's hockey data set records the time between hits[^hit] in the regulation periods of all 82 regular-season games for the Chicago Blackhawks.\n\n[^hit]: From [Wikipedia](https://en.wikipedia.org/wiki/Ice_hockey_statistics), a hit is: *\"Intentionally initiated contact with the player possessing the puck that causes that player to lose possession of the puck.\"*\n\nBefore looking at the data, do you expect an exponential model to fit the times between hits? Write down your prediction and your reasoning. Notice that your derivation in [memorylessness]{.ex-ref} *can't* settle this one. Whether hits actually behave this way is an empirical question. It could be that hits cluster (a hit sparks retaliation). Or maybe a long lull makes the next hit imminent.\n\nModel `seconds_btw_hits` as exponential, estimate the rate and the mean, and use the predictive distribution to evaluate the fit. Were you right?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load data directly from the web\nhockey <- read_csv(\"https://gist.githubusercontent.com/carlislerainey/0bc3018cd2377022fd045e1c932110a2/raw/fd6dcc28a7c0df456d779e9f0d7a82f15b9b5844/herron-hockey.csv\")\n\n# quick look\nglimpse(hockey)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,175\nColumns: 5\n$ game_id                  <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, …\n$ period_id                <dbl> 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 2, …\n$ time_of_hit              <chr> \"25S\", \"2M 8S\", \"2M 58S\", \"3M 8S\", \"4M 13S\", …\n$ seconds_played_in_season <dbl> 25, 128, 178, 188, 253, 560, 643, 1407, 1825,…\n$ seconds_btw_hits         <dbl> NA, 103, 50, 10, 65, 307, 83, 764, 418, 535, …\n```\n\n\n:::\n:::\n\n\n\n::: hint\n\nThe general recipe for the predictive distribution is in the notes and it works for any fitted distribution. You've already derived a formula for $\\hat{\\lambda}$ in [exponential-model]{.ex-ref}. Get that number for the hockey data first. Then simulate.\n\n:::\n\n::: hint\n\nThe notes offer a three-step procedure: estimate $\\hat{\\lambda}$ (you derived the estimator in [exponential-model]{.ex-ref}), simulate several fake data sets from the fitted exponential distribution, and compare them to the observed data with histograms or ECDFs. \n\n:::\n\n::: sol\n\nFirst the estimates, using $\\hat{\\lambda} = 1/\\text{avg}(t)$:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# drop the one missing value (the season's first hit has no predecessor)\ny <- na.omit(hockey$seconds_btw_hits)\n\n# ml estimates of the rate and the mean\nlambda_hat <- 1/mean(y)\nlambda_hat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.003980079\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(y)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 251.2513\n```\n\n\n:::\n:::\n\n\n\nThe mean time between hits is about 251 seconds (a hit every four minutes or so), which makes the rate $\\hat{\\lambda} \\approx 0.004$ hits per second.\n\nNow the predictive check:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create observed data set\nobserved_data <- tibble(seconds_btw_hits = y, type = \"observed\")\n\n# simulate five fake data sets\nset.seed(1917)\nn <- length(y)\nsim_list <- list()\nfor (i in 1:5) {\n  y_pred <- rexp(n, rate = lambda_hat)\n  sim_list[[i]] <- tibble(seconds_btw_hits = y_pred,\n                          type = paste0(\"simulated #\", i))\n}\n\n# combine the fake and observed data sets\ngg_data <- bind_rows(sim_list) |>\n  bind_rows(observed_data)\n\n# plot the observed and fake data sets\nggplot(gg_data, aes(x = seconds_btw_hits)) +\n  geom_histogram(bins = 30) +\n  facet_wrap(vars(type))\n```\n\n::: {.cell-output-display}\n![](wk02-exercises_files/figure-html/ex16-check-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# a sharper comparison: all the ecdfs in one panel\ngg_data2 <- gg_data |>\n  separate(type, into = c(\"type\", \"version\"))\n\nggplot(gg_data2, aes(x = seconds_btw_hits, color = type, group = version)) +\n  stat_ecdf()\n```\n\n::: {.cell-output-display}\n![](wk02-exercises_files/figure-html/ex16-ecdf-1.png){width=672}\n:::\n:::\n\n\n\nThese distributions look *very* similar. In the ECDF overlay, the observed curve hides among the simulated ones. \n\nThe exponential fits; this is perhaps substantively surprising. In sports we talk constantly about momentum, big swings, retaliation, tension building during a lull. If any of that mattered for hits, the time since the last hit would predict the time to the next one, but the distribution of hits seems memoryless.\n\n:::\n\n## Heavy Tails: GDP Growth and the Location-Scale *t* {ref=\"t-model\"}\n\nThe location-scale *t* distribution is a flexible model for data with heavier-than-normal tails (i.e., more extreme observations than a normal model expects). Its pdf is\n\n$$\nf(y; \\mu, \\sigma, \\nu) = \\frac{\\Gamma\\left(\\frac{\\nu+1}{2}\\right)}{\\Gamma\\left(\\frac{\\nu}{2}\\right) \\sqrt{\\nu \\pi} \\, \\sigma} \\left[1 + \\frac{1}{\\nu} \\left( \\frac{y - \\mu}{\\sigma} \\right)^2 \\right]^{-\\frac{\\nu+1}{2}},\n$$\n\nwhere $\\mu$ is the location parameter (it shifts the distribution, like the normal's mean), $\\sigma$ is the scale parameter (it spreads the distribution, like the normal's SD), and $\\nu$ controls the heaviness of the tails. The $\\mu$ and $\\sigma$ work similarly to a normal model. Small $\\nu$ means heavy tails, and as $\\nu \\to \\infty$ the distribution converges to the normal. (For $\\nu > 10$ or so, the $t$ and the normal distributions are hard to tell apart, and $\\nu = 1$ is the Cauchy.)\n\nIn R, `metRology::dt.scaled()` computes this density.^[`metRology` is on CRAN: `install.packages(\"metRology\")`.] Be careful with the argument names in `metRology::dt.scaled()`. `mean` is the location $\\mu$ (though $\\mu$ isn't always a mean), `sd` is the scale $\\sigma$ (though $\\sigma$ isn't the SD), and `df` is $\\nu$.\n\nWe'll model cross-national GDP growth, which mixes a tight cluster of ordinary economies with a few extreme performers. The code below downloads percentage GDP growth for 2022 from the World Bank.^[The `WDI` package (CRAN) fetches the data live, so this chunk needs an internet connection.]\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load package\nlibrary(WDI)\n\n# get annual % gdp growth for 2022\n# - \"NY.GDP.MKTP.KD.ZG\" is percentage gdp growth\n#   see https://data.worldbank.org/indicator/NY.GDP.MKTP.KD.ZG\ndf <- WDI(indicator = \"NY.GDP.MKTP.KD.ZG\",\n          start = 2022,\n          end = 2022,\n          extra = TRUE) %>%\n  # drop aggregates (e.g., European Union)\n  filter(region != \"Aggregates\") %>%\n  mutate(pct_gdp_growth = NY.GDP.MKTP.KD.ZG) %>%\n  select(country, year, region, pct_gdp_growth) %>%\n  na.omit()\n\n# plot histogram\nggplot(df, aes(x = pct_gdp_growth)) +\n  geom_histogram(bins = 40)\n```\n\n::: {.cell-output-display}\n![](wk02-exercises_files/figure-html/ex17-data-1.png){width=672}\n:::\n:::\n\n\n\na. As a baseline, model `pct_gdp_growth` with a normal distribution. Estimate $\\mu$ and $\\sigma$ by ML (both have closed forms), then use the predictive distribution to assess the fit. What does the normal model miss?\nb. Now fit the location-scale *t*, estimating $\\mu$, $\\sigma$, and $\\nu$ with `optim()`. Complete the skeleton below by filling in the two blanked lines.\n\n    ```r\n    ll_t <- function(par, y) {\n      # unpack the parameter vector\n      mu    <- par[1]   # location\n      sigma <- par[2]   # scale\n      nu    <- par[3]   # degrees of freedom (tail heaviness)\n\n      # 1. guard: impossible parameter values should return -Inf\n      #    ... your code here ...\n\n      # 2. compute the log-likelihood with metRology::dt.scaled()\n      #    ll <- ... your code here ...\n\n      return(ll)\n    }\n    ```\n\n    Reasonable starting values are `c(median(y), sd(y), 10)`.\nc. Use the predictive distribution to compare the *t* model to the normal model. What is the ML estimate of $\\nu$, and what does it give us?\n\n::: {.hint label=\"For part (b)\"}\n\nThe density is undefined when the scale or the tail parameter is zero or negative. Decide what your function should return for those impossible values, so that `optim()` doesn't consider them.\n\n:::\n\n::: {.hint label=\"For part (b), the code\"}\n\nIf `sigma` or `nu` is not positive, return `-Inf`; otherwise return `sum(dt.scaled(y, mean = mu, sd = sigma, df = nu, log = TRUE))`.\n\n:::\n\n::: {.hint label=\"Self-check\"}\n\nYour normal-model estimates in part (a) must match the closed forms exactly so that $\\hat{\\mu}$ = `mean(y)` and $\\hat{\\sigma}$ = `sqrt(sum((y - mean(y))^2)/length(y))`. If your predictive simulations look off, check these two numbers before debugging anything else.\n\n:::\n\n::: sol\n\n**Part (a)** The normal ML estimates have closed forms, so no optimizer is needed:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# save the variable as y to simplify the code\ny <- df$pct_gdp_growth\nn <- length(y)\n\n# ml estimates for the normal model\nmu_hat <- mean(y)\nsigma_hat <- sqrt(sum((y - mu_hat)^2)/n)\nc(mu_hat = mu_hat, sigma_hat = sigma_hat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   mu_hat sigma_hat \n 4.418957  6.766710 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# predictive check for the normal model\nobserved_data <- tibble(pct_gdp_growth = y, type = \"observed\")\n\nset.seed(2026)\nsim_list <- list()\nfor (i in 1:5) {\n  y_pred <- rnorm(n, mean = mu_hat, sd = sigma_hat)\n  sim_list[[i]] <- tibble(pct_gdp_growth = y_pred,\n                          type = paste0(\"simulated #\", i))\n}\n\ngg_data <- bind_rows(sim_list) |>\n  bind_rows(observed_data)\n\nggplot(gg_data, aes(x = pct_gdp_growth)) +\n  geom_histogram(bins = 40) +\n  facet_wrap(vars(type))\n```\n\n::: {.cell-output-display}\n![](wk02-exercises_files/figure-html/ex17-normal-check-1.png){width=672}\n:::\n:::\n\n\n\nThe normal model misses in two directions at once. To accommodate the handful of extreme observations, it needs a large SD (about 6.8 here). But that large SD forces the simulated data sets to spread out, so they show too little of the tight clustering around the average that the observed data have, and still none of the truly extreme values. The observed panel has a sharper peak *and* wilder outliers than any simulated panel.\n\n**Part (b)** The completed skeleton:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load package\nlibrary(metRology)  # for dt.scaled()\n\n# log-likelihood for the location-scale t\nll_t <- function(par, y) {\n  # unpack the parameter vector\n  mu    <- par[1]   # location\n  sigma <- par[2]   # scale\n  nu    <- par[3]   # degrees of freedom (tail heaviness)\n\n  # 1. guard: impossible parameters get -Inf, so optim() walks away\n  if (sigma <= 0 | nu <= 0) return(-Inf)\n\n  # 2. compute the log-likelihood\n  ll <- sum(dt.scaled(y, mean = mu, sd = sigma, df = nu, log = TRUE))\n\n  return(ll)\n}\n\n# maximize\nest <- optim(par = c(median(y), sd(y), 10),\n             fn = ll_t,\n             y = y,\n             control = list(fnscale = -1),\n             method = \"Nelder-Mead\")\nest$convergence\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nest$par\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.379386 2.561957 1.884743\n```\n\n\n:::\n:::\n\n\n\n\n**Part (c)** The predictive check for the *t* model:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2027)\nsim_list <- list()\nfor (i in 1:5) {\n  y_pred <- rt.scaled(n, mean = est$par[1], sd = est$par[2], df = est$par[3])\n  sim_list[[i]] <- tibble(pct_gdp_growth = y_pred,\n                          type = paste0(\"simulated #\", i))\n}\n\ngg_data <- bind_rows(sim_list) |>\n  bind_rows(observed_data)\n\nggplot(gg_data, aes(x = pct_gdp_growth)) +\n  geom_histogram(bins = 40) +\n  facet_wrap(vars(type))\n```\n\n::: {.cell-output-display}\n![](wk02-exercises_files/figure-html/ex17-t-check-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# the ecdf overlay for a sharper comparison\ngg_data2 <- gg_data |>\n  separate(type, into = c(\"type\", \"version\"))\n\nggplot(gg_data2, aes(x = pct_gdp_growth, color = type, group = version)) +\n  stat_ecdf()\n```\n\n::: {.cell-output-display}\n![](wk02-exercises_files/figure-html/ex17-t-ecdf-1.png){width=672}\n:::\n:::\n\n\n\nThe fitted *t* distributions match the observed data far better than the normal model. The simulated panels now show the tight central cluster *and* occasional extreme values. In the ECDF overlay, the observed curve is hard to pick out.\n\nThe estimate of the degrees of freedom is $\\hat{\\nu} \\approx 1.9$. This means that these data have extremely heavy tails (almost a Cauchy). A $t$ has a finite variance only when $\\nu > 2$, so the fitted model doesn't have one. This is a sharp reminder that $\\sigma$ is a \"scale\" and not an SD. \n\n$\\nu$ gives us a third parameter that separates \"how spread out is the middle?\" ($\\sigma \\approx 2.6$, against the normal's inflated 6.8) from \"how common are extreme values?\". With the tails handled by $\\nu$, the scale can describe the typical countries. If you'd like to see what these heavy tails do for *robustness* (what happens to each model when one observation is wildly wrong), see [ep-corrupted]{.ex-ref}.\n\n:::\n\n# Reflection\n\n## What Should a Model Match? {ref=\"reflection\"}\n\nThe exercises above repeatedly compare a fitted model against observed data, and the models often disagree with the data about everything *except* the mean. Three questions, a few sentences each:\n\na. Is it important that a model mimic features of the data beyond the mean?\nb. When might the SD, the tails, or the behavior of waits matter *substantively*, for the political question itself?\nc. When might those features matter *statistically*, even if the mean is all you care about?\n\n::: {.hint label=\"For part (a)\"}\n\n[four-models]{.ex-ref} earlier on this page fit several different models to the same data. Reread it and compare what varied across the fits to what didn't, then think about what that contrast implies for when matching the mean is enough.\n\n:::\n\n::: {.hint label=\"For part (b)\"}\n\nTwo of the exercises above already put this question in a concrete setting: [t-model]{.ex-ref} compared a normal model to a heavier-tailed model for a country's GDP growth, and [memorylessness]{.ex-ref} asked whether a wait so far should change your forecast of the wait still to come. Reread whichever is closer to where you're stuck, and ask what would go wrong for the actual political question, not just for the histogram, if you'd picked the wrong model.\n\n:::\n\n::: sol\n\nThere's no single right answer here. But here are a few thoughts:\n\n**(a)** It depends on the target. [four-models]{.ex-ref} showed four wildly different models agreeing exactly about the mean, so for estimating a mean, mimicry beyond the mean can be surprisingly optional. But a model might be useful when we lean on the parts beyond the mean and some interesting quantities eventually do.\n\n**(b)** Your question might concern more than the center. If you care about the *chance of an extreme outcome* (a deep recession, an unusually long stretch without a coup), the tails are the substance. If you care about *how long until an event, given the wait so far*, the memory structure is the substance. If you care about variability, then the scale or SD might matter most. A normal model of GDP growth answers tail questions badly even though its mean is fine.\n\n**(c)** Looking ahead, standard errors depend on more of the distribution than its center. A model whose spread or tails are wrong can deliver a fine point estimate with badly wrong uncertainty.\n\n:::\n\n# Extra Practice {.extra-practice}\n\n## Bernoulli Grid Search {ref=\"ep-grid\"}\n\nSuppose you design a Bernoulli experiment that generates successes and failures with an unknown probability $\\pi$. You want to estimate $\\pi$, so you run the experiment three times and get the outcomes `y <- c(0, 1, 0)`, where `0` is a failure and `1` is a success.\n\nUse ML to estimate $\\pi$. *But don't find the maximum analytically* or with a hill-climbing algorithm. Instead, use a *grid search*: use `seq()` to create ten to twenty candidate values of $\\pi$, compute the log-likelihood for each candidate, and locate the candidate that produces the largest log-likelihood. Report your results in a figure. (A table works too, if you'd like both.)\n\n::: hint\n\nYou'll need the Bernoulli log-likelihood as a function you can evaluate. That is, write $\\log L(\\pi) = k \\log(\\pi) + (N - k)\\log(1 - \\pi)$, with $k$ successes in $N$ trials, as an R function of $\\pi$. Then you can give this R function the whole grid at once to compute the log-likelihoods for the entire grid.\n\n:::\n\n::: {.hint label=\"Self-check\"}\n\nYour grid search and the closed-form Bernoulli estimate from your notes should land on nearly the same $\\pi$. The grid is just more coarse. Compute both, store them, and check that they differ by less than your grid's spacing.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# best_grid_pi: the pi your grid search returned as the best candidate\n# closed_form_pi: the closed-form Bernoulli estimate from your notes\nbest_grid_pi <- NA\nclosed_form_pi <- mean(y)\nabs(best_grid_pi - closed_form_pi)\n```\n:::\n\n\n\n:::\n\n::: sol\n\nFirst, create a function to compute the log-likelihood.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create function to compute log-likelihood\ncompute_log_lik <- function(pi_grid, y) {\n  k <- sum(y)\n  N <- length(y)\n  log_lik <- k*log(pi_grid) + (N - k)*log(1 - pi_grid)\n  return(log_lik)\n}\n```\n:::\n\n\n\nOne R gotcha worth highlighting: we named the argument `pi_grid`, not `pi`, because `pi` is R's built-in constant 3.14159.... Naming a variable `pi` works, but then a stray line that *forgot* to define it would silently use 3.14159... instead of producing an error. \n\nNow compute the log-likelihood for 11 evenly spaced candidates from 0 to 1 and plot.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create data set\ny <- c(0, 1, 0)\n\n# candidate values and their log-likelihoods\npi_grid <- seq(0, 1, length.out = 11)\ngrid_df <- data.frame(pi_grid = pi_grid,\n                      log_lik = compute_log_lik(pi_grid, y))\n\n# plot log-likelihood against the candidates\nggplot(grid_df, aes(x = pi_grid, y = log_lik)) +\n  geom_point() +\n  geom_line()\n```\n\n::: {.cell-output-display}\n![](wk02-exercises_files/figure-html/ep1-grid-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# a table, for those who want the numbers\ngrid_df |>\n  rename(\"Candidate Value\" = pi_grid,\n         \"Log-Likelihood\" = log_lik) |>\n  tinytable::tt(digits = 3)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_zzye6k0i70oufpkxlxwi = TinyTable.createTableFunctions(\"tinytable_zzye6k0i70oufpkxlxwi\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '11', j: 1 }, { i: '11', j: 2 } ], css_id: 'tinytable_css_aazbtz5ryseph8ioazxa',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 } ], css_id: 'tinytable_css_vqz679tslq8e8596jq8x',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_zzye6k0i70oufpkxlxwi.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_zzye6k0i70oufpkxlxwi td.tinytable_css_aazbtz5ryseph8ioazxa, #tinytable_zzye6k0i70oufpkxlxwi th.tinytable_css_aazbtz5ryseph8ioazxa {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_zzye6k0i70oufpkxlxwi td.tinytable_css_vqz679tslq8e8596jq8x, #tinytable_zzye6k0i70oufpkxlxwi th.tinytable_css_vqz679tslq8e8596jq8x {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_zzye6k0i70oufpkxlxwi\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Candidate Value</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Log-Likelihood</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">0</td>\n                  <td data-row=\"1\" data-col=\"2\">-Inf</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">0.1</td>\n                  <td data-row=\"2\" data-col=\"2\">-2.51</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">0.2</td>\n                  <td data-row=\"3\" data-col=\"2\">-2.06</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\">0.3</td>\n                  <td data-row=\"4\" data-col=\"2\">-1.92</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">0.4</td>\n                  <td data-row=\"5\" data-col=\"2\">-1.94</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\">0.5</td>\n                  <td data-row=\"6\" data-col=\"2\">-2.08</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">0.6</td>\n                  <td data-row=\"7\" data-col=\"2\">-2.34</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\">0.7</td>\n                  <td data-row=\"8\" data-col=\"2\">-2.76</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">0.8</td>\n                  <td data-row=\"9\" data-col=\"2\">-3.44</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\">0.9</td>\n                  <td data-row=\"10\" data-col=\"2\">-4.71</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"1\">1</td>\n                  <td data-row=\"11\" data-col=\"2\">-Inf</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\nAmong the candidates, $\\pi = 0.3$ produces the largest log-likelihood (about $-1.92$, against $-1.94$ for $\\pi = 0.4$). I knew the winner would be 0.3 or 0.4 before computing anything, because the ML estimate is the sample mean, $\\text{avg}(y) = \\frac{1}{3} \\approx 0.33$, and the log-likelihood rises to that peak and falls away on both sides, so the best candidate has to be one of the two that bracket it. Which of the two wins depends on the shape of the curve, not only on distance. And notice that the grid *cannot* report $\\frac{1}{3}$ itself, because 0.33 isn't a candidate, which is precisely the limitation [grid-miss]{.ex-ref} asked about. (The endpoints show as missing in the plot: at $\\pi = 0$ and $\\pi = 1$ the log-likelihood is $-\\infty$.)\n\n:::\n\n## `optim()` Meets the Closed Form {ref=\"ep-optim\"}\n\nWe found that the sample average is the ML estimator of the parameter $\\lambda$ of the Poisson distribution. For the data set `y <- c(12, 7, 9, 12, 10)`, show that maximizing the Poisson log-likelihood with `optim()` produces the same answer as the closed-form solution.\n\n::: hint\n\nYou need a Poisson log-likelihood function before you can call `optim()`. See the example for the beta distribution in the notes. Then write the Poisson version yourself.\n\n:::\n\n::: hint\n\nOnce you have a log-likelihood function, the beta example in the notes walks through every argument the `optim()` call needs, one by one, in the numbered list right after the call.\n\n:::\n\n::: {.hint label=\"Self-check\"}\n\nBefore calling `optim()`, check that the log-likelihood function itself works as expected. It should return a larger value at the closed-form estimate than at a nearby value that isn't the estimate.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# evaluate your log-likelihood function at the closed-form estimate\nll_fn(par = mean(y), y = y)\n\n# and at a nearby value that is NOT the estimate\nll_fn(par = mean(y) + 1, y = y)\n\n# if ll_fn is correct, the first number is larger\n```\n:::\n\n\n\n:::\n\n::: sol\n\nFirst, the closed-form solution.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# data set\ny <- c(12, 7, 9, 12, 10)\n\n# closed-form maximum\nmean(y)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10\n```\n\n\n:::\n:::\n\n\n\nNext, the numerical solution.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create log-likelihood function to maximize\nll_pois <- function(par, y) {\n  sum(dpois(y, lambda = par, log = TRUE))\n}\n\n# maximize the log-likelihood function\nest <- optim(par = 1,\n             fn = ll_pois,\n             y = y,\n             control = list(fnscale = -1),\n             method = \"Brent\",\n             lower = 0, upper = 100)\n\n# print the lambda that maximizes the log-likelihood\nest$par\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10\n```\n\n\n:::\n:::\n\n\n\nBoth find $\\hat{\\lambda} = 10$. The numerical solution isn't *exactly* 10, because of *very* small numerical errors (the difference is around $10^{-8}$).\n\n:::\n\n\n## Corrupted Data {ref=\"ep-corrupted\"}\n\nTake the WDI GDP-growth data from [t-model]{.ex-ref} and corrupt them by replacing one observation with a severe data-entry error. Perhaps replace one value of `pct_gdp_growth` with 10,000. Re-fit the normal and *t* models. How did each model's estimate of the *location* change? Why? Is resistance to corruption a desirable property?\n\n::: sol\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# save the variable as y (to simplify the code)\ny <- df$pct_gdp_growth\n\n# corrupt the data\ny_corrupt <- y\ny_corrupt[1] <- 10000\n\n# normal ml estimates, clean and corrupted\nc(mu_hat = mean(y),\n  sigma_hat = sqrt(sum((y - mean(y))^2)/length(y)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   mu_hat sigma_hat \n 4.418957  6.766710 \n```\n\n\n:::\n\n```{.r .cell-code}\nc(mu_hat = mean(y_corrupt),\n  sigma_hat = sqrt(sum((y_corrupt - mean(y_corrupt))^2)/length(y_corrupt)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   mu_hat sigma_hat \n  52.2957  689.7820 \n```\n\n\n:::\n:::\n\n\n\nThe data-entry error drags the normal model's estimated mean from about 4.4 to about 52. This is percentage GDP growth, so that's a huge error.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# t ml estimates, clean and corrupted (ll_t() comes from the heavy-tails exercise)\nest_clean <- optim(par = c(median(y), sd(y), 10),\n                   fn = ll_t, y = y,\n                   control = list(fnscale = -1), method = \"Nelder-Mead\")\nest_corrupt <- optim(par = c(median(y_corrupt), sd(y_corrupt), 10),\n                     fn = ll_t, y = y_corrupt,\n                     control = list(fnscale = -1), method = \"Nelder-Mead\")\nc(mu_clean = est_clean$par[1], mu_corrupt = est_corrupt$par[1],\n  nu_clean = est_clean$par[3], nu_corrupt = est_corrupt$par[3])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  mu_clean mu_corrupt   nu_clean nu_corrupt \n  4.379386   4.376540   1.884743   1.438458 \n```\n\n\n:::\n:::\n\n\n\nThe *t* model's location estimate barely moves. It's about 4.4 in both the original and the corrupted data. With heavy tails available, the model can file the absurd observation under \"weird draw\" without letting it drag the location away from the correct value. Notice that $\\hat{\\nu}$ drops from about 1.9 to about 1.4, making the tails heavier still to accommodate this new, absurd value. The normal distribution has thin tails that make 10,000 essentially impossible. It has no option but to move the whole distribution toward this absurd value.\n\nIs the *t*'s behavior desirable? Often, yes! If data-entry errors happen, we'd rather our estimates not swing wildly with each error. However, the resistance applies to *correct* extreme observations, and whether those outliers should move the estimate of the typical value is a substantive question, not a statistical one. A robust model is a choice about which observations speak to \"typical\". That's a choice worth being thoughtful about.\n\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}